"""Music-artist and video-game news feeds - Google News search per artist/game.

Same shape as ``life_data.LifeFeed`` (query, id, name, kicker, column) so it
plugs into the same getters and ``SOURCES`` generation. Ids use ``music-`` and
``game-`` prefixes for their own card icons.
"""

from __future__ import annotations

import re

Feed = tuple[str, str, str, str, str]


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def _q(text: str) -> str:
    return re.sub(r"\s+", "+", text.strip())


_ARTISTS: list[str] = [
    # Pop
    "Taylor Swift",
    "Beyonce",
    "Ariana Grande",
    "Billie Eilish",
    "Dua Lipa",
    "Ed Sheeran",
    "Justin Bieber",
    "Bruno Mars",
    "Lady Gaga",
    "Katy Perry",
    "Rihanna",
    "Adele",
    "Harry Styles",
    "Olivia Rodrigo",
    "Sabrina Carpenter",
    "Charlie Puth",
    "Shawn Mendes",
    "Selena Gomez",
    "Miley Cyrus",
    "Sam Smith",
    "Halsey",
    "Camila Cabello",
    "Doja Cat",
    "SZA",
    "Lana Del Rey",
    "Lorde",
    "The Weeknd",
    "Post Malone",
    "Sia",
    "Pink singer",
    "Chappell Roan",
    "Tate McRae",
    "Gracie Abrams",
    "Benson Boone",
    "Teddy Swims",
    # Hip-hop / rap
    "Drake",
    "Kendrick Lamar",
    "Kanye West",
    "Travis Scott",
    "J Cole",
    "Nicki Minaj",
    "Cardi B",
    "Snoop Dogg",
    "Lil Wayne",
    "Future rapper",
    "21 Savage",
    "Megan Thee Stallion",
    "Tyler the Creator",
    "Lil Baby",
    "Playboi Carti",
    "A$AP Rocky",
    "Ice Spice",
    "Metro Boomin",
    "Jack Harlow",
    "Central Cee",
    "Stormzy",
    "Lil Uzi Vert",
    "Gunna",
    "Latto",
    "GloRilla",
    # Rock / alternative
    "Coldplay",
    "Imagine Dragons",
    "Foo Fighters",
    "Red Hot Chili Peppers",
    "Arctic Monkeys",
    "Twenty One Pilots",
    "Linkin Park",
    "Green Day",
    "Metallica",
    "Muse band",
    "The Killers",
    "Paramore",
    "Fall Out Boy",
    "Panic at the Disco",
    "Radiohead",
    "Pearl Jam",
    "U2 band",
    "Queen band",
    "Blink-182",
    "My Chemical Romance",
    # Country
    "Morgan Wallen",
    "Luke Combs",
    "Zach Bryan",
    "Chris Stapleton",
    "Carrie Underwood",
    "Blake Shelton",
    "Kacey Musgraves",
    "Jason Aldean",
    "Luke Bryan",
    "Cody Johnson",
    # Latin
    "Bad Bunny",
    "Karol G",
    "J Balvin",
    "Shakira",
    "Rosalia",
    "Peso Pluma",
    "Rauw Alejandro",
    "Maluma",
    "Daddy Yankee",
    "Ozuna",
    "Feid",
    "Grupo Frontera",
    # EDM / DJ
    "Calvin Harris",
    "David Guetta",
    "Marshmello dj",
    "Martin Garrix",
    "Skrillex",
    "Zedd",
    "Kygo",
    "Tiesto",
    "Diplo",
    "Alan Walker",
    "Deadmau5",
    "Swedish House Mafia",
    "Illenium",
    "John Summit",
    "Fred again",
    # K-pop
    "BTS",
    "BLACKPINK",
    "Stray Kids",
    "TWICE",
    "NewJeans",
    "SEVENTEEN",
    "aespa",
    "ENHYPEN",
    "Tomorrow X Together",
    "IVE",
    "LE SSERAFIM",
    "ITZY",
    "NCT",
    "Jungkook",
    "Jimin",
    "Lisa Blackpink",
    "Rose Blackpink",
    # R&B / soul
    "Usher",
    "Chris Brown",
    "Frank Ocean",
    "H.E.R.",
    "Daniel Caesar",
    "Giveon",
    "Summer Walker",
    "Brent Faiyaz",
    "Victoria Monet",
    # Legends
    "Elton John",
    "Paul McCartney",
    "Bruce Springsteen",
    "Madonna",
    "Bob Dylan",
    "The Rolling Stones",
    "Stevie Wonder",
    "Mariah Carey",
    "Celine Dion",
    "Cher",
]

_GAMES: list[str] = [
    "Fortnite",
    "Minecraft",
    "Roblox",
    "Call of Duty",
    "Grand Theft Auto",
    "GTA 6",
    "Valorant",
    "League of Legends",
    "Counter-Strike 2",
    "Dota 2",
    "Apex Legends",
    "Overwatch 2",
    "Rainbow Six Siege",
    "PUBG",
    "Rocket League",
    "EA Sports FC",
    "Madden NFL",
    "NBA 2K",
    "The Sims",
    "Animal Crossing",
    "The Legend of Zelda",
    "Super Mario",
    "Pokemon",
    "Super Smash Bros",
    "Elden Ring",
    "Baldur's Gate 3",
    "The Witcher",
    "Cyberpunk 2077",
    "Red Dead Redemption",
    "Assassin's Creed",
    "Far Cry",
    "Halo",
    "Gears of War",
    "Forza Horizon",
    "God of War",
    "Marvel's Spider-Man",
    "The Last of Us",
    "Horizon Forbidden West",
    "Ghost of Tsushima",
    "Final Fantasy",
    "Genshin Impact",
    "Honkai Star Rail",
    "Diablo 4",
    "World of Warcraft",
    "Hearthstone",
    "StarCraft",
    "Destiny 2",
    "Warframe",
    "Sea of Thieves",
    "Fall Guys",
    "Among Us",
    "Stardew Valley",
    "Terraria",
    "Hollow Knight",
    "Cuphead",
    "Hades game",
    "Palworld",
    "Helldivers 2",
    "Street Fighter",
    "Tekken 8",
    "Mortal Kombat",
    "Monster Hunter",
    "Resident Evil",
    "Silent Hill",
    "Metal Gear Solid",
    "Death Stranding",
    "Kingdom Hearts",
    "Persona game",
    "Dark Souls",
    "Bloodborne",
    "Sekiro",
    "Starfield",
    "No Man's Sky",
    "Fallout game",
    "The Elder Scrolls",
    "Skyrim",
    "Doom game",
    "Borderlands",
    "Dead by Daylight",
    "Warzone",
    "Splatoon",
    "Metroid",
    "Kirby game",
    "Donkey Kong",
    "Mario Kart",
    "Zelda Tears of the Kingdom",
    "Hogwarts Legacy",
    "Alan Wake 2",
    "Lies of P",
    "Sea of Stars",
    "Armored Core",
    "Like a Dragon",
    "Yakuza game",
    "Nier",
    "Bayonetta",
    "Devil May Cry",
    "Ni no Kuni",
    "Octopath Traveler",
    "Fire Emblem",
    "Xenoblade Chronicles",
    "Splatgame",
    "Fortnite Battle Royale",
    "Clash of Clans",
    "Clash Royale",
    "Brawl Stars",
    "Candy Crush",
    "Pokemon Go",
    "Mobile Legends",
    "Free Fire",
    "Honor of Kings",
    "EA FC Mobile",
    "Marvel Rivals",
    "Black Myth Wukong",
    "Concord game",
    "Astro Bot",
    "Silent Hill 2 remake",
    "Dragon Age",
    "Mass Effect",
    "Diablo Immortal",
    "Path of Exile",
    "Old School RuneScape",
    "Runescape",
    "Guild Wars 2",
    "Final Fantasy XIV",
    "Lost Ark",
    "New World game",
    "Escape from Tarkov",
    "Rust game",
    "DayZ",
    "ARK Survival",
    "Valheim",
    "Grounded game",
    "Sons of the Forest",
    "Lethal Company",
    "Content Warning",
    "Manor Lords",
    "Cities Skylines",
    "Football Manager",
    # Platforms / studios
    "PlayStation 5",
    "Xbox Series X",
    "Nintendo Switch",
    "Steam gaming",
    "Nintendo",
    "Xbox Game Pass",
    "Epic Games",
    "Riot Games",
    "Rockstar Games",
    "Ubisoft",
    "Electronic Arts",
    "Activision Blizzard",
    "Bethesda",
    "CD Projekt Red",
    "Naughty Dog",
    "FromSoftware",
    "Insomniac Games",
]


_MOVIES: list[str] = [
    # Marvel / DC
    "Avengers",
    "Deadpool",
    "Spider-Man movie",
    "X-Men",
    "Guardians of the Galaxy",
    "Thor movie",
    "Black Panther",
    "Captain America",
    "Fantastic Four",
    "Blade movie",
    "Batman movie",
    "Superman movie",
    "Joker movie",
    "Aquaman",
    "Wonder Woman",
    "The Flash movie",
    # Franchises
    "Star Wars",
    "Star Trek",
    "Dune movie",
    "Avatar movie",
    "Lord of the Rings",
    "The Hobbit",
    "Harry Potter",
    "Fantastic Beasts",
    "Jurassic World",
    "Indiana Jones",
    "Mission Impossible",
    "James Bond",
    "Fast and Furious",
    "John Wick",
    "The Matrix",
    "Transformers movie",
    "Pirates of the Caribbean",
    "The Hunger Games",
    "Ghostbusters",
    "Godzilla movie",
    "King Kong movie",
    "Alien movie",
    "Predator movie",
    "The Conjuring",
    "IT movie",
    "Halloween movie",
    "Scream movie",
    "A Quiet Place",
    "Mad Max",
    "Rocky movie",
    "Rambo",
    "Terminator movie",
    "Die Hard",
    "Kingsman",
    "The Purge",
    # Recent / notable
    "Oppenheimer",
    "Barbie movie",
    "Wicked movie",
    "Gladiator II",
    "Inside Out 2",
    "Moana 2",
    "Beetlejuice Beetlejuice",
    "Furiosa",
    "Nosferatu movie",
    "Deadpool and Wolverine",
    "Twisters",
    "Wonka",
    "Kung Fu Panda 4",
    "Bad Boys Ride or Die",
    "The Fall Guy",
    # Animated / studios
    "Frozen movie",
    "Toy Story",
    "Shrek",
    "Minions movie",
    "Despicable Me",
    "The Lion King",
    "Spider-Verse",
    "Pixar",
    "DreamWorks",
    "A24 films",
    "Studio Ghibli",
    "How to Train Your Dragon",
    # Directors
    "Christopher Nolan",
    "Quentin Tarantino",
    "Martin Scorsese",
    "Steven Spielberg",
    "Denis Villeneuve",
    "Greta Gerwig",
    # TV / streaming
    "Stranger Things",
    "House of the Dragon",
    "The Last of Us show",
    "The Bear show",
    "The Mandalorian",
    "Squid Game",
    "Wednesday show",
    "Bridgerton",
    "The Witcher show",
    "Rings of Power",
    "Severance show",
    "True Detective",
    "Yellowstone show",
    "Euphoria show",
    # Awards
    "Oscars",
    "Cannes Film Festival",
    "Golden Globes",
    "Box Office",
]


_TVSHOWS: list[str] = [
    "Game of Thrones",
    "House of the Dragon",
    "Stranger Things",
    "The Last of Us",
    "Breaking Bad",
    "Better Call Saul",
    "The Boys",
    "Wednesday show",
    "The Mandalorian",
    "The Witcher show",
    "Squid Game",
    "Bridgerton",
    "The Crown",
    "Succession",
    "Ted Lasso",
    "The Bear",
    "Yellowstone",
    "Euphoria",
    "Severance",
    "The White Lotus",
    "True Detective",
    "Fargo",
    "Peaky Blinders",
    "Money Heist",
    "Dark Netflix",
    "The Umbrella Academy",
    "Cobra Kai",
    "Ozark",
    "Narcos",
    "The Handmaid's Tale",
    "Westworld",
    "The Walking Dead",
    "Rick and Morty",
    "The Simpsons",
    "Family Guy",
    "South Park",
    "Friends show",
    "The Office",
    "Seinfeld",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "The Big Bang Theory",
    "Grey's Anatomy",
    "Sherlock",
    "Doctor Who",
    "Black Mirror",
    "The Queen's Gambit",
    "Emily in Paris",
    "Outer Banks",
    "Heartstopper",
    "You Netflix",
    "Sex Education",
    "The Sandman",
    "Rings of Power",
    "Loki show",
    "WandaVision",
    "Andor",
    "Ahsoka",
    "Fallout show",
    "Reacher",
    "Jack Ryan",
    "Slow Horses",
    "Only Murders in the Building",
    "Abbott Elementary",
    "Hacks",
    "Barry HBO",
    "Saturday Night Live",
    "Last Week Tonight",
    "RuPaul's Drag Race",
    "Love Island",
    "The Bachelor",
    "Survivor",
    "Big Brother",
    "MasterChef",
    "The Great British Bake Off",
    "Top Gear",
    "The Grand Tour",
    "Planet Earth",
    "Drive to Survive",
    "Beef Netflix",
    "Baby Reindeer",
    "3 Body Problem",
    "Shogun",
    "Ripley Netflix",
    "The Gentlemen",
    "One Piece Netflix",
    "Arcane",
    "Fallout series",
    "The Penguin show",
    "Agatha All Along",
    "Silo Apple",
    "Foundation Apple",
    "Ted Lasso Apple",
    "The Morning Show",
    "Yellowjackets",
    "The Diplomat",
    "Wednesday Netflix",
    "Cobra Kai Netflix",
    "Vikings",
    "The Last Kingdom",
    "Outlander",
    "Downton Abbey",
]

_ANIME: list[str] = [
    "Naruto",
    "One Piece anime",
    "Dragon Ball",
    "Attack on Titan",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Death Note",
    "Fullmetal Alchemist",
    "Bleach anime",
    "Hunter x Hunter",
    "Tokyo Ghoul",
    "Sword Art Online",
    "One Punch Man",
    "Chainsaw Man",
    "Spy x Family",
    "Mob Psycho 100",
    "Vinland Saga",
    "Black Clover",
    "Fairy Tail",
    "Fire Force",
    "Dr Stone",
    "The Promised Neverland",
    "Haikyuu",
    "Blue Lock",
    "Solo Leveling",
    "Frieren",
    "Oshi no Ko",
    "Cyberpunk Edgerunners",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Sailor Moon",
    "Pokemon anime",
    "Yu-Gi-Oh",
    "Digimon",
    "Inuyasha",
    "Gintama",
    "JoJo's Bizarre Adventure",
    "Steins Gate",
    "Code Geass",
    "Re Zero",
    "Konosuba",
    "Overlord anime",
    "That Time I Got Reincarnated as a Slime",
    "No Game No Life",
    "Your Name anime",
    "Weathering with You",
    "Suzume",
    "A Silent Voice",
    "Spirited Away",
    "Princess Mononoke",
    "My Neighbor Totoro",
    "Howl's Moving Castle",
    "Ghost in the Shell",
    "Akira anime",
    "Made in Abyss",
    "Violet Evergarden",
    "Your Lie in April",
    "Clannad",
    "Toradora",
    "Kaguya-sama Love is War",
    "Horimiya",
    "Dandadan",
    "Kaiju No 8",
    "Wind Breaker anime",
    "Sakamoto Days",
    "Bocchi the Rock",
    "Lycoris Recoil",
    "Mushoku Tensei",
    "The Eminence in Shadow",
    "Hell's Paradise",
    "Zom 100",
    "Undead Unluck",
    "Mashle",
    "Ranking of Kings",
    "Berserk anime",
    "Vagabond manga",
    "Monster anime",
    "Parasyte",
    "Erased anime",
    "Psycho-Pass",
    "Fate Stay Night",
    "Fate Zero",
    "Log Horizon",
    "Bunny Girl Senpai",
    "Grand Blue",
    "Golden Kamuy",
    "Vivy anime",
    "Tokyo Revengers",
    "Dragon Ball Daima",
    "Kingdom anime",
    "Blue Exorcist",
    "Seven Deadly Sins anime",
    "Rurouni Kenshin",
    "Trigun",
    "Gundam",
    "Evangelion",
    "Neon Genesis",
]

_BOOKS: list[str] = [
    # Authors
    "Stephen King",
    "George R.R. Martin",
    "Colleen Hoover",
    "Brandon Sanderson",
    "Sarah J Maas",
    "Rebecca Yarros",
    "James Patterson",
    "John Grisham",
    "Dan Brown author",
    "Agatha Christie",
    "Neil Gaiman",
    "Haruki Murakami",
    "Margaret Atwood",
    "Cormac McCarthy",
    "Taylor Jenkins Reid",
    "Emily Henry",
    "Ali Hazelwood",
    "Freida McFadden",
    "Rick Riordan",
    "Leigh Bardugo",
    "Cassandra Clare",
    "Suzanne Collins",
    "Delia Owens",
    "Bonnie Garmus",
    "R.F. Kuang",
    "Kristin Hannah",
    "Fredrik Backman",
    "Matt Haig",
    # Series / titles
    "Fourth Wing",
    "A Court of Thorns and Roses",
    "Iron Flame",
    "It Ends With Us",
    "The Seven Husbands of Evelyn Hugo",
    "Verity book",
    "A Song of Ice and Fire",
    "The Wheel of Time books",
    "Mistborn",
    "The Stormlight Archive",
    "Percy Jackson books",
    "The Hunger Games books",
    "The Silent Patient",
    "Where the Crawdads Sing",
    "The Midnight Library",
    "Project Hail Mary",
    "The Song of Achilles",
    "Circe book",
    "Normal People",
    "Babel R.F. Kuang",
    "Yellowface",
    "Tomorrow and Tomorrow and Tomorrow",
    "Lessons in Chemistry",
    "The Housemaid",
    "Happy Place",
    "Book Lovers",
    "The Love Hypothesis",
    "House of Earth and Blood",
    "Throne of Glass",
    "Red Rising",
    "The Way of Kings",
    "Dune book",
    "The Name of the Wind",
    "Six of Crows",
    "Shadow and Bone books",
    # Non-fiction / self-help
    "Atomic Habits",
    "Rich Dad Poor Dad",
    "The Psychology of Money",
    "Sapiens book",
    "The 48 Laws of Power",
    "Think and Grow Rich",
    "The 7 Habits of Highly Effective People",
    "The Subtle Art of Not Giving",
    "Man's Search for Meaning",
    "Deep Work",
    "Can't Hurt Me",
    "The Alchemist",
    "Outliers Gladwell",
    "Thinking Fast and Slow",
    "The Body Keeps the Score",
    # Industry
    "New York Times Bestsellers",
    "Booker Prize",
    "Goodreads Choice Awards",
    "BookTok",
    "Pulitzer Prize fiction",
]


# General "latest news" card per new column - the representative each column
# contributes to the default deck (referenced by id in endpoints.DEFAULT_DECK).
_GENERAL: list[Feed] = [
    ("new+music+releases", "music-new", "New Music", "Music", "music"),
    ("video+game+news", "game-new", "Gaming News", "Gaming", "gaming"),
    ("new+movies", "movie-new", "New Movies", "Movie", "movies"),
    ("new+tv+shows", "tv-new", "New TV Shows", "TV Show", "tv"),
    ("new+anime", "anime-new", "New Anime", "Anime", "anime"),
    ("new+books+bestsellers", "book-new", "New Books", "Books", "books"),
    ("new+gadgets+tech", "tech-new", "New Gadgets", "Tech", "gadgets"),
    ("new+cars+auto+news", "car-new", "Auto News", "Cars", "cars"),
    ("popular+podcasts", "podcast-new", "Podcasts", "Podcast", "podcasts"),
]

_PODCASTS: list[str] = [
    "The Joe Rogan Experience",
    "Call Her Daddy",
    "Crime Junkie",
    "The Daily podcast",
    "SmartLess",
    "This American Life",
    "Serial podcast",
    "Huberman Lab",
    "Lex Fridman Podcast",
    "The Diary of a CEO",
    "My Favorite Murder",
    "Armchair Expert",
    "Stuff You Should Know",
    "Pod Save America",
    "The Tim Ferriss Show",
    "Radiolab",
    "Freakonomics",
    "Planet Money",
    "How I Built This",
    "Hardcore History",
    "TED Talks Daily",
    "The Rest Is History",
    "The Rest Is Politics",
    "Rotten Mango",
    "Morbid",
    "2 Bears 1 Cave",
    "Bad Friends",
    "H3 Podcast",
    "Impaulsive",
    "Flagrant",
    "Distractible",
    "New Heights podcast",
    "Pardon My Take",
    "The Bill Simmons Podcast",
    "WTF with Marc Maron",
    "Conan O'Brien Needs a Friend",
    "On Purpose Jay Shetty",
    "The Mel Robbins Podcast",
    "Modern Wisdom",
    "Acquired podcast",
    "All-In Podcast",
    "Lenny's Podcast",
    "The Vergecast",
    "Waveform podcast",
    "Darknet Diaries",
    "99% Invisible",
    "Casefile",
    "Last Podcast on the Left",
    "You're Wrong About",
    "Behind the Bastards",
    "Office Ladies",
    "Shawn Ryan Show",
    "Andrew Schulz Flagrant",
    "Chapo Trap House",
    "The Joe Budden Podcast",
    "Anything Goes Emma Chamberlain",
    "Smartless podcast",
    "Dateline NBC podcast",
    "The MeidasTouch Podcast",
    "The Ben Shapiro Show",
    "The Megyn Kelly Show",
    "The Breakfast Club",
    "Club Shay Shay",
    "Million Dollaz Worth of Game",
    "The Pat McAfee Show",
    "No Jumper",
    "Theo Von This Past Weekend",
    "Bussin With The Boys",
    "The Ringer NBA Show",
    "Serial Killers podcast",
]

_TECH: list[str] = [
    # Apple
    "iPhone",
    "iPad",
    "MacBook",
    "Apple Watch",
    "AirPods",
    "Apple Vision Pro",
    "Mac Studio",
    "iMac",
    "Apple TV",
    "HomePod",
    "Apple Intelligence",
    "AirPods Pro",
    "MacBook Air",
    "MacBook Pro",
    # Samsung / Google / Microsoft / Sony
    "Samsung Galaxy S",
    "Galaxy Z Fold",
    "Galaxy Z Flip",
    "Galaxy Watch",
    "Galaxy Buds",
    "Google Pixel",
    "Pixel Watch",
    "Google Nest",
    "Microsoft Surface",
    "Windows 11",
    "Microsoft Copilot",
    "Sony Bravia",
    "Sony WH-1000XM5",
    "PlayStation VR",
    # Phone brands
    "OnePlus",
    "Xiaomi",
    "Oppo",
    "Vivo phone",
    "Nothing Phone",
    "Motorola",
    "Huawei",
    "Honor phone",
    "Realme",
    "Asus ROG Phone",
    # Computing
    "Asus laptop",
    "Acer",
    "Lenovo ThinkPad",
    "Dell XPS",
    "HP laptop",
    "Razer laptop",
    "MSI laptop",
    "Framework Laptop",
    "Chromebook",
    # Chips
    "Nvidia",
    "Nvidia RTX",
    "AMD Ryzen",
    "Intel",
    "Qualcomm Snapdragon",
    "Apple M4 chip",
    "Nvidia Blackwell",
    # Audio
    "Bose",
    "Sonos",
    "JBL",
    "Sennheiser",
    "Beats headphones",
    "Marshall speaker",
    # Wearables / smart home
    "Fitbit",
    "Garmin",
    "Oura Ring",
    "Whoop",
    "Meta Quest 3",
    "Ray-Ban Meta",
    "Amazon Echo",
    "Amazon Alexa",
    "Ring doorbell",
    "Philips Hue",
    "iRobot Roomba",
    "Nest Thermostat",
    "Google Home",
    "Eufy",
    # AI products
    "ChatGPT",
    "Claude AI",
    "Google Gemini",
    "Midjourney",
    "Perplexity AI",
    "Grok AI",
    "DALL-E",
    "Sora AI",
    "Stable Diffusion",
    "Runway AI",
    "ElevenLabs",
    "DeepSeek",
    "Copilot AI",
    "Llama AI",
    "Mistral AI",
    # Cameras / drones
    "GoPro",
    "DJI drone",
    "Canon camera",
    "Nikon camera",
    "Sony Alpha camera",
    "Fujifilm camera",
    "Leica camera",
    "Insta360",
    # Gaming hardware
    "Steam Deck",
    "ROG Ally",
    "Nintendo Switch 2",
    "Valve Index",
    # Misc gadgets
    "Dyson",
    "Anker",
    "Raspberry Pi",
    "Amazon Kindle",
    "reMarkable tablet",
    "Rabbit R1",
    "Humane AI Pin",
    "Boston Dynamics",
]

_CARS: list[str] = [
    # Mass brands
    "Toyota",
    "Honda",
    "Ford",
    "Chevrolet",
    "Volkswagen",
    "Nissan",
    "Hyundai",
    "Kia",
    "Mazda",
    "Subaru",
    "Suzuki",
    "Mitsubishi",
    "Peugeot",
    "Renault",
    "Citroen",
    "Fiat",
    "Skoda",
    "SEAT",
    "Opel",
    "Vauxhall",
    "Dacia",
    # Premium / luxury
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Porsche",
    "Lexus",
    "Acura",
    "Infiniti",
    "Genesis cars",
    "Cadillac",
    "Volvo cars",
    "Jaguar",
    "Land Rover",
    "Range Rover",
    "Mini Cooper",
    "Alfa Romeo",
    "Maserati",
    # Supercars
    "Ferrari",
    "Lamborghini",
    "McLaren cars",
    "Bugatti",
    "Rolls-Royce",
    "Bentley",
    "Aston Martin",
    "Koenigsegg",
    "Pagani",
    # American
    "Jeep",
    "Ram trucks",
    "Dodge",
    "Chrysler",
    "GMC",
    "Buick",
    "Lincoln cars",
    # EV makers
    "Tesla",
    "Rivian",
    "Lucid Motors",
    "Polestar",
    "Fisker",
    "VinFast",
    "BYD cars",
    "Nio",
    "Xpeng",
    "Li Auto",
    "Zeekr",
    # Chinese / Indian
    "Geely",
    "Chery",
    "Great Wall Motors",
    "MG cars",
    "Tata Motors",
    "Mahindra",
    # Popular models
    "Ford F-150",
    "Ford Mustang",
    "Ford Bronco",
    "Toyota Corolla",
    "Toyota Camry",
    "Toyota RAV4",
    "Toyota Hilux",
    "Toyota Supra",
    "Honda Civic",
    "Honda Accord",
    "Honda CR-V",
    "Chevrolet Corvette",
    "Chevrolet Silverado",
    "Jeep Wrangler",
    "Porsche 911",
    "BMW M3",
    "Mercedes G-Wagon",
    "Nissan GT-R",
    "Mazda MX-5",
    "Dodge Charger",
    "Tesla Model 3",
    "Tesla Model Y",
    "Tesla Model S",
    "Tesla Cybertruck",
    "Hyundai Ioniq 5",
    "Kia EV6",
    "Rivian R1T",
    "BMW i4",
    "Ford Ranger",
    "VW Golf",
    "Range Rover Sport",
    "Audi RS6",
    # Culture
    "Classic cars",
    "Electric vehicles",
    "Self-driving cars",
    "Car reviews",
]


def _build() -> list[Feed]:
    feeds: list[Feed] = list(_GENERAL)
    seen: set[str] = {sid for _q_, sid, _n, _k, _c in _GENERAL}
    for name in _ARTISTS:
        sid = f"music-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(f"{name} music"), sid, name, "Music", "music"))
    for name in _GAMES:
        sid = f"game-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(f"{name} game"), sid, name, "Gaming", "gaming"))
    for name in _MOVIES:
        sid = f"movie-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "Movie", "movies"))
    for name in _TVSHOWS:
        sid = f"tv-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "TV Show", "tv"))
    for name in _ANIME:
        sid = f"anime-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "Anime", "anime"))
    for name in _BOOKS:
        sid = f"book-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(f"{name} book"), sid, name, "Books", "books"))
    for name in _TECH:
        sid = f"tech-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "Tech", "gadgets"))
    for name in _CARS:
        sid = f"car-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "Cars", "cars"))
    for name in _PODCASTS:
        sid = f"podcast-{_slug(name)}"
        if sid in seen:
            continue
        seen.add(sid)
        feeds.append((_q(name), sid, name, "Podcast", "podcasts"))
    return feeds


MUSIC_GAMING_FEEDS: list[Feed] = _build()
