"""Science, academia and coding feeds - every field gets its own card, as
Google News search feeds (mathematics, physics, chemistry, biology, medicine,
engineering, coding, …) plus university campus feeds.

Each entry becomes a feed (getters in ``sources/science.py``, ``SOURCES`` rows
in ``metadata.py``) under a topic column, carrying a per-group twemoji logo so
every card ships with an icon. Plain data only, so both modules can import it
without a circular dependency.
"""

from __future__ import annotations

import re

# (google-news-query, source_id, card_name, kicker, column, logo_url)
ScienceFeed = tuple[str, str, str, str, str, str]

_TWEMOJI = "https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/72x72"


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def _q(text: str) -> str:
    return re.sub(r"\s+", "+", text.strip())


# (column, kicker, glyph, query_suffix, [topic names]). The query is
# "topic+suffix"; the id is "sci-{slug(topic)}"; the card title is the topic.
_GROUPS: list[tuple[str, str, str, str, list[str]]] = [
    (
        "science",
        "Mathematics",
        "1f9ee",
        "mathematics",
        [
            "Algebra",
            "Geometry",
            "Calculus",
            "Number Theory",
            "Topology",
            "Graph Theory",
            "Game Theory",
            "Probability Theory",
            "Statistics",
            "Linear Algebra",
            "Differential Equations",
            "Mathematical Analysis",
            "Combinatorics",
            "Set Theory",
            "Logic",
            "Category Theory",
            "Group Theory",
            "Knot Theory",
            "Chaos Theory",
            "Fractals",
            "Prime Numbers",
            "Cryptography Math",
            "Mathematical Modeling",
            "Numerical Analysis",
            "Optimization",
            "Applied Mathematics",
            "Pure Mathematics",
            "Mathematical Physics",
            "Riemann Hypothesis",
            "Millennium Prize Problems",
            "Fields Medal",
            "Math Olympiad",
            "Math Education",
            "Recreational Mathematics",
            "Mathematical Proofs",
            "Algebraic Geometry",
            "Differential Geometry",
            "Stochastic Processes",
            "Fourier Analysis",
            "Bayesian Statistics",
            "Real Analysis",
            "Complex Analysis",
            "Functional Analysis",
            "Measure Theory",
            "Representation Theory",
            "Model Theory",
            "Proof Theory",
            "Ergodic Theory",
            "Dynamical Systems",
            "Information Theory",
            "Coding Theory",
            "Queueing Theory",
            "Actuarial Science",
            "Econometrics",
            "Biostatistics",
            "Operations Research",
            "Tensor Calculus",
        ],
    ),
    (
        "science",
        "Physics",
        "269b",
        "physics",
        [
            "Quantum Mechanics",
            "Quantum Entanglement",
            "Quantum Field Theory",
            "Particle Physics",
            "Higgs Boson",
            "String Theory",
            "General Relativity",
            "Special Relativity",
            "Thermodynamics",
            "Electromagnetism",
            "Optics",
            "Photonics",
            "Nuclear Physics",
            "Nuclear Fusion",
            "Plasma Physics",
            "Condensed Matter",
            "Superconductivity",
            "Fluid Dynamics",
            "Acoustics",
            "Astrophysics",
            "Cosmology",
            "Dark Matter",
            "Dark Energy",
            "Gravitational Waves",
            "Neutrinos",
            "Antimatter",
            "Quantum Gravity",
            "Standard Model",
            "Large Hadron Collider",
            "Particle Accelerators",
            "Atomic Physics",
            "Molecular Physics",
            "Biophysics",
            "Geophysics",
            "Nobel Prize Physics",
            "Physics Education",
            "Theoretical Physics",
            "Experimental Physics",
            "Laser Physics",
            "Semiconductor Physics",
            "Quantum Sensors",
            "Quantum Networks",
            "Attosecond Physics",
            "Metrology",
            "Cold Atoms",
            "Bose Einstein Condensate",
            "Topological Materials",
            "Muons",
            "Quarks",
            "Tokamak Fusion",
        ],
    ),
    (
        "science",
        "Chemistry",
        "1f9ea",
        "chemistry",
        [
            "Organic Chemistry",
            "Inorganic Chemistry",
            "Physical Chemistry",
            "Analytical Chemistry",
            "Biochemistry",
            "Electrochemistry",
            "Photochemistry",
            "Polymer Chemistry",
            "Medicinal Chemistry",
            "Computational Chemistry",
            "Green Chemistry",
            "Catalysis",
            "Chemical Synthesis",
            "Chemical Bonds",
            "Periodic Table",
            "Chemical Elements",
            "Molecules",
            "Crystallography",
            "Spectroscopy",
            "Chromatography",
            "Chemical Engineering",
            "Petrochemicals",
            "Agrochemicals",
            "Food Chemistry",
            "Atmospheric Chemistry",
            "Nuclear Chemistry",
            "Supramolecular Chemistry",
            "Nobel Prize Chemistry",
            "Chemistry Education",
            "Toxicology",
        ],
    ),
    (
        "science",
        "Biology",
        "1f9ec",
        "biology",
        [
            "Molecular Biology",
            "Cell Biology",
            "Microbiology",
            "Virology",
            "Bacteriology",
            "Mycology",
            "Botany",
            "Zoology",
            "Entomology",
            "Ornithology",
            "Marine Biology",
            "Ecology",
            "Evolution",
            "Evolutionary Biology",
            "Genomics",
            "Gene Editing",
            "CRISPR",
            "Synthetic Biology",
            "Structural Biology",
            "Developmental Biology",
            "Immunology",
            "Epigenetics",
            "Bioinformatics",
            "Biotechnology",
            "Stem Cells",
            "Cloning",
            "Proteins",
            "Enzymes",
            "Photosynthesis",
            "Biodiversity",
            "Conservation Biology",
            "Ethology",
            "Herpetology",
            "Ichthyology",
            "Parasitology",
            "Astrobiology",
            "Microbiome",
            "Longevity Research",
            "Aging Research",
            "Biology Education",
            "Molecular Genetics",
            "Population Genetics",
            "Phylogenetics",
            "Paleogenomics",
            "Protein Folding",
            "AlphaFold",
            "Organoids",
            "Lab Grown Meat",
            "Biohacking",
            "Bioluminescence",
            "Extremophiles",
            "Plant Science",
            "Agricultural Science",
            "Crop Science",
            "Pollinators",
            "Bees Research",
            "Invasive Species",
            "Rewilding",
            "Animal Cognition",
            "Whale Research",
            "Shark Research",
            "Primatology",
            "Fungal Networks",
            "Soil Microbes",
            "Zoonotic Diseases",
        ],
    ),
    (
        "science",
        "Medicine",
        "1fa7a",
        "",
        [
            "Medical Research",
            "Clinical Trials",
            "Drug Discovery",
            "Vaccines",
            "Oncology",
            "Cardiology",
            "Neurology",
            "Pediatrics",
            "Geriatrics",
            "Radiology",
            "Surgery Innovation",
            "Anesthesiology",
            "Dermatology",
            "Ophthalmology",
            "Orthopedics",
            "Immunotherapy",
            "Gene Therapy",
            "Precision Medicine",
            "Telemedicine",
            "Medical Devices",
            "Medical Imaging",
            "Epidemiology",
            "Public Health Research",
            "Antibiotics Resistance",
            "Rare Diseases",
            "Organ Transplants",
            "Prosthetics",
            "Regenerative Medicine",
            "Pharmacology",
            "Pathology",
            "Endocrinology",
            "Gastroenterology",
            "Hematology",
            "Nephrology",
            "Pulmonology",
            "Rheumatology",
            "Urology",
            "Psychiatry Research",
            "Sports Medicine",
            "Emergency Medicine",
            "Nursing Research",
            "Dentistry Research",
            "Veterinary Medicine",
            "Nutrition Science",
            "Obesity Research",
            "Diabetes Research",
            "Cancer Research",
            "Alzheimers Research",
            "Parkinsons Research",
            "Heart Disease Research",
            "Stroke Research",
            "HIV Research",
            "Malaria Research",
            "Tuberculosis Research",
            "Pandemic Preparedness",
            "Womens Health Research",
            "Mens Health Research",
            "Mental Health Research",
            "Pain Research",
            "Sleep Research",
            "Asthma Research",
            "Arthritis Research",
            "Epilepsy Research",
            "Migraine Research",
            "Autism Research",
            "ADHD Research",
            "Depression Research",
            "Anxiety Research",
            "Schizophrenia Research",
            "Bipolar Research",
            "Multiple Sclerosis Research",
            "ALS Research",
            "Cystic Fibrosis Research",
            "Sickle Cell Research",
            "Leukemia Research",
            "Lymphoma Research",
            "Melanoma Research",
            "Breast Cancer Research",
            "Lung Cancer Research",
            "Prostate Cancer Research",
            "Colon Cancer Research",
            "Pancreatic Cancer Research",
            "Brain Tumor Research",
            "Osteoporosis Research",
            "Hepatitis Research",
            "Kidney Disease Research",
            "Liver Disease Research",
            "Allergy Research",
            "Autoimmune Research",
            "Chronic Fatigue Research",
            "Fibromyalgia Research",
            "Long Covid Research",
            "Dementia Research",
            "Huntingtons Research",
            "Muscular Dystrophy Research",
            "Down Syndrome Research",
            "Fertility Research",
            "IVF Research",
            "Pregnancy Research",
            "Menopause Research",
            "Weight Loss Drugs",
            "GLP-1 Drugs",
            "Antidepressants Research",
            "Psychedelic Medicine",
            "Medical Cannabis Research",
            "Wearable Health Tech",
            "Health AI Diagnostics",
            "Robotic Surgery",
            "Blood Tests Innovation",
            "Biomarkers",
            "Microbiome Medicine",
            "Anti Aging Medicine",
            "Cryonics",
            "Bionic Implants",
            "Hearing Loss Research",
            "Vision Loss Research",
            "Vaccine Development",
            "Drug Pricing Research",
            "Hospital Innovation",
        ],
    ),
    (
        "science",
        "Mind & Brain",
        "1f9e0",
        "",
        [
            "Cognitive Science",
            "Cognitive Psychology",
            "Behavioral Science",
            "Developmental Psychology",
            "Social Psychology",
            "Clinical Psychology",
            "Neuroimaging",
            "Brain Computer Interface",
            "Neuroplasticity",
            "Memory Research",
            "Consciousness Research",
            "Decision Science",
            "Neurodegeneration",
            "Neurotechnology",
            "Child Development",
            "Educational Psychology",
            "Positive Psychology",
            "Psycholinguistics",
            "Neuroeconomics",
            "Addiction Research",
        ],
    ),
    (
        "science",
        "Earth & Climate",
        "1f30d",
        "",
        [
            "Climate Science",
            "Climate Change Research",
            "Meteorology",
            "Oceanography",
            "Geology",
            "Seismology",
            "Volcanology",
            "Glaciology",
            "Hydrology",
            "Paleoclimatology",
            "Carbon Capture",
            "Sea Level Rise",
            "Coral Reefs",
            "Rainforests",
            "Polar Research",
            "Arctic Research",
            "Antarctica Research",
            "Earthquakes Science",
            "Hurricanes Science",
            "Wildfires Science",
            "Drought Research",
            "Air Quality Research",
            "Water Resources",
            "Soil Science",
            "Geochemistry",
            "Mineralogy",
            "Plate Tectonics",
            "Atmospheric Science",
            "Environmental Science",
            "Renewable Energy Research",
            "Solar Energy Research",
            "Wind Energy Research",
            "Geothermal Energy",
            "Hydrogen Energy",
            "Battery Research",
            "Nuclear Energy Research",
            "Climate Policy Science",
            "Biodiversity Loss",
            "Deforestation Research",
            "Ocean Acidification",
        ],
    ),
    (
        "science",
        "Astronomy",
        "1f52d",
        "",
        [
            "Astronomy",
            "Exoplanets",
            "Black Holes",
            "Neutron Stars",
            "Supernovae",
            "Galaxies",
            "Milky Way",
            "Solar System",
            "Asteroids",
            "Comets",
            "Meteor Showers",
            "Moon Science",
            "Mars Science",
            "Venus Science",
            "Jupiter Science",
            "Saturn Science",
            "Pluto",
            "Kuiper Belt",
            "Solar Flares",
            "Space Weather",
            "Radio Astronomy",
            "Telescopes",
            "Observatories",
            "SETI",
            "Astrochemistry",
            "Planetary Science",
            "Space Debris",
            "Eclipses",
            "Auroras Science",
            "Star Formation",
        ],
    ),
    (
        "science",
        "Space Missions",
        "1f6f0",
        "",
        [
            "James Webb Telescope",
            "Hubble Telescope",
            "Artemis Program",
            "International Space Station",
            "SpaceX Starship",
            "Falcon 9",
            "Blue Origin",
            "Rocket Lab",
            "NASA Missions",
            "ESA Missions",
            "Mars Rover",
            "Perseverance Rover",
            "Curiosity Rover",
            "Europa Clipper",
            "Voyager Probes",
            "New Horizons",
            "Parker Solar Probe",
            "Lunar Gateway",
            "Moon Landing",
            "Mars Sample Return",
            "Space Tourism",
            "Satellite Launches",
            "Starlink",
            "Space Race",
            "China Space Program",
            "India Space Program",
            "Japan Space Program",
            "Rocket Launches",
            "Spacewalks",
            "Astronaut Training",
            "Space Mining",
            "Mars Colonization",
            "Space Habitats",
            "Rocket Engines",
            "Reusable Rockets",
            "Small Satellites",
            "Earth Observation",
            "GPS Technology",
            "Space Law",
            "Commercial Spaceflight",
        ],
    ),
    (
        "science",
        "Engineering",
        "1f527",
        "engineering",
        [
            "Mechanical Engineering",
            "Electrical Engineering",
            "Civil Engineering",
            "Aerospace Engineering",
            "Biomedical Engineering",
            "Structural Engineering",
            "Robotics Engineering",
            "Automation",
            "3D Printing",
            "Additive Manufacturing",
            "CNC Machining",
            "Microelectronics",
            "Semiconductors",
            "Chip Manufacturing",
            "Photolithography",
            "MEMS",
            "Control Systems",
            "Signal Processing",
            "Power Grid",
            "Energy Storage",
            "Electric Motors",
            "Turbines",
            "Bridges Engineering",
            "Tunnels Engineering",
            "Skyscrapers Engineering",
            "Earthquake Engineering",
            "Acoustic Engineering",
            "Automotive Engineering",
            "Marine Engineering",
            "Mining Engineering",
            "Petroleum Engineering",
            "Nuclear Engineering",
            "Environmental Engineering",
            "Industrial Engineering",
            "Systems Engineering",
            "Nanotechnology",
            "Drones Engineering",
            "Autonomous Vehicles",
            "Hyperloop",
            "High Speed Rail",
        ],
    ),
    (
        "tech",
        "Computer Science",
        "1f4bb",
        "",
        [
            "Algorithms",
            "Data Structures",
            "Computational Complexity",
            "Distributed Systems",
            "Operating Systems",
            "Compilers",
            "Databases Research",
            "Computer Networks",
            "Computer Architecture",
            "Parallel Computing",
            "Cloud Computing",
            "Edge Computing",
            "Quantum Computing",
            "Quantum Algorithms",
            "Cryptography",
            "Formal Verification",
            "Programming Language Theory",
            "Type Theory",
            "Human Computer Interaction",
            "Computer Graphics",
            "Computer Vision",
            "Natural Language Processing",
            "Information Retrieval",
            "Recommender Systems",
            "Software Engineering Research",
            "Theoretical Computer Science",
            "Turing Award",
            "ACM Research",
            "Computability",
            "Automata Theory",
        ],
    ),
    (
        "tech",
        "Coding",
        "2328",
        "programming",
        [
            "Python",
            "JavaScript",
            "TypeScript",
            "Rust",
            "Go Language",
            "Java",
            "Kotlin",
            "Swift",
            "C Language",
            "C Plus Plus",
            "C Sharp",
            "Ruby",
            "PHP",
            "Scala",
            "Haskell",
            "Elixir",
            "Erlang",
            "Clojure",
            "Julia Language",
            "R Language",
            "Dart",
            "Zig Language",
            "Lua",
            "Perl",
            "Assembly Language",
            "COBOL",
            "Fortran",
            "SQL",
            "WebAssembly",
            "Solidity",
            "OCaml",
            "F Sharp",
            "Groovy",
            "MATLAB",
            "Objective C",
            "Visual Basic",
            "Delphi",
            "Prolog",
            "Lisp",
            "Scheme",
        ],
    ),
    (
        "tech",
        "Dev Life",
        "1f9d1-200d-1f4bb",
        "",
        [
            "Vibe Coding",
            "AI Coding Assistants",
            "Pair Programming",
            "Code Review",
            "Open Source Software",
            "Software Testing",
            "Test Driven Development",
            "Continuous Integration",
            "DevOps",
            "Site Reliability Engineering",
            "Platform Engineering",
            "Microservices",
            "Serverless Computing",
            "Kubernetes",
            "Docker Containers",
            "Git Version Control",
            "GitHub Copilot",
            "Frontend Development",
            "Backend Development",
            "Full Stack Development",
            "Mobile App Development",
            "Web Development",
            "Game Development",
            "React Framework",
            "Vue Framework",
            "Angular Framework",
            "Nextjs",
            "Svelte",
            "Nodejs",
            "Django Framework",
            "Ruby on Rails",
            "Spring Framework",
            "Flutter",
            "React Native",
            "GraphQL",
            "REST API Design",
            "Clean Code",
            "Refactoring",
            "Technical Debt",
            "Programming Tutorials",
            "Coding Bootcamps",
            "Developer Productivity",
            "Remote Software Jobs",
            "Freelance Programming",
            "Hackathons",
            "Competitive Programming",
            "Low Code Development",
            "No Code Tools",
            "API Development",
            "Software Architecture",
            "Laravel",
            "ASP.NET",
            "Express Framework",
            "FastAPI",
            "Flask Framework",
            "Terraform",
            "Ansible",
            "Jenkins CI",
            "GitLab",
            "Bitbucket",
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis Database",
            "SQLite",
            "Elasticsearch",
            "Apache Kafka",
            "Apache Spark",
            "RabbitMQ",
            "Nginx",
            "Linux Kernel",
            "Ubuntu Linux",
            "Debian Linux",
            "Arch Linux",
            "Fedora Linux",
            "FreeBSD",
            "Vim Editor",
            "Neovim",
            "Emacs",
            "VS Code Editor",
            "JetBrains IDE",
            "Cursor AI Editor",
            "Tailwind CSS",
            "Bootstrap CSS",
            "Webpack",
            "Vite",
            "Bun Runtime",
            "Deno Runtime",
            "Electron Apps",
            "Tauri",
            "Unity Engine",
            "Unreal Engine",
            "Godot Engine",
            "Blender 3D",
            "AWS Cloud",
            "Azure Cloud",
            "Google Cloud Platform",
            "Cloudflare",
            "Vercel",
            "Netlify",
            "Supabase",
            "Firebase",
            "Raspberry Pi",
            "Arduino",
            "Home Assistant",
            "Self Hosting",
        ],
    ),
    (
        "tech",
        "AI & Data",
        "1f916",
        "",
        [
            "Machine Learning Research",
            "Deep Learning",
            "Neural Networks",
            "Large Language Models",
            "Generative AI",
            "AI Agents",
            "Reinforcement Learning",
            "Transformers AI",
            "Diffusion Models",
            "AI Alignment",
            "AI Safety",
            "AI Ethics",
            "AI Regulation",
            "AGI Research",
            "Prompt Engineering",
            "Fine Tuning AI",
            "RAG Retrieval Augmented",
            "Multimodal AI",
            "Speech Recognition",
            "Text to Speech",
            "Image Generation AI",
            "Video Generation AI",
            "AI Chips",
            "GPU Computing",
            "TensorFlow",
            "PyTorch",
            "Data Science",
            "Data Engineering",
            "Big Data",
            "Data Visualization",
            "Data Mining",
            "Predictive Analytics",
            "MLOps",
            "Federated Learning",
            "Explainable AI",
            "Computer Vision AI",
            "AI in Healthcare",
            "AI in Education",
            "AI in Finance",
            "AI Startups",
            "AI Benchmarks",
            "AI Hardware",
            "Synthetic Data",
            "AI Music Generation",
            "Open Source AI",
            "AI Datacenters",
            "AI Energy Use",
            "Robot Learning",
            "Humanoid Robots",
            "Swarm Robotics",
            "Autonomous Drones AI",
            "Chatbots",
            "AI Search Engines",
            "Edge AI",
            "TinyML",
        ],
    ),
    (
        "tech",
        "Cybersecurity",
        "1f512",
        "",
        [
            "Cybersecurity Research",
            "Ransomware",
            "Data Breaches",
            "Zero Day Vulnerabilities",
            "Penetration Testing",
            "Ethical Hacking",
            "Malware Analysis",
            "Phishing Attacks",
            "Network Security",
            "Application Security",
            "Cloud Security",
            "Encryption",
            "Post Quantum Cryptography",
            "Identity Theft Protection",
            "Bug Bounty",
            "Security Operations",
            "Threat Intelligence",
            "Social Engineering Security",
            "IoT Security",
            "Mobile Security",
            "Privacy Technology",
            "VPN Technology",
            "Cyber Warfare",
            "Infosec Community",
            "CISO Leadership",
        ],
    ),
    (
        "science",
        "Progress",
        "1f4c8",
        "",
        [
            "Scientific Progress",
            "Medical Progress",
            "Space Discoveries",
            "Physics Progress",
            "AI Progress",
            "Cancer Research Progress",
            "Quantum Progress",
            "Energy Progress",
            "Genetics Progress",
            "Robotics Progress",
            "Archaeology Discoveries",
            "New Species Discovered",
            "Astronomy Discoveries",
            "Materials Progress",
            "Longevity Progress",
            "Neuroscience Progress",
            "Mathematics Progress",
            "Vaccine Progress",
            "Deep Sea Discoveries",
            "Fossil Discoveries",
        ],
    ),
    (
        "science",
        "Energy",
        "26a1",
        "",
        [
            "Fusion Energy",
            "Fusion Progress",
            "ITER",
            "Commonwealth Fusion",
            "Helion Energy",
            "Stellarator",
            "Inertial Confinement Fusion",
            "National Ignition Facility",
            "Laser Fusion",
            "Fusion Startups",
            "Green Hydrogen",
            "Hydrogen Fuel Cells",
            "Hydrogen Cars",
            "Hydrogen Aviation",
            "Hydrogen Trains",
            "Electrolyzers",
            "Ammonia Fuel",
            "E-Fuels",
            "Sustainable Aviation Fuel",
            "Biofuels",
            "Small Modular Reactors",
            "Thorium Reactors",
            "Nuclear Microreactors",
            "Enhanced Geothermal",
            "Tidal Energy",
            "Wave Energy",
            "Floating Solar",
            "Space Based Solar Power",
            "Solid State Batteries",
            "Sodium Ion Batteries",
            "Flow Batteries",
            "Supercapacitors",
            "Grid Scale Storage",
            "Smart Grid Technology",
            "Energy Transition",
            "Vehicle to Grid",
            "Heat Pumps",
            "Airborne Wind Energy",
            "Pylon Wind Turbines",
            "Offshore Wind Farms",
            "Vertical Wind Turbines",
        ],
    ),
    (
        "science",
        "Materials",
        "1f9f2",
        "",
        [
            "Materials Science",
            "Graphene",
            "Carbon Nanotubes",
            "Metamaterials",
            "Biomaterials",
            "Smart Materials",
            "Composite Materials",
            "Ceramics Science",
            "Alloys",
            "Polymers Science",
            "Rare Earth Elements",
            "Lithium Mining",
            "Cobalt Mining",
            "Copper Industry",
            "Steel Industry",
            "Aluminum Industry",
            "Titanium",
            "Silicon Materials",
            "Perovskite Solar",
            "Quantum Dots",
            "Aerogels",
            "Superalloys",
            "Self Healing Materials",
            "Recycling Technology",
            "Critical Minerals",
            "Plastic Magnets",
            "Permanent Magnets",
            "Bioplastics",
        ],
    ),
    (
        "science",
        "Social Science",
        "1f465",
        "",
        [
            "Sociology",
            "Anthropology",
            "Political Science",
            "Economics Research",
            "Behavioral Economics",
            "Demography",
            "Urban Studies",
            "Criminology",
            "Linguistics",
            "Education Research",
            "Gender Studies",
            "Media Studies",
            "International Relations Research",
            "Development Economics",
            "Labor Economics",
            "Public Policy Research",
            "Survey Research",
            "Social Mobility",
            "Inequality Research",
            "Migration Research",
            "Happiness Research",
            "Religion Studies",
            "Ethics Research",
            "Philosophy of Science",
            "Science Communication",
        ],
    ),
    (
        "science",
        "Paleontology",
        "1f996",
        "",
        [
            "Paleontology",
            "Dinosaur Discoveries",
            "Fossils",
            "Human Evolution",
            "Neanderthals",
            "Ancient DNA",
            "Extinct Species",
            "Mass Extinctions",
            "Prehistoric Animals",
            "Ice Age",
            "Early Humans",
            "Hominins",
            "Paleobotany",
            "Amber Fossils",
            "Trilobites",
        ],
    ),
    (
        "science",
        "Research World",
        "1f52c",
        "",
        [
            "CERN",
            "NASA JPL",
            "Max Planck Society",
            "National Institutes of Health",
            "National Science Foundation",
            "Royal Society",
            "CSIRO",
            "RIKEN",
            "Chinese Academy of Sciences",
            "Fermilab",
            "Brookhaven Lab",
            "Los Alamos Lab",
            "Lawrence Berkeley Lab",
            "Oak Ridge Lab",
            "Argonne Lab",
            "Sandia Labs",
            "Broad Institute",
            "Salk Institute",
            "Scripps Research",
            "Cold Spring Harbor",
            "Wellcome Trust",
            "Howard Hughes Medical",
            "Pasteur Institute",
            "Karolinska Institute",
            "Nobel Prize",
            "Breakthrough Prize",
            "Scientific Publishing",
            "Peer Review",
            "Research Funding",
            "Research Integrity",
            "Preprints Research",
            "Open Science",
            "Citizen Science",
            "Science Policy",
            "Lab Life",
        ],
    ),
    (
        "science",
        "Academic Life",
        "1f393",
        "",
        [
            "Higher Education",
            "University Rankings",
            "College Admissions",
            "Graduate School",
            "PhD Students",
            "Postdoc Research",
            "Tenure Track",
            "Academic Jobs",
            "Student Loans News",
            "Scholarships News",
            "Study Abroad",
            "International Students",
            "Campus Life",
            "Student Housing",
            "Tuition Fees",
            "Academic Publishing",
            "University Research",
            "College Sports Academics",
            "Online Degrees",
            "MOOCs",
            "EdTech",
            "Exam Season",
            "Academic Conferences",
            "University Funding",
            "Student Mental Health",
        ],
    ),
]

# University campus feeds: the query is the quoted university name; the id is
# "uni-{slug(name)}"; the card title is the name. Populated in
# ``UNIVERSITIES`` below.
_UNI_GLYPH = f"{_TWEMOJI}/1f3db.png"
UNIVERSITIES: list[str] = [
    "Harvard University",
    "MIT",
    "Stanford University",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Chicago",
    "Caltech",
    "University of Pennsylvania",
    "Cornell University",
    "Johns Hopkins University",
    "Duke University",
    "Northwestern University",
    "Brown University",
    "Dartmouth College",
    "UC Berkeley",
    "UCLA",
    "UC San Diego",
    "UC Davis",
    "UC Irvine",
    "University of Michigan",
    "University of Washington",
    "University of Texas Austin",
    "Georgia Tech",
    "Carnegie Mellon University",
    "New York University",
    "University of Wisconsin Madison",
    "University of Illinois Urbana",
    "University of Minnesota",
    "Ohio State University",
    "Penn State University",
    "University of Florida",
    "University of North Carolina",
    "University of Virginia",
    "Vanderbilt University",
    "Rice University",
    "Notre Dame University",
    "Georgetown University",
    "Boston University",
    "University of Southern California",
    "Purdue University",
    "University of Maryland",
    "University of Colorado Boulder",
    "Arizona State University",
    "University of Arizona",
    "Michigan State University",
    "Texas A&M University",
    "University of Pittsburgh",
    "Emory University",
    "Washington University St Louis",
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "UCL",
    "London School of Economics",
    "Kings College London",
    "University of Edinburgh",
    "University of Manchester",
    "University of Bristol",
    "University of Warwick",
    "University of Glasgow",
    "Durham University",
    "University of St Andrews",
    "University of Birmingham",
    "University of Leeds",
    "University of Sheffield",
    "University of Nottingham",
    "Queen Mary University London",
    "Trinity College Dublin",
    "University College Dublin",
    "University College Cork",
    "University of Galway",
    "Dublin City University",
    "University of Limerick",
    "ETH Zurich",
    "EPFL",
    "University of Zurich",
    "University of Geneva",
    "Technical University Munich",
    "LMU Munich",
    "Heidelberg University",
    "Humboldt University Berlin",
    "Free University Berlin",
    "RWTH Aachen",
    "University of Freiburg",
    "University of Tubingen",
    "Sorbonne University",
    "Sciences Po",
    "Ecole Polytechnique",
    "PSL University",
    "University of Amsterdam",
    "Delft University of Technology",
    "Utrecht University",
    "Leiden University",
    "Erasmus University Rotterdam",
    "KU Leuven",
    "Ghent University",
    "University of Copenhagen",
    "Technical University of Denmark",
    "Aarhus University",
    "Karolinska Institutet",
    "KTH Royal Institute",
    "Lund University",
    "Uppsala University",
    "University of Oslo",
    "University of Helsinki",
    "Aalto University",
    "University of Vienna",
    "University of Bologna",
    "Sapienza University Rome",
    "Politecnico di Milano",
    "University of Padua",
    "Complutense University Madrid",
    "University of Barcelona",
    "Autonomous University of Madrid",
    "IE University",
    "University of Lisbon",
    "University of Porto",
    "University of Warsaw",
    "Jagiellonian University",
    "Charles University Prague",
    "Central European University",
    "University of Athens",
    "Bocconi University",
    "University of Toronto",
    "McGill University",
    "University of British Columbia",
    "University of Waterloo",
    "McMaster University",
    "University of Alberta",
    "University of Montreal",
    "Australian National University",
    "University of Melbourne",
    "University of Sydney",
    "UNSW Sydney",
    "University of Queensland",
    "Monash University",
    "University of Auckland",
    "University of Tokyo",
    "Kyoto University",
    "Osaka University",
    "Tohoku University",
    "Tokyo Institute of Technology",
    "Waseda University",
    "Keio University",
    "Tsinghua University",
    "Peking University",
    "Fudan University",
    "Shanghai Jiao Tong University",
    "Zhejiang University",
    "University of Hong Kong",
    "HKUST",
    "Chinese University of Hong Kong",
    "National Taiwan University",
    "Seoul National University",
    "KAIST",
    "Yonsei University",
    "Korea University",
    "National University of Singapore",
    "Nanyang Technological University",
    "IIT Bombay",
    "IIT Delhi",
    "IIT Madras",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IISc Bangalore",
    "Delhi University",
    "Jawaharlal Nehru University",
    "University of Malaya",
    "Chulalongkorn University",
    "University of Indonesia",
    "University of the Philippines",
    "Vietnam National University",
    "Hebrew University of Jerusalem",
    "Tel Aviv University",
    "Technion",
    "Weizmann Institute",
    "King Abdullah University KAUST",
    "American University of Beirut",
    "American University in Cairo",
    "Cairo University",
    "University of Cape Town",
    "University of the Witwatersrand",
    "Stellenbosch University",
    "University of Nairobi",
    "University of Lagos",
    "University of Ibadan",
    "Makerere University",
    "University of Ghana",
    "University of Sao Paulo",
    "University of Campinas",
    "Federal University of Rio de Janeiro",
    "University of Buenos Aires",
    "Pontifical Catholic University of Chile",
    "University of Chile",
    "National Autonomous University of Mexico",
    "Monterrey Institute of Technology",
    "University of the Andes Colombia",
    "National University of Colombia",
    "Moscow State University",
    "Istanbul University",
    "Bogazici University",
    "Middle East Technical University",
]


def _build() -> list[ScienceFeed]:
    feeds: list[ScienceFeed] = []
    seen: set[str] = set()
    for column, kicker, glyph, suffix, topics in _GROUPS:
        logo = f"{_TWEMOJI}/{glyph}.png"
        for topic in topics:
            source_id = f"sci-{_slug(topic)}"
            if source_id in seen:
                continue
            seen.add(source_id)
            query = _q(f"{topic} {suffix}") if suffix else _q(topic)
            feeds.append((query, source_id, topic, kicker, column, logo))
    for name in UNIVERSITIES:
        source_id = f"uni-{_slug(name)}"
        if source_id in seen:
            continue
        seen.add(source_id)
        feeds.append(
            (f'"{_q(name)}"', source_id, name, "Campus", "science", _UNI_GLYPH)
        )
    return feeds


SCIENCE_FEEDS: list[ScienceFeed] = _build()
