"""Sports team & league news feeds, plus the per-country sports map used to
tailor the default deck by the visitor's location.

Each entry becomes a Google News search feed (see ``sources/teams.py`` for the
getters and ``metadata.py`` for the ``SOURCES`` entries). Feeds live under the
``sports`` column; the team name is the card title and the sport is the kicker.

Nothing here imports from the ``news`` package, so both ``metadata`` and
``sources.teams`` can import it without a circular dependency.
"""

from __future__ import annotations

import re

# A feed tuple: (google-news-query, source_id, card_name, sport_kicker).
TeamFeed = tuple[str, str, str, str]


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def _q(text: str) -> str:
    return re.sub(r"\s+", "+", text.strip())


# ── Sport / league-level feeds ───────────────────────────────────────────────
# (query, id, name, kicker). Stable ids so COUNTRY_SPORTS can reference them.
_SPORT_FEEDS: list[TeamFeed] = [
    ("Premier+League+football", "sport-premier-league", "Premier League", "Soccer"),
    ("La+Liga+football", "sport-la-liga", "La Liga", "Soccer"),
    ("Serie+A+football", "sport-serie-a", "Serie A", "Soccer"),
    ("Bundesliga+football", "sport-bundesliga", "Bundesliga", "Soccer"),
    ("Ligue+1+football", "sport-ligue-1", "Ligue 1", "Soccer"),
    ("Champions+League", "sport-champions-league", "Champions League", "Soccer"),
    ("Europa+League", "sport-europa-league", "Europa League", "Soccer"),
    ("MLS+soccer", "sport-mls", "MLS", "Soccer"),
    ("Liga+MX", "sport-liga-mx", "Liga MX", "Soccer"),
    ("Brasileirao", "sport-brasileirao", "Brasileirão", "Soccer"),
    ("Eredivisie", "sport-eredivisie", "Eredivisie", "Soccer"),
    ("Primeira+Liga", "sport-primeira-liga", "Primeira Liga", "Soccer"),
    ("Scottish+Premiership", "sport-spfl", "Scottish Premiership", "Soccer"),
    ("Saudi+Pro+League", "sport-saudi-league", "Saudi Pro League", "Soccer"),
    ("NBA", "sport-nba", "NBA", "Basketball"),
    ("EuroLeague+basketball", "sport-euroleague", "EuroLeague", "Basketball"),
    ("NCAA+basketball", "sport-ncaa-basketball", "College Basketball", "Basketball"),
    ("WNBA", "sport-wnba", "WNBA", "Basketball"),
    ("NFL", "sport-nfl", "NFL", "American Football"),
    (
        "NCAA+college+football",
        "sport-college-football",
        "College Football",
        "American Football",
    ),
    ("MLB+baseball", "sport-mlb", "MLB", "Baseball"),
    ("NPB+baseball+Japan", "sport-npb", "NPB", "Baseball"),
    ("KBO+baseball", "sport-kbo", "KBO", "Baseball"),
    ("NHL+hockey", "sport-nhl", "NHL", "Ice Hockey"),
    ("IPL+cricket", "sport-ipl", "IPL", "Cricket"),
    ("Test+cricket", "sport-test-cricket", "Test Cricket", "Cricket"),
    ("Big+Bash+League", "sport-big-bash", "Big Bash", "Cricket"),
    ("The+Hundred+cricket", "sport-the-hundred", "The Hundred", "Cricket"),
    ("Six+Nations+rugby", "sport-six-nations", "Six Nations", "Rugby"),
    ("Rugby+Championship", "sport-rugby-championship", "Rugby Championship", "Rugby"),
    ("United+Rugby+Championship", "sport-urc", "URC", "Rugby"),
    ("NRL+rugby+league", "sport-nrl", "NRL", "Rugby League"),
    ("Super+League+rugby", "sport-super-league-rl", "Super League", "Rugby League"),
    ("AFL+Australian+football", "sport-afl", "AFL", "Aussie Rules"),
    ("Gaelic+football", "sport-gaelic-football", "Gaelic Football", "Gaelic Games"),
    ("hurling", "sport-hurling", "Hurling", "Gaelic Games"),
    ("Formula+1", "sport-formula-1", "Formula 1", "Motorsport"),
    ("MotoGP", "sport-motogp", "MotoGP", "Motorsport"),
    ("NASCAR", "sport-nascar", "NASCAR", "Motorsport"),
    ("IndyCar", "sport-indycar", "IndyCar", "Motorsport"),
    ("ATP+tennis", "sport-atp-tennis", "ATP Tour", "Tennis"),
    ("WTA+tennis", "sport-wta-tennis", "WTA Tour", "Tennis"),
    ("PGA+Tour+golf", "sport-pga-tour", "PGA Tour", "Golf"),
    ("UFC", "sport-ufc", "UFC", "MMA"),
    ("boxing", "sport-boxing", "Boxing", "Boxing"),
    ("Tour+de+France+cycling", "sport-cycling", "Cycling", "Cycling"),
    ("EuroLeague+handball", "sport-handball", "Handball", "Handball"),
    ("FIVB+volleyball", "sport-volleyball", "Volleyball", "Volleyball"),
    ("PDC+darts", "sport-darts", "Darts", "Darts"),
    ("snooker", "sport-snooker", "Snooker", "Snooker"),
    ("League+of+Legends+esports", "sport-lol-esports", "LoL Esports", "Esports"),
    ("Counter-Strike+esports", "sport-cs-esports", "CS Esports", "Esports"),
]

# ── Team rosters per sport ───────────────────────────────────────────────────
# {sport_key: (kicker, query_suffix, [team names...])}. The query is
# "team+suffix"; the source id is "team-{sport_key}-{slug(team)}".
_TEAM_LISTS: dict[str, tuple[str, str, list[str]]] = {
    "soccer": (
        "Soccer",
        "football",
        [
            # England
            "Arsenal",
            "Chelsea",
            "Liverpool",
            "Manchester United",
            "Manchester City",
            "Tottenham Hotspur",
            "Newcastle United",
            "Aston Villa",
            "West Ham United",
            "Everton",
            "Leeds United",
            "Nottingham Forest",
            "Wolverhampton Wanderers",
            "Brighton",
            "Crystal Palace",
            "Fulham",
            "Brentford",
            "Bournemouth",
            # Spain
            "Real Madrid",
            "FC Barcelona",
            "Atletico Madrid",
            "Sevilla",
            "Real Betis",
            "Valencia CF",
            "Villarreal",
            "Athletic Bilbao",
            "Real Sociedad",
            "Celta Vigo",
            "Girona FC",
            # Italy
            "Juventus",
            "AC Milan",
            "Inter Milan",
            "AS Roma",
            "Napoli",
            "Lazio",
            "Atalanta",
            "Fiorentina",
            # Germany
            "Bayern Munich",
            "Borussia Dortmund",
            "RB Leipzig",
            "Bayer Leverkusen",
            "Eintracht Frankfurt",
            "Schalke 04",
            "VfB Stuttgart",
            "Borussia Monchengladbach",
            # France
            "Paris Saint-Germain",
            "Olympique Marseille",
            "Olympique Lyonnais",
            "AS Monaco",
            "Lille OSC",
            "OGC Nice",
            # Netherlands / Portugal / Scotland
            "Ajax",
            "PSV Eindhoven",
            "Feyenoord",
            "Benfica",
            "FC Porto",
            "Sporting CP",
            "Celtic FC",
            "Rangers FC",
            # Rest of Europe
            "Galatasaray",
            "Fenerbahce",
            "Besiktas",
            "Shakhtar Donetsk",
            "Red Star Belgrade",
            "Olympiacos",
            "Anderlecht",
            "Club Brugge",
            "Dynamo Kyiv",
            "Zenit Saint Petersburg",
            "Salzburg",
            # Americas
            "LA Galaxy",
            "Inter Miami",
            "LAFC",
            "Seattle Sounders",
            "Atlanta United",
            "Club America",
            "Chivas Guadalajara",
            "Boca Juniors",
            "River Plate",
            "Flamengo",
            "Palmeiras",
            "Corinthians",
            "Sao Paulo FC",
            "Santos FC",
            # Middle East / Asia / Africa
            "Al Nassr",
            "Al Hilal",
            "Al Ittihad",
            "Al Ahli",
            "Al Ahly",
            "Zamalek",
            "Kaizer Chiefs",
            "Mamelodi Sundowns",
            "Urawa Red Diamonds",
            "Kashima Antlers",
            # National teams
            "England national football team",
            "France national football team",
            "Brazil national football team",
            "Argentina national football team",
            "Spain national football team",
            "Germany national football team",
            "Portugal national football team",
            "Netherlands national football team",
            "Italy national football team",
            "Ireland national football team",
            "USMNT",
            "Mexico national football team",
            "Japan national football team",
        ],
    ),
    "nba": (
        "NBA",
        "NBA",
        [
            "Atlanta Hawks",
            "Boston Celtics",
            "Brooklyn Nets",
            "Charlotte Hornets",
            "Chicago Bulls",
            "Cleveland Cavaliers",
            "Dallas Mavericks",
            "Denver Nuggets",
            "Detroit Pistons",
            "Golden State Warriors",
            "Houston Rockets",
            "Indiana Pacers",
            "LA Clippers",
            "Los Angeles Lakers",
            "Memphis Grizzlies",
            "Miami Heat",
            "Milwaukee Bucks",
            "Minnesota Timberwolves",
            "New Orleans Pelicans",
            "New York Knicks",
            "Oklahoma City Thunder",
            "Orlando Magic",
            "Philadelphia 76ers",
            "Phoenix Suns",
            "Portland Trail Blazers",
            "Sacramento Kings",
            "San Antonio Spurs",
            "Toronto Raptors",
            "Utah Jazz",
            "Washington Wizards",
        ],
    ),
    "nfl": (
        "NFL",
        "NFL",
        [
            "Arizona Cardinals",
            "Atlanta Falcons",
            "Baltimore Ravens",
            "Buffalo Bills",
            "Carolina Panthers",
            "Chicago Bears",
            "Cincinnati Bengals",
            "Cleveland Browns",
            "Dallas Cowboys",
            "Denver Broncos",
            "Detroit Lions",
            "Green Bay Packers",
            "Houston Texans",
            "Indianapolis Colts",
            "Jacksonville Jaguars",
            "Kansas City Chiefs",
            "Las Vegas Raiders",
            "Los Angeles Chargers",
            "Los Angeles Rams",
            "Miami Dolphins",
            "Minnesota Vikings",
            "New England Patriots",
            "New Orleans Saints",
            "New York Giants",
            "New York Jets",
            "Philadelphia Eagles",
            "Pittsburgh Steelers",
            "San Francisco 49ers",
            "Seattle Seahawks",
            "Tampa Bay Buccaneers",
            "Tennessee Titans",
            "Washington Commanders",
        ],
    ),
    "mlb": (
        "MLB",
        "baseball",
        [
            "Arizona Diamondbacks",
            "Atlanta Braves",
            "Baltimore Orioles",
            "Boston Red Sox",
            "Chicago Cubs",
            "Chicago White Sox",
            "Cincinnati Reds",
            "Cleveland Guardians",
            "Colorado Rockies",
            "Detroit Tigers",
            "Houston Astros",
            "Kansas City Royals",
            "Los Angeles Angels",
            "Los Angeles Dodgers",
            "Miami Marlins",
            "Milwaukee Brewers",
            "Minnesota Twins",
            "New York Mets",
            "New York Yankees",
            "Oakland Athletics",
            "Philadelphia Phillies",
            "Pittsburgh Pirates",
            "San Diego Padres",
            "San Francisco Giants",
            "Seattle Mariners",
            "St. Louis Cardinals",
            "Tampa Bay Rays",
            "Texas Rangers",
            "Toronto Blue Jays",
            "Washington Nationals",
        ],
    ),
    "nhl": (
        "NHL",
        "hockey",
        [
            "Anaheim Ducks",
            "Boston Bruins",
            "Buffalo Sabres",
            "Calgary Flames",
            "Carolina Hurricanes",
            "Chicago Blackhawks",
            "Colorado Avalanche",
            "Columbus Blue Jackets",
            "Dallas Stars",
            "Detroit Red Wings",
            "Edmonton Oilers",
            "Florida Panthers",
            "Los Angeles Kings",
            "Minnesota Wild",
            "Montreal Canadiens",
            "Nashville Predators",
            "New Jersey Devils",
            "New York Islanders",
            "New York Rangers",
            "Ottawa Senators",
            "Philadelphia Flyers",
            "Pittsburgh Penguins",
            "San Jose Sharks",
            "Seattle Kraken",
            "St. Louis Blues",
            "Tampa Bay Lightning",
            "Toronto Maple Leafs",
            "Vancouver Canucks",
            "Vegas Golden Knights",
            "Washington Capitals",
            "Winnipeg Jets",
            "Utah Hockey Club",
        ],
    ),
    "cricket": (
        "Cricket",
        "cricket",
        [
            # IPL
            "Mumbai Indians",
            "Chennai Super Kings",
            "Royal Challengers Bengaluru",
            "Kolkata Knight Riders",
            "Delhi Capitals",
            "Rajasthan Royals",
            "Sunrisers Hyderabad",
            "Punjab Kings",
            "Gujarat Titans",
            "Lucknow Super Giants",
            # National teams
            "India national cricket team",
            "Australia national cricket team",
            "England cricket team",
            "Pakistan cricket team",
            "South Africa cricket team",
            "New Zealand cricket team",
            "West Indies cricket team",
            "Sri Lanka cricket team",
            "Bangladesh cricket team",
            "Afghanistan cricket team",
        ],
    ),
    "rugby": (
        "Rugby",
        "rugby",
        [
            "Leinster Rugby",
            "Munster Rugby",
            "Ulster Rugby",
            "Connacht Rugby",
            "Saracens",
            "Leicester Tigers",
            "Toulouse rugby",
            "Racing 92",
            "Crusaders rugby",
            "Bulls rugby",
            "Stormers rugby",
            "Ireland national rugby team",
            "New Zealand All Blacks",
            "South Africa Springboks",
            "England rugby team",
            "Wales rugby team",
            "France national rugby team",
            "Australia Wallabies",
            "Scotland rugby team",
        ],
    ),
    "rugbyleague": (
        "Rugby League",
        "NRL",
        [
            "Brisbane Broncos",
            "Melbourne Storm",
            "Sydney Roosters",
            "South Sydney Rabbitohs",
            "Penrith Panthers",
            "Parramatta Eels",
            "Wigan Warriors",
            "St Helens",
            "Leeds Rhinos",
        ],
    ),
    "gaafootball": (
        "Gaelic Football",
        "GAA football",
        [
            "Dublin",
            "Kerry",
            "Mayo",
            "Galway",
            "Tyrone",
            "Donegal",
            "Armagh",
            "Derry",
            "Cork",
            "Meath",
            "Monaghan",
            "Roscommon",
        ],
    ),
    "hurling": (
        "Hurling",
        "hurling GAA",
        [
            "Limerick",
            "Kilkenny",
            "Cork",
            "Tipperary",
            "Galway",
            "Clare",
            "Waterford",
            "Wexford",
            "Dublin",
        ],
    ),
    "afl": (
        "AFL",
        "AFL",
        [
            "Adelaide Crows",
            "Brisbane Lions",
            "Carlton Blues",
            "Collingwood Magpies",
            "Essendon Bombers",
            "Fremantle Dockers",
            "Geelong Cats",
            "Gold Coast Suns",
            "GWS Giants",
            "Hawthorn Hawks",
            "Melbourne Demons",
            "North Melbourne Kangaroos",
            "Port Adelaide",
            "Richmond Tigers",
            "St Kilda Saints",
            "Sydney Swans",
            "West Coast Eagles",
            "Western Bulldogs",
        ],
    ),
    "f1": (
        "Formula 1",
        "F1",
        [
            "Red Bull Racing",
            "Ferrari F1",
            "Mercedes F1",
            "McLaren F1",
            "Aston Martin F1",
            "Alpine F1",
            "Williams F1",
            "RB F1 team",
            "Haas F1",
            "Kick Sauber",
        ],
    ),
    "motogp": (
        "MotoGP",
        "MotoGP",
        [
            "Ducati Lenovo",
            "Aprilia Racing",
            "Monster Energy Yamaha",
            "Repsol Honda",
            "KTM MotoGP",
            "Gresini Racing",
        ],
    ),
    "tennis": (
        "Tennis",
        "tennis",
        [
            "Novak Djokovic",
            "Carlos Alcaraz",
            "Jannik Sinner",
            "Daniil Medvedev",
            "Alexander Zverev",
            "Rafael Nadal",
            "Iga Swiatek",
            "Aryna Sabalenka",
            "Coco Gauff",
            "Elena Rybakina",
        ],
    ),
    "golf": (
        "Golf",
        "golf",
        [
            "Scottie Scheffler",
            "Rory McIlroy",
            "Jon Rahm",
            "Tiger Woods",
            "Xander Schauffele",
            "Brooks Koepka",
            "Bryson DeChambeau",
        ],
    ),
    "mma": (
        "MMA",
        "UFC",
        [
            "Jon Jones",
            "Islam Makhachev",
            "Alex Pereira",
            "Conor McGregor",
            "Ilia Topuria",
            "Sean O'Malley",
            "Leon Edwards",
        ],
    ),
    "esports": (
        "Esports",
        "esports",
        [
            "T1 esports",
            "G2 Esports",
            "Fnatic",
            "Cloud9",
            "Team Liquid",
            "FaZe Clan",
            "Natus Vincere",
        ],
    ),
}


# Supplemental rosters, merged into the sport lists above (build dedupes by id).
# Deep league squads, national teams, and more sports/players to reach broad
# global coverage.
_TEAM_LISTS_EXTRA: dict[str, tuple[str, str, list[str]]] = {
    "soccer": (
        "Soccer",
        "football",
        [
            # England - rest of PL + Championship
            "Ipswich Town",
            "Leicester City",
            "Southampton",
            "Norwich City",
            "West Bromwich Albion",
            "Middlesbrough",
            "Coventry City",
            "Hull City",
            "Cardiff City",
            "Bristol City",
            "Preston North End",
            "Millwall",
            "Swansea City",
            "Watford",
            "Stoke City",
            "Sheffield Wednesday",
            "Sheffield United",
            "Blackburn Rovers",
            "Sunderland",
            "Queens Park Rangers",
            "Plymouth Argyle",
            "Luton Town",
            "Oxford United",
            "Portsmouth",
            "Derby County",
            # Spain - rest of La Liga
            "Osasuna",
            "Getafe",
            "Rayo Vallecano",
            "RCD Mallorca",
            "Deportivo Alaves",
            "UD Las Palmas",
            "RCD Espanyol",
            "CD Leganes",
            "Real Valladolid",
            # Italy - rest of Serie A
            "Torino",
            "Bologna",
            "Udinese",
            "Genoa",
            "Cagliari",
            "Empoli",
            "Hellas Verona",
            "Lecce",
            "Como 1907",
            "Monza",
            "Parma Calcio",
            "Venezia",
            "Sassuolo",
            # Germany - rest of Bundesliga
            "VfL Wolfsburg",
            "SC Freiburg",
            "TSG Hoffenheim",
            "Mainz 05",
            "Werder Bremen",
            "FC Augsburg",
            "Union Berlin",
            "Hertha BSC",
            "Hamburger SV",
            "FC Koln",
            "VfL Bochum",
            "Heidenheim",
            "Holstein Kiel",
            "St Pauli",
            # France - rest of Ligue 1
            "Stade Rennais",
            "RC Lens",
            "FC Nantes",
            "RC Strasbourg",
            "Montpellier",
            "Stade de Reims",
            "Toulouse FC",
            "Stade Brestois",
            "AJ Auxerre",
            "Le Havre",
            "Angers SCO",
            "Saint-Etienne",
            # Netherlands / Portugal / Turkey / Greece / Belgium / Scotland
            "AZ Alkmaar",
            "FC Twente",
            "FC Utrecht",
            "Vitesse",
            "SC Heerenveen",
            "SC Braga",
            "Vitoria Guimaraes",
            "Boavista",
            "Trabzonspor",
            "Istanbul Basaksehir",
            "Panathinaikos",
            "AEK Athens",
            "PAOK",
            "KRC Genk",
            "Standard Liege",
            "KAA Gent",
            "Royal Antwerp",
            "Aberdeen FC",
            "Heart of Midlothian",
            "Hibernian",
            # MLS
            "New York Red Bulls",
            "New York City FC",
            "Columbus Crew",
            "Portland Timbers",
            "Toronto FC",
            "Nashville SC",
            "Austin FC",
            "FC Cincinnati",
            "Philadelphia Union",
            "Orlando City",
            "Sporting Kansas City",
            "Minnesota United",
            "Real Salt Lake",
            "Houston Dynamo",
            "Colorado Rapids",
            "San Jose Earthquakes",
            "Vancouver Whitecaps",
            "CF Montreal",
            "Chicago Fire",
            "DC United",
            "New England Revolution",
            "FC Dallas",
            "St Louis City SC",
            # Liga MX / Brazil / Argentina / Saudi
            "Tigres UANL",
            "CF Monterrey",
            "Cruz Azul",
            "Pumas UNAM",
            "Deportivo Toluca",
            "Santos Laguna",
            "CF Pachuca",
            "Club Leon",
            "Fluminense",
            "Botafogo",
            "Gremio",
            "Internacional",
            "Atletico Mineiro",
            "Cruzeiro",
            "Vasco da Gama",
            "EC Bahia",
            "Fortaleza EC",
            "Racing Club",
            "Independiente",
            "San Lorenzo",
            "Velez Sarsfield",
            "Estudiantes",
            "Newells Old Boys",
            "Rosario Central",
            "Al Shabab",
            "Al Ettifaq",
            # National teams
            "Belgium national football team",
            "Croatia national football team",
            "Denmark national football team",
            "Sweden national football team",
            "Switzerland national football team",
            "Poland national football team",
            "Austria national football team",
            "Serbia national football team",
            "Ukraine national football team",
            "Turkey national football team",
            "Greece national football team",
            "Wales national football team",
            "Scotland national football team",
            "Nigeria national football team",
            "Ghana national football team",
            "Senegal national football team",
            "Ivory Coast national football team",
            "Cameroon national football team",
            "Morocco national football team",
            "Egypt national football team",
            "Algeria national football team",
            "Tunisia national football team",
            "South Africa national football team",
            "Colombia national football team",
            "Uruguay national football team",
            "Chile national football team",
            "Peru national football team",
            "Ecuador national football team",
            "Paraguay national football team",
            "Venezuela national football team",
            "Costa Rica national football team",
            "Canada national soccer team",
            "South Korea national football team",
            "Australia national soccer team",
            "Iran national football team",
            "Saudi Arabia national football team",
            "Qatar national football team",
            "China national football team",
            "India national football team",
            "Norway national football team",
        ],
    ),
    "basketball": (
        "Basketball",
        "basketball EuroLeague",
        [
            "Real Madrid Baloncesto",
            "FC Barcelona Basquet",
            "Panathinaikos BC",
            "Olympiacos BC",
            "Fenerbahce Beko",
            "Anadolu Efes",
            "Maccabi Tel Aviv",
            "Zalgiris Kaunas",
            "AS Monaco Basket",
            "Bayern Munich Basketball",
            "Olimpia Milano",
            "Virtus Bologna",
            "Partizan Belgrade",
            "Crvena Zvezda basketball",
            "Baskonia",
            "Valencia Basket",
            "ASVEL",
        ],
    ),
    "ncaaf": (
        "College Football",
        "college football",
        [
            "Alabama Crimson Tide",
            "Georgia Bulldogs",
            "Ohio State Buckeyes",
            "Michigan Wolverines",
            "Texas Longhorns",
            "Oklahoma Sooners",
            "USC Trojans",
            "Notre Dame Fighting Irish",
            "LSU Tigers",
            "Clemson Tigers",
            "Florida Gators",
            "Tennessee Volunteers",
            "Oregon Ducks",
            "Penn State Nittany Lions",
            "Wisconsin Badgers",
            "Auburn Tigers",
            "Texas A&M Aggies",
            "Florida State Seminoles",
            "Miami Hurricanes",
            "Nebraska Cornhuskers",
            "Michigan State Spartans",
            "Iowa Hawkeyes",
            "UCLA Bruins",
            "Washington Huskies",
            "Utah Utes",
            "Ole Miss Rebels",
            "Missouri Tigers",
            "Kentucky Wildcats",
            "Arkansas Razorbacks",
            "South Carolina Gamecocks",
        ],
    ),
    "ncaab": (
        "College Basketball",
        "college basketball",
        [
            "Duke Blue Devils",
            "Kentucky Wildcats basketball",
            "North Carolina Tar Heels",
            "Kansas Jayhawks",
            "UCLA Bruins basketball",
            "Gonzaga Bulldogs",
            "Michigan State Spartans basketball",
            "Villanova Wildcats",
            "Indiana Hoosiers",
            "Louisville Cardinals",
            "UConn Huskies",
            "Arizona Wildcats",
            "Baylor Bears",
            "Houston Cougars",
            "Purdue Boilermakers",
            "Tennessee Volunteers basketball",
            "Marquette Golden Eagles",
            "Alabama Crimson Tide basketball",
        ],
    ),
    "npb": (
        "NPB",
        "baseball",
        [
            "Yomiuri Giants",
            "Hanshin Tigers",
            "Fukuoka SoftBank Hawks",
            "Hiroshima Toyo Carp",
            "Yokohama DeNA BayStars",
            "Tokyo Yakult Swallows",
            "Chunichi Dragons",
            "Orix Buffaloes",
            "Chiba Lotte Marines",
            "Tohoku Rakuten Golden Eagles",
            "Saitama Seibu Lions",
            "Hokkaido Nippon-Ham Fighters",
        ],
    ),
    "kbo": (
        "KBO",
        "baseball KBO",
        [
            "LG Twins",
            "KT Wiz",
            "SSG Landers",
            "NC Dinos",
            "Doosan Bears",
            "KIA Tigers",
            "Lotte Giants",
            "Samsung Lions",
            "Hanwha Eagles",
            "Kiwoom Heroes",
        ],
    ),
    "cricket": (
        "Cricket",
        "cricket",
        [
            "Lahore Qalandars",
            "Karachi Kings",
            "Islamabad United",
            "Peshawar Zalmi",
            "Multan Sultans",
            "Quetta Gladiators",
            "Sydney Sixers",
            "Perth Scorchers",
            "Melbourne Stars",
            "Melbourne Renegades",
            "Brisbane Heat",
            "Adelaide Strikers",
            "Hobart Hurricanes",
            "Sydney Thunder",
            "Trinbago Knight Riders",
            "Guyana Amazon Warriors",
            "Barbados Royals",
            "MI Cape Town",
            "Sunrisers Eastern Cape",
            "Yorkshire cricket",
            "Surrey cricket",
            "Lancashire cricket",
            "Warwickshire cricket",
            "Essex cricket",
            "Nottinghamshire cricket",
            "Somerset cricket",
            "Hampshire cricket",
            "Ireland cricket team",
            "Zimbabwe cricket team",
            "Scotland cricket team",
        ],
    ),
    "rugby": (
        "Rugby",
        "rugby",
        [
            "Bath Rugby",
            "Bristol Bears",
            "Sale Sharks",
            "Northampton Saints",
            "Gloucester Rugby",
            "Harlequins",
            "Exeter Chiefs",
            "Newcastle Falcons",
            "Toulon rugby",
            "La Rochelle rugby",
            "Union Bordeaux Begles",
            "Clermont Auvergne",
            "Montpellier rugby",
            "Castres Olympique",
            "Lyon OU",
            "Stade Francais",
            "Glasgow Warriors",
            "Edinburgh Rugby",
            "Cardiff Rugby",
            "Ospreys",
            "Scarlets",
            "Dragons rugby",
            "Benetton Rugby",
            "Blues rugby",
            "Chiefs rugby",
            "Hurricanes rugby",
            "Highlanders rugby",
            "Brumbies",
            "Queensland Reds",
            "NSW Waratahs",
        ],
    ),
    "gaafootball": (
        "Gaelic Football",
        "GAA football",
        [
            "Kildare",
            "Down",
            "Cavan",
            "Louth",
            "Offaly",
            "Laois",
            "Westmeath",
            "Wicklow",
            "Longford",
            "Wexford GAA",
            "Carlow",
            "Sligo",
            "Leitrim",
            "Fermanagh",
            "Antrim",
            "Clare GAA",
        ],
    ),
    "hurling": (
        "Hurling",
        "hurling GAA",
        [
            "Antrim hurling",
            "Laois hurling",
            "Offaly hurling",
            "Westmeath hurling",
            "Carlow hurling",
            "Kerry hurling",
            "Down hurling",
        ],
    ),
    "f1driver": (
        "Formula 1",
        "F1",
        [
            "Max Verstappen",
            "Lewis Hamilton",
            "Charles Leclerc",
            "Lando Norris",
            "Oscar Piastri",
            "Carlos Sainz",
            "George Russell",
            "Fernando Alonso",
            "Sergio Perez",
            "Pierre Gasly",
        ],
    ),
    "motogprider": (
        "MotoGP",
        "MotoGP",
        [
            "Francesco Bagnaia",
            "Jorge Martin",
            "Marc Marquez",
            "Enea Bastianini",
            "Brad Binder",
            "Fabio Quartararo",
        ],
    ),
    "tennis": (
        "Tennis",
        "tennis",
        [
            "Stefanos Tsitsipas",
            "Casper Ruud",
            "Andrey Rublev",
            "Taylor Fritz",
            "Holger Rune",
            "Grigor Dimitrov",
            "Alex de Minaur",
            "Ben Shelton",
            "Frances Tiafoe",
            "Jessica Pegula",
            "Ons Jabeur",
            "Zheng Qinwen",
            "Madison Keys",
            "Emma Raducanu",
            "Naomi Osaka",
        ],
    ),
    "golf": (
        "Golf",
        "golf",
        [
            "Justin Thomas",
            "Collin Morikawa",
            "Viktor Hovland",
            "Patrick Cantlay",
            "Max Homa",
            "Jordan Spieth",
            "Hideki Matsuyama",
            "Tommy Fleetwood",
            "Shane Lowry",
            "Justin Rose",
            "Sergio Garcia",
            "Dustin Johnson",
        ],
    ),
    "boxing": (
        "Boxing",
        "boxing",
        [
            "Canelo Alvarez",
            "Tyson Fury",
            "Oleksandr Usyk",
            "Anthony Joshua",
            "Terence Crawford",
            "Gervonta Davis",
            "Naoya Inoue",
            "Errol Spence",
            "Deontay Wilder",
            "Ryan Garcia",
            "Jake Paul",
            "Dmitry Bivol",
        ],
    ),
    "mma": (
        "MMA",
        "UFC",
        [
            "Dricus du Plessis",
            "Khamzat Chimaev",
            "Charles Oliveira",
            "Justin Gaethje",
            "Max Holloway",
            "Dustin Poirier",
            "Kamaru Usman",
            "Israel Adesanya",
            "Sean Strickland",
        ],
    ),
    "cycling": (
        "Cycling",
        "cycling",
        [
            "Tadej Pogacar",
            "Jonas Vingegaard",
            "Remco Evenepoel",
            "Mathieu van der Poel",
            "Wout van Aert",
            "Primoz Roglic",
            "UAE Team Emirates",
            "Team Visma Lease a Bike",
            "Ineos Grenadiers",
            "Soudal Quick-Step",
        ],
    ),
    "darts": (
        "Darts",
        "darts",
        [
            "Luke Humphries",
            "Luke Littler",
            "Michael van Gerwen",
            "Michael Smith",
            "Gerwyn Price",
            "Rob Cross",
        ],
    ),
    "snooker": (
        "Snooker",
        "snooker",
        [
            "Ronnie OSullivan",
            "Judd Trump",
            "Mark Selby",
            "Neil Robertson",
            "John Higgins",
            "Kyren Wilson",
        ],
    ),
    "nascar": (
        "NASCAR",
        "NASCAR",
        [
            "Kyle Larson",
            "Chase Elliott",
            "Denny Hamlin",
            "William Byron",
            "Ryan Blaney",
            "Christopher Bell",
            "Joey Logano",
            "Tyler Reddick",
        ],
    ),
    "esports": (
        "Esports",
        "esports",
        [
            "100 Thieves",
            "TSM esports",
            "Evil Geniuses",
            "Sentinels",
            "NRG esports",
            "Gen.G",
            "Dplus KIA",
            "JD Gaming",
            "Bilibili Gaming",
            "Top Esports",
            "Astralis",
            "Team Vitality",
            "MOUZ",
            "Heroic",
            "Complexity Gaming",
        ],
    ),
}


# Second supplemental batch: more clubs across world leagues, additional
# national teams, athletes, and country-specific sports (Kabaddi, KHL/SHL/Liiga
# hockey, handball, field hockey, netball, PBA/NBL basketball, sumo, etc.).
_TEAM_LISTS_EXTRA2: dict[str, tuple[str, str, list[str]]] = {
    "soccer": (
        "Soccer",
        "football",
        [
            # J-League / CSL / ISL / A-League
            "Yokohama F Marinos",
            "Kawasaki Frontale",
            "Vissel Kobe",
            "Gamba Osaka",
            "Cerezo Osaka",
            "FC Tokyo",
            "Nagoya Grampus",
            "Sanfrecce Hiroshima",
            "Shanghai Port",
            "Shanghai Shenhua",
            "Beijing Guoan",
            "Shandong Taishan",
            "Mumbai City FC",
            "Bengaluru FC",
            "Mohun Bagan",
            "Kerala Blasters",
            "Chennaiyin FC",
            "Melbourne Victory",
            "Melbourne City FC",
            "Sydney FC",
            "Western Sydney Wanderers",
            # Russia / Switzerland / Austria / Nordics / CEE
            "CSKA Moscow",
            "Spartak Moscow",
            "Lokomotiv Moscow",
            "FC Krasnodar",
            "Young Boys",
            "FC Basel",
            "FC Zurich",
            "Rapid Vienna",
            "Austria Vienna",
            "Sturm Graz",
            "Malmo FF",
            "AIK",
            "Hammarby",
            "Molde FK",
            "Bodo Glimt",
            "Rosenborg",
            "FC Copenhagen",
            "Brondby",
            "FC Midtjylland",
            "Legia Warsaw",
            "Lech Poznan",
            "Slavia Prague",
            "Sparta Prague",
            "Dinamo Zagreb",
            "Hajduk Split",
            "Partizan football",
            "Orlando Pirates",
            "Ferencvaros",
            "Ludogorets",
            "Steaua Bucuresti",
            # National teams (rest)
            "Jamaica national football team",
            "Panama national football team",
            "Honduras national football team",
            "Bolivia national football team",
            "New Zealand national football team",
            "Iraq national football team",
            "United Arab Emirates national football team",
            "Uzbekistan national football team",
            "Iceland national football team",
            "Finland national football team",
            "Northern Ireland national football team",
            "Hungary national football team",
            "Czech Republic national football team",
            "Slovakia national football team",
            "Slovenia national football team",
            "Romania national football team",
            "Bulgaria national football team",
            "Israel national football team",
            "Mali national football team",
            "Burkina Faso national football team",
            "DR Congo national football team",
            "Zambia national football team",
            "Kenya national football team",
            "Angola national football team",
            "Cape Verde national football team",
        ],
    ),
    "kabaddi": (
        "Kabaddi",
        "Pro Kabaddi",
        [
            "Patna Pirates",
            "U Mumba",
            "Bengaluru Bulls",
            "Jaipur Pink Panthers",
            "Dabang Delhi",
            "Puneri Paltan",
            "Bengal Warriors",
            "Tamil Thalaivas",
            "Haryana Steelers",
            "UP Yoddhas",
            "Telugu Titans",
            "Gujarat Giants",
        ],
    ),
    "khl": (
        "Ice Hockey",
        "KHL hockey",
        [
            "SKA Saint Petersburg",
            "CSKA Moscow hockey",
            "Ak Bars Kazan",
            "Metallurg Magnitogorsk",
            "Dynamo Moscow hockey",
            "Avangard Omsk",
        ],
    ),
    "eurohockey": (
        "Ice Hockey",
        "hockey",
        [
            "Frolunda HC",
            "Skelleftea AIK",
            "Farjestad BK",
            "Tappara",
            "HC Davos",
            "EV Zug",
            "Adler Mannheim",
            "Eisbaren Berlin",
        ],
    ),
    "handball": (
        "Handball",
        "handball",
        [
            "Barcelona handball",
            "Paris Saint-Germain Handball",
            "THW Kiel",
            "SG Flensburg-Handewitt",
            "Telekom Veszprem",
            "Kielce handball",
            "Aalborg Handball",
            "Nantes handball",
        ],
    ),
    "volleyball": (
        "Volleyball",
        "volleyball",
        [
            "Sir Safety Perugia",
            "Zenit Kazan volleyball",
            "Trentino Volley",
            "Jastrzebski Wegiel",
            "Halkbank Ankara",
            "Cucine Lube Civitanova",
        ],
    ),
    "fieldhockey": (
        "Field Hockey",
        "field hockey national team",
        [
            "India hockey",
            "Netherlands hockey",
            "Australia hockey",
            "Belgium hockey",
            "Germany hockey",
            "Argentina hockey",
            "England hockey",
            "Pakistan hockey",
        ],
    ),
    "netball": (
        "Netball",
        "netball",
        [
            "Australia Diamonds",
            "New Zealand Silver Ferns",
            "England Roses netball",
            "Jamaica Sunshine Girls netball",
            "Melbourne Vixens",
            "NSW Swifts",
        ],
    ),
    "pba": (
        "Basketball",
        "PBA basketball Philippines",
        [
            "Barangay Ginebra",
            "San Miguel Beermen",
            "TNT Tropang Giga",
            "Meralco Bolts",
            "Magnolia Hotshots",
            "Rain or Shine",
        ],
    ),
    "nbl": (
        "Basketball",
        "NBL basketball Australia",
        [
            "Sydney Kings",
            "Melbourne United",
            "Perth Wildcats",
            "New Zealand Breakers",
            "Brisbane Bullets",
            "Adelaide 36ers",
        ],
    ),
    "athletics": (
        "Athletics",
        "athletics",
        [
            "Usain Bolt",
            "Noah Lyles",
            "Sha'Carri Richardson",
            "Sydney McLaughlin",
            "Faith Kipyegon",
            "Eliud Kipchoge",
            "Mondo Duplantis",
            "Femke Bol",
            "Josh Kerr",
        ],
    ),
    "combat": (
        "Combat Sports",
        "sumo",
        [
            "Sumo wrestling",
            "Terunofuji",
            "Hoshoryu",
            "Kotozakura",
        ],
    ),
    "motorsport": (
        "Motorsport",
        "motorsport",
        [
            "World Rally Championship",
            "Formula E",
            "IndyCar Series",
            "Le Mans 24 Hours",
            "World Superbike",
        ],
    ),
}


# Third supplemental batch: deeper league squads, the remaining national teams,
# more athletes, and additional domestic competitions worldwide.
_TEAM_LISTS_EXTRA3: dict[str, tuple[str, str, list[str]]] = {
    "soccer": (
        "Soccer",
        "football",
        [
            # More English clubs
            "Birmingham City",
            "Wrexham AFC",
            "Bolton Wanderers",
            "Charlton Athletic",
            "Reading FC",
            "Huddersfield Town",
            "Peterborough United",
            "Wigan Athletic",
            "Bradford City",
            # More Spanish / Italian / German / French
            "Real Zaragoza",
            "Sporting Gijon",
            "Real Oviedo",
            "Racing Santander",
            "Sampdoria",
            "Palermo",
            "Bari",
            "Cremonese",
            "Pisa SC",
            "Fortuna Dusseldorf",
            "Nurnberg",
            "Kaiserslautern",
            "Hannover 96",
            "Karlsruher SC",
            "FC Metz",
            "FC Lorient",
            "SC Bastia",
            "Guingamp",
            # More Portugal / Turkey / Belgium / Netherlands
            "Rio Ave",
            "Famalicao",
            "Estoril Praia",
            "Sivasspor",
            "Konyaspor",
            "Adana Demirspor",
            "Cercle Brugge",
            "Sporting Charleroi",
            "KV Mechelen",
            "Sparta Rotterdam",
            "NEC Nijmegen",
            "Go Ahead Eagles",
            # More Brazil / Argentina / Mexico
            "Athletico Paranaense",
            "Red Bull Bragantino",
            "Goias",
            "Coritiba",
            "Ceara SC",
            "Argentinos Juniors",
            "Club Atletico Lanus",
            "Banfield",
            "Colon de Santa Fe",
            "Godoy Cruz",
            "Talleres de Cordoba",
            "Atlas FC",
            "Club Necaxa",
            "Queretaro FC",
            "Club Tijuana",
            "FC Juarez",
            "Mazatlan FC",
            # Gulf / Iran / Africa / Asia
            "Al Wehda",
            "Al Fateh",
            "Al Sadd",
            "Al Duhail",
            "Al Ain FC",
            "Al Wasl",
            "Persepolis",
            "Esteghlal",
            "Wydad Casablanca",
            "Raja Casablanca",
            "Esperance de Tunis",
            "Etoile du Sahel",
            "TP Mazembe",
            "Simba SC",
            "Young Africans",
            "Enyimba",
            "Jeonbuk Hyundai Motors",
            "Ulsan HD",
            "FC Seoul",
            "Guangzhou FC",
            # More national teams
            "Georgia national football team",
            "Albania national football team",
            "North Macedonia national football team",
            "Bosnia and Herzegovina national football team",
            "Montenegro national football team",
            "Kosovo national football team",
            "Armenia national football team",
            "Azerbaijan national football team",
            "Kazakhstan national football team",
            "Belarus national football team",
            "Latvia national football team",
            "Lithuania national football team",
            "Estonia national football team",
            "Luxembourg national football team",
            "Malta national football team",
            "Cyprus national football team",
            "Palestine national football team",
            "Jordan national football team",
            "Lebanon national football team",
            "Oman national football team",
            "Bahrain national football team",
            "Kuwait national football team",
            "Thailand national football team",
            "Vietnam national football team",
            "Indonesia national football team",
            "Malaysia national football team",
            "Philippines national football team",
            "Bangladesh national football team",
            "Guatemala national football team",
            "Haiti national football team",
            "Trinidad and Tobago national football team",
            "Curacao national football team",
            "Suriname national football team",
        ],
    ),
    "basketball": (
        "Basketball",
        "basketball EuroLeague",
        [
            "Zalgiris",
            "Alba Berlin",
            "Ratiopharm Ulm",
            "Zenit Saint Petersburg basketball",
            "Unicaja Malaga",
            "Gran Canaria basketball",
            "Cedevita Olimpija",
            "Buducnost",
            "Maccabi Playtika",
            "Hapoel Tel Aviv basketball",
            "Paris Basketball",
            "London Lions",
        ],
    ),
    "cricket": (
        "Cricket",
        "cricket",
        [
            "Mumbai Ranji",
            "Karnataka cricket",
            "Tamil Nadu cricket",
            "Delhi cricket",
            "Durham cricket",
            "Kent cricket",
            "Sussex cricket",
            "Glamorgan cricket",
            "Middlesex cricket",
            "Auckland Aces",
            "Wellington Firebirds",
            "Sydney Thunder WBBL",
            "Colombo Strikers",
            "Dubai Capitals",
            "Desert Vipers",
        ],
    ),
    "rugby": (
        "Rugby",
        "rugby",
        [
            "Saracens rugby",
            "Leicester Tigers rugby",
            "Perpignan rugby",
            "Pau rugby",
            "Bayonne rugby",
            "Ealing Trailfinders",
            "Emirates Lions",
            "Vodacom Bulls",
            "Hollywoodbets Sharks",
            "Fiji national rugby team",
            "Samoa national rugby team",
            "Tonga national rugby team",
            "Georgia national rugby team",
            "Japan national rugby team",
            "Argentina Pumas rugby",
        ],
    ),
    "golf": (
        "Golf",
        "golf",
        [
            "Ludvig Aberg",
            "Wyndham Clark",
            "Cameron Smith golf",
            "Adam Scott",
            "Matt Fitzpatrick",
            "Tony Finau",
            "Sahith Theegala",
            "Robert MacIntyre",
            "Nelly Korda",
            "Lydia Ko",
            "Brooke Henderson",
        ],
    ),
    "tennis": (
        "Tennis",
        "tennis",
        [
            "Hubert Hurkacz",
            "Karen Khachanov",
            "Tommy Paul",
            "Sebastian Korda",
            "Lorenzo Musetti",
            "Felix Auger-Aliassime",
            "Elena Rybakina tennis",
            "Barbora Krejcikova",
            "Jasmine Paolini",
            "Danielle Collins",
            "Mirra Andreeva",
            "Paula Badosa",
        ],
    ),
    "boxing": (
        "Boxing",
        "boxing",
        [
            "Shakur Stevenson",
            "Devin Haney",
            "Vasyl Lomachenko",
            "Dmitry Bivol boxing",
            "Artur Beterbiev",
            "David Benavidez",
            "Jaron Ennis",
            "Teofimo Lopez",
        ],
    ),
    "mma": (
        "MMA",
        "UFC",
        [
            "Merab Dvalishvili",
            "Movsar Evloev",
            "Arman Tsarukyan",
            "Belal Muhammad",
            "Tom Aspinall",
            "Jiri Prochazka",
            "Robert Whittaker",
            "Paddy Pimblett",
        ],
    ),
    "wintersports": (
        "Winter Sports",
        "skiing",
        [
            "Mikaela Shiffrin",
            "Marco Odermatt",
            "Alpine skiing World Cup",
            "Biathlon World Cup",
            "Figure skating",
            "Ski jumping World Cup",
            "Speed skating",
            "Bobsled",
        ],
    ),
    "swimming": (
        "Swimming",
        "swimming",
        [
            "Katie Ledecky",
            "Leon Marchand",
            "Summer McIntosh",
            "Caeleb Dressel",
            "Ariarne Titmus",
            "David Popovici",
        ],
    ),
    "esports": (
        "Esports",
        "esports",
        [
            "Karmine Corp",
            "BDS esports",
            "Team Falcons",
            "OG esports",
            "Team Spirit",
            "PSG Talon",
            "LOUD esports",
            "paiN Gaming",
            "T1 Valorant",
            "DRX",
        ],
    ),
    "ncaaf": (
        "College Football",
        "college football",
        [
            "Colorado Buffaloes",
            "Oregon State Beavers",
            "TCU Horned Frogs",
            "Baylor Bears football",
            "Kansas State Wildcats",
            "Iowa State Cyclones",
            "West Virginia Mountaineers",
            "Louisville Cardinals football",
            "NC State Wolfpack",
            "Virginia Tech Hokies",
            "Pittsburgh Panthers",
            "Boise State Broncos",
            "SMU Mustangs",
            "Memphis Tigers football",
        ],
    ),
}


def _merge_lists(
    *dicts: dict[str, tuple[str, str, list[str]]],
) -> dict[str, tuple[str, str, list[str]]]:
    merged: dict[str, tuple[str, str, list[str]]] = {}
    for d in dicts:
        for key, (kicker, suffix, teams) in d.items():
            if key in merged:
                merged[key] = (merged[key][0], merged[key][1], merged[key][2] + teams)
            else:
                merged[key] = (kicker, suffix, list(teams))
    return merged


# Fourth supplemental batch: WNBA, women's national football, more athletes and
# clubs across the world to round out broad coverage.
_TEAM_LISTS_EXTRA4: dict[str, tuple[str, str, list[str]]] = {
    "wnba": (
        "WNBA",
        "WNBA",
        [
            "Las Vegas Aces",
            "New York Liberty",
            "Connecticut Sun",
            "Seattle Storm",
            "Minnesota Lynx",
            "Chicago Sky",
            "Phoenix Mercury",
            "Indiana Fever",
            "Dallas Wings",
            "Atlanta Dream",
            "Washington Mystics",
            "Los Angeles Sparks",
        ],
    ),
    "womensoccer": (
        "Women's Soccer",
        "women national football team",
        [
            "United States women",
            "England Lionesses",
            "Spain women",
            "Germany women",
            "France women",
            "Sweden women",
            "Netherlands women",
            "Brazil women",
            "Canada women",
            "Australia Matildas",
            "Japan women",
            "Barcelona Femeni",
            "Arsenal Women",
            "Chelsea Women",
            "Lyon Feminin",
        ],
    ),
    "soccer": (
        "Soccer",
        "football",
        [
            "Watford FC",
            "Norwich City FC",
            "Blackpool FC",
            "Barnsley FC",
            "Fleetwood Town",
            "Real Betis Balompie",
            "Cadiz CF",
            "Elche CF",
            "Granada CF",
            "US Cremonese",
            "Frosinone Calcio",
            "Salernitana",
            "SV Darmstadt 98",
            "Greuther Furth",
            "Schalke 04 II",
            "AC Ajaccio",
            "Clermont Foot",
            "Estac Troyes",
            "Grenoble Foot",
            "Vitoria de Setubal",
            "Maritimo",
            "Gaziantep FK",
            "Kayserispor",
            "Antalyaspor",
            "Union Saint-Gilloise",
            "OH Leuven",
            "FC Volendam",
            "Willem II",
            "PEC Zwolle",
            "America Mineiro",
            "Juventude",
            "Vitoria Bahia",
            "Atletico Goianiense",
            "Huracan",
            "Platense",
            "Central Cordoba",
            "Instituto Cordoba",
            "Club Atletico Belgrano",
            "Pachuca women",
            "Al Shorta",
            "Al Zawraa",
            "Kaya FC",
            "Buriram United",
            "BG Pathum United",
            "Persija Jakarta",
            "Johor Darul Tazim",
            "Kitchee SC",
            "Shan United",
            "Mohammedan SC",
            "East Bengal",
            "Hyderabad FC",
            "Odisha FC",
            "FC Goa",
            "Jamshedpur FC",
            "Georgia national team football",
            "Serbia football",
            "Norway football",
            "Slovenia football team",
            "Uganda national football team",
            "Guinea national football team",
            "Gabon national football team",
            "Mozambique national football team",
            "Namibia national football team",
            "Benin national football team",
            "Madagascar national football team",
            "Sudan national football team",
            "Libya national football team",
            "Ethiopia national football team",
            "Tanzania national football team",
        ],
    ),
    "cycling": (
        "Cycling",
        "cycling",
        [
            "Team Jumbo",
            "EF Education",
            "Bahrain Victorious",
            "Movistar Team",
            "Alpecin Deceuninck",
            "Lidl Trek",
            "Team DSM",
            "Bora Hansgrohe",
            "Julian Alaphilippe",
            "Biniam Girmay",
        ],
    ),
    "athletics": (
        "Athletics",
        "athletics",
        [
            "Marcell Jacobs",
            "Karsten Warholm",
            "Ryan Crouser",
            "Shericka Jackson",
            "Shelly-Ann Fraser-Pryce",
            "Jakob Ingebrigtsen",
            "Letsile Tebogo",
            "Gabby Thomas",
            "Yulimar Rojas",
        ],
    ),
    "f1driver": (
        "Formula 1",
        "F1",
        [
            "Yuki Tsunoda",
            "Alexander Albon",
            "Nico Hulkenberg",
            "Esteban Ocon",
            "Lance Stroll",
            "Kevin Magnussen",
            "Valtteri Bottas",
            "Zhou Guanyu",
            "Liam Lawson",
            "Franco Colapinto",
        ],
    ),
    "darts": (
        "Darts",
        "darts",
        [
            "Nathan Aspinall",
            "Dave Chisnall",
            "Danny Noppert",
            "Peter Wright",
            "Jonny Clayton",
            "Stephen Bunting",
        ],
    ),
    "snooker": (
        "Snooker",
        "snooker",
        [
            "Mark Williams",
            "Shaun Murphy",
            "Barry Hawkins",
            "Ali Carter",
            "Zhao Xintong",
            "Luca Brecel",
        ],
    ),
    "golf": (
        "Golf",
        "golf",
        [
            "Sungjae Im",
            "Jason Day",
            "Corey Conners",
            "Keegan Bradley",
            "Russell Henley",
            "Akshay Bhatia",
            "Charley Hull",
            "Rose Zhang",
        ],
    ),
    "nba": (
        "NBA",
        "NBA basketball",
        [],
    ),
    "horseracing": (
        "Horse Racing",
        "horse racing",
        [
            "Cheltenham Festival",
            "Grand National",
            "Kentucky Derby",
            "Royal Ascot",
            "Melbourne Cup",
            "Breeders Cup",
        ],
    ),
    "gymnastics": (
        "Gymnastics",
        "gymnastics",
        ["Simone Biles", "Rebeca Andrade", "Sunisa Lee", "Artistic gymnastics"],
    ),
    "table": (
        "Table Tennis",
        "table tennis",
        ["Fan Zhendong", "Wang Chuqin", "Tomokazu Harimoto", "Ma Long"],
    ),
    "badminton": (
        "Badminton",
        "badminton",
        [
            "Viktor Axelsen",
            "An Se-young",
            "Kunlavut Vitidsarn",
            "PV Sindhu",
            "Lakshya Sen",
        ],
    ),
}


# Fifth supplemental batch - final coverage top-up across the board.
_TEAM_LISTS_EXTRA5: dict[str, tuple[str, str, list[str]]] = {
    "soccer": (
        "Soccer",
        "football",
        [
            "Coventry City FC",
            "Sheffield United FC",
            "West Brom",
            "Millwall FC",
            "Real Sociedad B",
            "Sporting Braga B",
            "Hertha Berlin II",
            "New York City",
            "Charlotte FC",
            "St Louis City",
            "Atlanta United FC",
            "Deportivo Cali",
            "Atletico Nacional",
            "Millonarios",
            "America de Cali",
            "Junior Barranquilla",
            "Universitario Peru",
            "Alianza Lima",
            "Colo-Colo",
            "Universidad de Chile",
            "Barcelona SC Ecuador",
            "LDU Quito",
            "Olimpia Paraguay",
            "Cerro Porteno",
            "Nacional Uruguay",
            "Penarol",
            "Kaizer Chiefs FC",
            "SuperSport United",
            "Al Merrikh",
            "Al Hilal Omdurman",
            "Sundowns FC",
            "ES Setif",
            "MC Alger",
            "Faroe Islands national football team",
            "Gibraltar national football team",
            "Hong Kong national football team",
            "Chinese Taipei football",
            "Myanmar national football team",
            "Cambodia national football team",
        ],
    ),
    "cricket": (
        "Cricket",
        "cricket",
        [
            "Saurashtra cricket",
            "Bengal cricket",
            "Vidarbha cricket",
            "Kerala cricket team",
            "Punjab cricket",
            "Rajasthan cricket",
            "Gloucestershire cricket",
            "Leicestershire cricket",
            "Central Districts",
            "Canterbury cricket",
            "Otago Volts",
            "Northamptonshire cricket",
            "Worcestershire cricket",
        ],
    ),
    "rugby": (
        "Rugby",
        "rugby",
        [
            "Doncaster Knights",
            "Coventry Rugby",
            "Jersey Reds",
            "Racing 92 rugby",
            "Section Paloise",
            "USA Perpignan",
            "Crusaders rugby team",
            "Moana Pasifika",
            "Fijian Drua",
        ],
    ),
    "mma": (
        "MMA",
        "UFC fighter",
        [
            "Alexandre Pantoja",
            "Brandon Moreno",
            "Sean Brady",
            "Ciryl Gane",
            "Jan Blachowicz",
            "Cory Sandhagen",
            "Umar Nurmagomedov",
            "Alexa Grasso",
        ],
    ),
    "boxing": (
        "Boxing",
        "boxing",
        [
            "Josh Taylor",
            "Chris Billam-Smith",
            "Zhilei Zhang",
            "Daniel Dubois",
            "Joe Joyce",
            "Nick Ball",
            "Leigh Wood",
        ],
    ),
    "esports": (
        "Esports",
        "esports",
        [
            "Weibo Gaming",
            "Hanwha Life Esports",
            "KT Rolster",
            "MAD Lions",
            "SK Gaming",
            "Team Heretics",
            "Furia esports",
            "MIBR",
            "Virtus.pro",
        ],
    ),
    "motorsport": (
        "Motorsport",
        "racing",
        [
            "Kyle Busch",
            "Martin Truex Jr",
            "Brad Keselowski",
            "Josef Newgarden",
            "Alex Palou",
            "Scott Dixon",
            "Pato OWard",
        ],
    ),
}


def _build_feeds() -> list[TeamFeed]:
    feeds: list[TeamFeed] = list(_SPORT_FEEDS)
    seen: set[str] = {sid for _q_, sid, _n, _k in _SPORT_FEEDS}
    for sport_key, (kicker, suffix, teams) in _merge_lists(
        _TEAM_LISTS,
        _TEAM_LISTS_EXTRA,
        _TEAM_LISTS_EXTRA2,
        _TEAM_LISTS_EXTRA3,
        _TEAM_LISTS_EXTRA4,
        _TEAM_LISTS_EXTRA5,
    ).items():
        for team in teams:
            source_id = f"team-{sport_key}-{_slug(team)}"
            if source_id in seen:
                continue
            seen.add(source_id)
            query = _q(f"{team} {suffix}") if suffix else _q(team)
            feeds.append((query, source_id, team, kicker))
    return feeds


# All team + sport feeds, deduplicated.
TEAM_FEEDS: list[TeamFeed] = _build_feeds()


# ── Per-country sports (geo default) ─────────────────────────────────────────
# ISO-3166 alpha-2 → the source ids that lead this country's sports slice in the
# default deck (the visitor's native sports, most-followed first). Ids must
# exist among TEAM_FEEDS above. Countries not listed keep the generic sports.
COUNTRY_SPORTS: dict[str, list[str]] = {
    "IE": [
        "sport-gaelic-football",
        "sport-hurling",
        "team-gaafootball-dublin",
        "sport-premier-league",
    ],
    "GB": [
        "sport-premier-league",
        "sport-champions-league",
        "team-rugby-leinsterrugby",
        "sport-six-nations",
    ],
    "US": ["sport-nfl", "sport-nba", "sport-mlb", "sport-nhl"],
    "CA": ["sport-nhl", "sport-nba", "sport-mlb", "sport-nfl"],
    "IN": [
        "sport-ipl",
        "team-cricket-mumbaiindians",
        "team-cricket-indianationalcricketteam",
        "sport-test-cricket",
    ],
    "AU": [
        "sport-afl",
        "sport-nrl",
        "team-cricket-australianationalcricketteam",
        "sport-rugby-championship",
    ],
    "NZ": [
        "team-rugby-newzealandallblacks",
        "sport-rugby-championship",
        "team-cricket-newzealandcricketteam",
        "sport-nrl",
    ],
    "ES": [
        "sport-la-liga",
        "team-soccer-realmadrid",
        "team-soccer-fcbarcelona",
        "sport-champions-league",
    ],
    "IT": [
        "sport-serie-a",
        "team-soccer-juventus",
        "team-soccer-acmilan",
        "sport-champions-league",
    ],
    "DE": [
        "sport-bundesliga",
        "team-soccer-bayernmunich",
        "team-soccer-borussiadortmund",
        "sport-champions-league",
    ],
    "FR": [
        "sport-ligue-1",
        "team-soccer-parissaintgermain",
        "sport-six-nations",
        "sport-champions-league",
    ],
    "BR": [
        "sport-brasileirao",
        "team-soccer-flamengo",
        "team-soccer-palmeiras",
        "sport-formula-1",
    ],
    "AR": [
        "team-soccer-bocajuniors",
        "team-soccer-riverplate",
        "team-soccer-argentinanationalfootballteam",
        "sport-la-liga",
    ],
    "MX": [
        "sport-liga-mx",
        "team-soccer-clubamerica",
        "team-soccer-chivasguadalajara",
        "sport-mlb",
    ],
    "PT": [
        "sport-primeira-liga",
        "team-soccer-benfica",
        "team-soccer-fcporto",
        "sport-champions-league",
    ],
    "NL": [
        "sport-eredivisie",
        "team-soccer-ajax",
        "team-soccer-psveindhoven",
        "sport-champions-league",
    ],
    "JP": [
        "sport-npb",
        "team-soccer-japannationalfootballteam",
        "sport-nba",
        "sport-motogp",
    ],
    "KR": ["sport-kbo", "sport-nba", "sport-premier-league", "sport-lol-esports"],
    "ZA": [
        "team-rugby-southafricaspringboks",
        "team-cricket-southafricacricketteam",
        "sport-rugby-championship",
        "sport-premier-league",
    ],
    "PK": [
        "team-cricket-pakistancricketteam",
        "sport-ipl",
        "sport-test-cricket",
        "sport-premier-league",
    ],
    "SA": [
        "sport-saudi-league",
        "team-soccer-alnassr",
        "team-soccer-alhilal",
        "sport-formula-1",
    ],
    "TR": [
        "team-soccer-galatasaray",
        "team-soccer-fenerbahce",
        "team-soccer-besiktas",
        "sport-euroleague",
    ],
    "SC": [
        "sport-spfl",
        "team-soccer-celticfc",
        "team-soccer-rangersfc",
        "sport-six-nations",
    ],
    "BE": [
        "team-soccer-clubbrugge",
        "team-soccer-anderlecht",
        "sport-champions-league",
        "sport-formula-1",
    ],
    "GR": [
        "team-soccer-olympiacos",
        "sport-euroleague",
        "sport-champions-league",
        "sport-premier-league",
    ],
    "UA": [
        "team-soccer-shakhtardonetsk",
        "team-soccer-dynamokyiv",
        "sport-champions-league",
        "sport-atp-tennis",
    ],
    "RU": [
        "team-soccer-zenitsaintpetersburg",
        "sport-nhl",
        "sport-champions-league",
        "sport-atp-tennis",
    ],
    "AT": [
        "team-soccer-salzburg",
        "sport-formula-1",
        "sport-bundesliga",
        "sport-champions-league",
    ],
    "EG": [
        "team-soccer-alahly",
        "team-soccer-zamalek",
        "sport-premier-league",
        "sport-champions-league",
    ],
    "RS": [
        "team-soccer-redstarbelgrade",
        "sport-euroleague",
        "sport-atp-tennis",
        "sport-champions-league",
    ],
    "BD": [
        "team-cricket-bangladeshcricketteam",
        "sport-ipl",
        "sport-test-cricket",
        "sport-premier-league",
    ],
    "LK": [
        "team-cricket-srilankacricketteam",
        "sport-ipl",
        "sport-test-cricket",
        "sport-premier-league",
    ],
    "AF": [
        "team-cricket-afghanistancricketteam",
        "sport-ipl",
        "sport-test-cricket",
        "sport-premier-league",
    ],
    "CN": ["sport-nba", "sport-lol-esports", "sport-premier-league", "sport-formula-1"],
    "SE": [
        "sport-nhl",
        "sport-premier-league",
        "sport-champions-league",
        "sport-atp-tennis",
    ],
    "FI": ["sport-nhl", "sport-formula-1", "sport-premier-league", "sport-motogp"],
    "NO": [
        "sport-premier-league",
        "team-soccer-manchestercity",
        "sport-champions-league",
        "sport-cycling",
    ],
    "CH": [
        "sport-champions-league",
        "sport-formula-1",
        "sport-atp-tennis",
        "sport-nhl",
    ],
    "PH": ["sport-nba", "sport-premier-league", "sport-ufc", "sport-boxing"],
    "ID": [
        "sport-premier-league",
        "sport-motogp",
        "sport-lol-esports",
        "sport-champions-league",
    ],
    "TH": [
        "sport-premier-league",
        "sport-motogp",
        "sport-ufc",
        "sport-champions-league",
    ],
    "NG": [
        "sport-premier-league",
        "team-soccer-chelsea",
        "sport-champions-league",
        "sport-nba",
    ],
    "MA": [
        "sport-champions-league",
        "sport-la-liga",
        "team-soccer-parissaintgermain",
        "sport-premier-league",
    ],
    "CO": ["sport-cycling", "sport-la-liga", "sport-champions-league", "sport-mlb"],
    "CL": [
        "sport-la-liga",
        "sport-champions-league",
        "sport-atp-tennis",
        "sport-formula-1",
    ],
    "PE": [
        "sport-la-liga",
        "sport-champions-league",
        "sport-brasileirao",
        "sport-atp-tennis",
    ],
    "SG": [
        "sport-premier-league",
        "sport-formula-1",
        "sport-nba",
        "sport-champions-league",
    ],
    "AE": [
        "sport-formula-1",
        "sport-premier-league",
        "sport-champions-league",
        "sport-ipl",
    ],
    "QA": [
        "team-soccer-parissaintgermain",
        "sport-champions-league",
        "sport-formula-1",
        "sport-premier-league",
    ],
    "CZ": [
        "sport-nhl",
        "sport-champions-league",
        "sport-premier-league",
        "sport-atp-tennis",
    ],
    "PL": [
        "team-soccer-fcbarcelona",
        "sport-champions-league",
        "sport-premier-league",
        "sport-formula-1",
    ],
}
