/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** EmailUpdateEmail */
    EmailUpdateEmail: {
      /**
       * Template
       * @default email_update
       * @constant
       */
      template: 'email_update'
      props: components['schemas']['EmailUpdateProps']
    }
    /** EmailUpdateProps */
    EmailUpdateProps: {
      /** Email */
      email: string
      /** Token Lifetime Minutes */
      token_lifetime_minutes: number
      /** Url */
      url: string
    }
    /** LoginCodeEmail */
    LoginCodeEmail: {
      /**
       * Template
       * @default login_code
       * @constant
       */
      template: 'login_code'
      props: components['schemas']['LoginCodeProps']
    }
    /** LoginCodeProps */
    LoginCodeProps: {
      /** Email */
      email: string
      /** Code */
      code: string
      /** Code Lifetime Minutes */
      code_lifetime_minutes: number
      /** Domain */
      domain: string
    }
    /** OAuth2LeakedClientEmail */
    OAuth2LeakedClientEmail: {
      /**
       * Template
       * @default oauth2_leaked_client
       * @constant
       */
      template: 'oauth2_leaked_client'
      props: components['schemas']['OAuth2LeakedClientProps']
    }
    /** OAuth2LeakedClientProps */
    OAuth2LeakedClientProps: {
      /** Email */
      email: string
      /** Token Type */
      token_type: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OAuth2LeakedTokenEmail */
    OAuth2LeakedTokenEmail: {
      /**
       * Template
       * @default oauth2_leaked_token
       * @constant
       */
      template: 'oauth2_leaked_token'
      props: components['schemas']['OAuth2LeakedTokenProps']
    }
    /** OAuth2LeakedTokenProps */
    OAuth2LeakedTokenProps: {
      /** Email */
      email: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OrganizationAccessTokenLeakedEmail */
    OrganizationAccessTokenLeakedEmail: {
      /**
       * Template
       * @default organization_access_token_leaked
       * @constant
       */
      template: 'organization_access_token_leaked'
      props: components['schemas']['OrganizationAccessTokenLeakedProps']
    }
    /** OrganizationAccessTokenLeakedProps */
    OrganizationAccessTokenLeakedProps: {
      /** Email */
      email: string
      /** Organization Access Token */
      organization_access_token: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OrganizationInviteEmail */
    OrganizationInviteEmail: {
      /**
       * Template
       * @default organization_invite
       * @constant
       */
      template: 'organization_invite'
      props: components['schemas']['OrganizationInviteProps']
    }
    /** OrganizationInviteProps */
    OrganizationInviteProps: {
      /** Email */
      email: string
      /** Organization Name */
      organization_name: string
      /** Inviter Email */
      inviter_email: string
      /** Invite Url */
      invite_url: string
    }
    /** PersonalAccessTokenLeakedEmail */
    PersonalAccessTokenLeakedEmail: {
      /**
       * Template
       * @default personal_access_token_leaked
       * @constant
       */
      template: 'personal_access_token_leaked'
      props: components['schemas']['PersonalAccessTokenLeakedProps']
    }
    /** PersonalAccessTokenLeakedProps */
    PersonalAccessTokenLeakedProps: {
      /** Email */
      email: string
      /** Personal Access Token */
      personal_access_token: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
