"""Generic RSS feeds — one factory registers all simple RSS sources.

Each entry is just (source_id, url); the factory creates an async getter
that follows the same parse_rss pattern as guardian.py and registers it
under the given id.  Redirect logic is handled at the metadata layer so
no special-casing is needed here.
"""

from ..fetch import NewsFetchError, fetch_text, parse_rss
from ..registry import register
from ..schemas import NewsItem

_FEEDS: list[tuple[str, str]] = [
    # Sports
    ("bbcsport", "https://feeds.bbci.co.uk/sport/rss.xml"),
    ("skysports", "https://www.skysports.com/rss/12040"),
    ("cbssports", "https://www.cbssports.com/rss/headlines/"),
    ("yahoosports", "https://sports.yahoo.com/rss/"),
    # Betting
    ("legalsportsreport", "https://www.legalsportsreport.com/feed/"),
    ("sbcnews", "https://sbcnews.co.uk/feed/"),
    # Finance
    ("cnbc", "https://www.cnbc.com/id/100003114/device/rss/rss.html"),
    ("marketwatch", "https://feeds.content.dowjones.io/public/rss/mw_topstories"),
    ("yahoofinance", "https://finance.yahoo.com/news/rssindex"),
    ("coindesk", "https://www.coindesk.com/arc/outboundfeeds/rss/"),
    # Entertainment
    ("variety", "https://variety.com/feed/"),
    ("billboard", "https://www.billboard.com/feed/"),
    ("hollywoodreporter", "https://www.hollywoodreporter.com/feed/"),
    # Politics
    ("thehill", "https://thehill.com/news/feed/"),
    # Science
    ("sciencedaily", "https://www.sciencedaily.com/rss/all.xml"),
    ("nasa", "https://www.nasa.gov/rss/dyn/breaking_news.rss"),
    ("statnews", "https://www.statnews.com/feed/"),
    # Gaming
    ("ign", "https://feeds.feedburner.com/ign/all"),
    ("polygon", "https://www.polygon.com/rss/index.xml"),
    # News (broadcast / international)
    ("cbsnews", "https://www.cbsnews.com/latest/rss/main"),
    ("abcnews", "https://abcnews.go.com/abcnews/topstories"),
    ("nbcnews", "https://feeds.nbcnews.com/nbcnews/public/news"),
    ("foxnews", "https://moxie.foxnews.com/google-publisher/latest.xml"),
    ("time", "https://time.com/feed/"),
    ("aljazeera", "https://www.aljazeera.com/xml/rss/all.xml"),
    ("skynews", "https://feeds.skynews.com/feeds/rss/home.xml"),
    ("dw", "https://rss.dw.com/rdf/rss-en-all"),
    ("france24", "https://www.france24.com/en/rss"),
    # Tech (additional)
    ("engadget", "https://www.engadget.com/rss.xml"),
    ("9to5mac", "https://9to5mac.com/feed/"),
    ("technologyreview", "https://www.technologyreview.com/feed/"),
    ("venturebeat", "https://venturebeat.com/feed/"),
    ("gizmodo", "https://gizmodo.com/feed"),
    ("theregister", "https://www.theregister.com/headlines.atom"),
    # Finance (additional)
    ("fortune", "https://fortune.com/feed/"),
    ("businessinsider", "https://www.businessinsider.com/rss"),
    ("cointelegraph", "https://cointelegraph.com/rss"),
    # Betting (additional)
    ("bettingusa", "https://www.bettingusa.com/feed/"),
    ("vsin", "https://www.vsin.com/feed/"),
    # Science (additional)
    ("livescience", "https://www.livescience.com/feeds/all"),
    ("physorg", "https://phys.org/rss-feed/"),
    ("space", "https://www.space.com/feeds/all"),
    ("scientificamerican", "http://rss.sciam.com/ScientificAmerican-Global"),
    # Entertainment (additional)
    ("rollingstone", "https://www.rollingstone.com/feed/"),
    ("deadline", "https://deadline.com/feed/"),
    ("pitchfork", "https://pitchfork.com/feed/feed-news/rss"),
    ("tmz", "https://www.tmz.com/rss.xml"),
    # Gaming (additional, column: tech)
    ("gamespot", "https://www.gamespot.com/feeds/news/"),
    ("kotaku", "https://kotaku.com/rss"),
    ("pcgamer", "https://www.pcgamer.com/rss/"),
    ("eurogamer", "https://www.eurogamer.net/feed"),
    # DEV / Tech (additional)
    ("devto", "https://dev.to/feed"),
    ("githubblog", "https://github.blog/feed/"),
    ("hackaday", "https://hackaday.com/feed/"),
    ("freecodecamp", "https://www.freecodecamp.org/news/rss/"),
    ("stackoverflow", "https://stackoverflow.blog/feed/"),
    # AI (column: tech)
    ("marktechpost", "https://www.marktechpost.com/feed/"),
    ("thedecoder", "https://the-decoder.com/feed/"),
    # World/News (additional)
    ("independent", "https://www.independent.co.uk/rss"),
    ("euronews", "https://www.euronews.com/rss"),
    ("cbc", "https://www.cbc.ca/webfeed/rss/rss-topstories"),
    ("abcau", "https://www.abc.net.au/news/feed/51120/rss.xml"),
    ("theatlantic", "https://www.theatlantic.com/feed/all/"),
    ("vox", "https://www.vox.com/rss/index.xml"),
    # Crypto (column: finance)
    ("decrypt", "https://decrypt.co/feed"),
    ("theblock", "https://www.theblock.co/rss.xml"),
    ("bitcoinmagazine", "https://bitcoinmagazine.com/feed"),
    # Business (column: finance)
    ("inc", "https://www.inc.com/rss/"),
    # Sports (additional)
    ("sportingnews", "https://www.sportingnews.com/us/rss"),
    ("profootballtalk", "https://profootballtalk.nbcsports.com/feed/"),
    # Movies/TV (column: entertainment)
    ("collider", "https://collider.com/feed/"),
    ("screenrant", "https://screenrant.com/feed/"),
    ("indiewire", "https://www.indiewire.com/feed"),
    # Music (column: entertainment)
    ("stereogum", "https://www.stereogum.com/feed"),
    ("consequence", "https://consequence.net/feed/"),
    # Lifestyle (column: entertainment)
    ("motor1", "https://www.motor1.com/rss/news/all/"),
    ("jalopnik", "https://jalopnik.com/feed"),
    ("eater", "https://www.eater.com/rss/index.xml"),
    ("skift", "https://skift.com/feed/"),
    # News — additional international
    ("wsj", "https://feeds.a.dj.com/rss/RSSWorldNews.xml"),
    ("nypost", "https://nypost.com/feed/"),
    ("latimes", "https://www.latimes.com/world-nation/rss2.0.xml"),
    ("dailymail", "https://www.dailymail.co.uk/articles.rss"),
    ("timesofindia", "https://timesofindia.indiatimes.com/rssfeedstopstories.cms"),
    ("scmp", "https://www.scmp.com/rss/91/feed"),
    ("japantimes", "https://www.japantimes.co.jp/feed/"),
    ("nprpolitics", "https://feeds.npr.org/1014/rss.xml"),
    # Tech — additional outlets
    ("techradar", "https://www.techradar.com/rss"),
    ("tomshardware", "https://www.tomshardware.com/feeds/all"),
    ("cnet", "https://www.cnet.com/rss/news/"),
    ("zdnet", "https://www.zdnet.com/news/rss.xml"),
    ("mashable", "https://mashable.com/feeds/rss/all"),
    ("tnw", "https://thenextweb.com/feed"),
    ("androidauthority", "https://www.androidauthority.com/feed/"),
    ("macrumors", "https://feeds.macrumors.com/MacRumors-All"),
    ("xda", "https://www.xda-developers.com/feed/"),
    # Science — additional outlets
    ("nature", "https://www.nature.com/nature.rss"),
    ("quanta", "https://www.quantamagazine.org/feed/"),
    ("newatlas", "https://newatlas.com/index.rss"),
    ("sciencealert", "https://www.sciencealert.com/feed"),
    # Sports — additional
    ("bbcfootball", "https://feeds.bbci.co.uk/sport/football/rss.xml"),
    ("f1", "https://www.formula1.com/content/fom-website/en/latest/all.xml"),
    # Gaming — additional outlets (column: tech)
    ("nintendolife", "https://www.nintendolife.com/feeds/latest"),
    ("rps", "https://www.rockpapershotgun.com/feed"),
    ("vg247", "https://www.vg247.com/feed"),
    ("destructoid", "https://www.destructoid.com/feed/"),
    # Entertainment — additional
    ("avclub", "https://www.avclub.com/rss"),
    # Finance — additional outlets
    ("investing", "https://www.investing.com/rss/news.rss"),
    ("benzinga", "https://www.benzinga.com/feed"),
    ("kiplinger", "https://www.kiplinger.com/feed/all"),
    # News/Investigative
    ("propublica", "https://www.propublica.org/feeds/propublica/main"),
    ("theintercept", "https://theintercept.com/feed/?rss"),
    ("foreignpolicy", "https://foreignpolicy.com/feed/"),
    ("theconversation", "https://theconversation.com/us/articles.atom"),
    ("straitstimes", "https://www.straitstimes.com/news/world/rss.xml"),
    # Dev
    ("infoq", "https://feed.infoq.com/"),
    ("phoronix", "https://www.phoronix.com/rss.php"),
    ("lwn", "https://lwn.net/headlines/rss"),
    ("hackernoon", "https://hackernoon.com/feed"),
    ("smashing", "https://www.smashingmagazine.com/feed/"),
    ("csstricks", "https://css-tricks.com/feed/"),
    # AI
    ("openai", "https://openai.com/news/rss.xml"),
    ("googleai", "https://blog.google/technology/ai/rss/"),
    ("huggingface", "https://huggingface.co/blog/feed.xml"),
    # Science
    ("smithsonian", "https://www.smithsonianmag.com/rss/latest_articles/"),
    ("popsci", "https://www.popsci.com/feed/"),
    ("universetoday", "https://www.universetoday.com/feed/"),
    # Sports
    ("cyclingnews", "https://www.cyclingnews.com/rss/"),
    ("defector", "https://defector.com/feed"),
    # Entertainment
    ("pagesix", "https://pagesix.com/feed/"),
    ("vanityfair", "https://www.vanityfair.com/feed/rss"),
    ("nme", "https://www.nme.com/feed"),
    # Betting
    ("igamingbusiness", "https://igamingbusiness.com/feed/"),
    ("casinoorg", "https://www.casino.org/news/feed/"),
    ("gamblingnews", "https://www.gamblingnews.com/feed/"),
    # Finance
    ("finextra", "https://www.finextra.com/rss/headlines.aspx"),
    ("fxstreet", "https://www.fxstreet.com/rss/news"),
    # World (additional international)
    ("unnews", "https://news.un.org/feed/subscribe/en/news/all/rss.xml"),
    ("arabnews", "https://www.arabnews.com/rss.xml"),
    ("timesofisrael", "https://www.timesofisrael.com/feed/"),
    ("globalnews", "https://globalnews.ca/feed/"),
    ("smh", "https://www.smh.com.au/rss/feed.xml"),
    # US Politics (column: news)
    ("realclearpolitics", "https://www.realclearpolitics.com/index.xml"),
    ("salon", "https://www.salon.com/feed/"),
    ("reason", "https://reason.com/feed/"),
    ("nationalreview", "https://www.nationalreview.com/feed/"),
    ("motherjones", "https://www.motherjones.com/feed/"),
    # Security (column: tech)
    ("krebs", "https://krebsonsecurity.com/feed/"),
    ("bleepingcomputer", "https://www.bleepingcomputer.com/feed/"),
    ("thehackernews", "https://feeds.feedburner.com/TheHackersNews"),
    ("darkreading", "https://www.darkreading.com/rss.xml"),
    # Tech (additional)
    ("404media", "https://www.404media.co/rss/"),
    ("restofworld", "https://restofworld.org/feed/latest/"),
    ("techdirt", "https://www.techdirt.com/feed/"),
    ("tomsguide", "https://www.tomsguide.com/feeds/all"),
    ("digitaltrends", "https://www.digitaltrends.com/feed/"),
    ("9to5google", "https://9to5google.com/feed/"),
    # Dev (column: tech)
    ("realpython", "https://realpython.com/atom.xml"),
    ("martinfowler", "https://martinfowler.com/feed.atom"),
    # Sports
    ("cricinfo", "https://www.espncricinfo.com/rss/content/story/feeds/0.xml"),
    ("skyf1", "https://www.skysports.com/rss/12433"),
    # Entertainment
    ("slashfilm", "https://www.slashfilm.com/feed/"),
    # Health (column: science)
    ("medicalxpress", "https://medicalxpress.com/rss-feed/"),
    # World — additional international (batch D)
    ("lemonde", "https://www.lemonde.fr/en/rss/une.xml"),
    ("spiegel", "https://www.spiegel.de/international/index.rss"),
    ("thehindu", "https://www.thehindu.com/news/national/feeder/default.rss"),
    ("dawn", "https://www.dawn.com/feeds/home"),
    # Climate (column: science, batch D)
    ("insideclimate", "https://insideclimatenews.org/feed/"),
    ("grist", "https://grist.org/feed/"),
    ("carbonbrief", "https://www.carbonbrief.org/feed/"),
    # Law (column: news, batch D)
    ("scotusblog", "https://www.scotusblog.com/feed/"),
    ("abovethelaw", "https://abovethelaw.com/feed/"),
    # Autos/EV (column: entertainment, batch D)
    ("electrek", "https://electrek.co/feed/"),
    ("carscoops", "https://www.carscoops.com/feed/"),
    ("thedrive", "https://www.thedrive.com/feed"),
    # Aviation/Travel (column: entertainment, batch D)
    ("simpleflying", "https://simpleflying.com/feed/"),
    ("thepointsguy", "https://thepointsguy.com/feed/"),
    # Photo/Design/Books/Ideas (column: entertainment, batch D)
    ("petapixel", "https://petapixel.com/feed/"),
    ("dezeen", "https://www.dezeen.com/feed/"),
    ("lithub", "https://lithub.com/feed/"),
    ("aeon", "https://aeon.co/feed.rss"),
    ("nautilus", "https://nautil.us/feed/"),
    # Esports / Anime / Comics (column: entertainment, batch E)
    ("dexerto", "https://www.dexerto.com/feed/"),
    ("dotesports", "https://dotesports.com/feed"),
    ("animenewsnetwork", "https://www.animenewsnetwork.com/all/rss.xml"),
    ("cbr", "https://www.cbr.com/feed/"),
    # Defense (column: news, batch E)
    ("defensenews", "https://www.defensenews.com/arc/outboundfeeds/rss/"),
    ("breakingdefense", "https://breakingdefense.com/feed/"),
    # Space Industry (column: science, batch E)
    ("spacenews", "https://spacenews.com/feed/"),
    ("nasaspaceflight", "https://www.nasaspaceflight.com/feed/"),
    # Energy / Industry (column: finance, batch E)
    ("oilprice", "https://oilprice.com/rss/main"),
    ("cleantechnica", "https://cleantechnica.com/feed/"),
    ("housingwire", "https://www.housingwire.com/feed/"),
    ("retaildive", "https://www.retaildive.com/feeds/news/"),
    ("crunchbasenews", "https://news.crunchbase.com/feed/"),
    # Education / Outdoors (column: news / entertainment, batch E)
    ("insidehighered", "https://www.insidehighered.com/rss.xml"),
    ("outsideonline", "https://www.outsideonline.com/feed/"),
    # News / international — batch F (18 new)
    ("cnn", "http://rss.cnn.com/rss/cnn_topstories.rss"),
    ("bbcnews", "https://feeds.bbci.co.uk/news/rss.xml"),
    ("bbctech", "https://feeds.bbci.co.uk/news/technology/rss.xml"),
    ("bbcbusiness", "https://feeds.bbci.co.uk/news/business/rss.xml"),
    ("guardiantech", "https://www.theguardian.com/uk/technology/rss"),
    ("guardiansport", "https://www.theguardian.com/sport/rss"),
    ("guardianfilm", "https://www.theguardian.com/film/rss"),
    ("nyttech", "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"),
    ("nytscience", "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml"),
    ("nytarts", "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml"),
    ("wsjtech", "https://feeds.a.dj.com/rss/RSSWSJD.xml"),
    ("wsjmarkets", "https://feeds.a.dj.com/rss/RSSMarketsMain.xml"),
    ("theweek", "https://theweek.com/feed/all"),
    ("fastcompany", "https://www.fastcompany.com/rss"),
    ("slate", "https://slate.com/feeds/all.rss"),
    ("semafor", "https://www.semafor.com/rss.xml"),
    ("newyorker", "https://www.newyorker.com/feed/everything"),
    # Weather / Traffic (batch G)
    ("nhc", "https://www.nhc.noaa.gov/index-at.xml"),
    ("spc", "https://www.spc.noaa.gov/products/spcrss.xml"),
    ("watchers", "https://watchers.news/feed/"),
    ("ukroads", "https://m.highwaysengland.co.uk/feeds/rss/AllEvents.xml"),
    # Culture (column: entertainment, batch H)
    ("boingboing", "https://boingboing.net/feed"),
    ("mentalfloss", "https://www.mentalfloss.com/rss.xml"),
    ("atlasobscura", "https://www.atlasobscura.com/feeds/latest"),
    ("openculture", "https://www.openculture.com/feed"),
    # Ideas / Science (batch H)
    ("bigthink", "https://bigthink.com/feed/"),
    ("skyandtelescope", "https://skyandtelescope.org/feed/"),
    # Finance (batch H)
    ("thestreet", "https://www.thestreet.com/.rss/full/"),
    # Gaming (column: tech, batch H)
    ("gamesradar", "https://www.gamesradar.com/rss/"),
    ("toucharcade", "https://toucharcade.com/feed/"),
    ("siliconera", "https://www.siliconera.com/feed/"),
    # Sports (batch H)
    ("fourfourtwo", "https://www.fourfourtwo.com/rss/"),
    # Asia News (column: news, batch H)
    ("ndtv", "https://feeds.feedburner.com/ndtvnews-top-stories"),
    ("cna", "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml"),
    # Food/Fashion/Home (column: entertainment, batch I)
    ("bonappetit", "https://www.bonappetit.com/feed/rss"),
    ("vogue", "https://www.vogue.com/feed/rss"),
    ("hypebeast", "https://hypebeast.com/feed"),
    ("gq", "https://www.gq.com/feed/rss"),
    ("apartmenttherapy", "https://www.apartmenttherapy.com/main.rss"),
    # Sports (batch I)
    ("runnersworld", "https://www.runnersworld.com/rss/all.xml/"),
    # Engineering Blogs (column: tech, batch I)
    ("changelog", "https://changelog.com/feed"),
    ("mozillahacks", "https://hacks.mozilla.org/feed/"),
    ("cloudflareblog", "https://blog.cloudflare.com/rss/"),
    ("awsblog", "https://aws.amazon.com/blogs/aws/feed/"),
    # Gaming (column: tech, batch I)
    ("pcgamesn", "https://www.pcgamesn.com/mainrss.xml"),
    ("pushsquare", "https://www.pushsquare.com/feeds/latest"),
    ("vgc", "https://www.videogameschronicle.com/feed/"),
    # City/History (batch I)
    ("gothamist", "https://gothamist.com/feed"),
    ("historyextra", "https://www.historyextra.com/feed/"),
    # Media/Marketing (batch J)
    ("niemanlab", "https://www.niemanlab.org/feed/"),
    ("podnews", "https://podnews.net/rss"),
    ("adweek", "https://www.adweek.com/feed/"),
    ("marketingdive", "https://www.marketingdive.com/feeds/news/"),
    # Linux/OSS (column: tech, batch J)
    ("omgubuntu", "https://www.omgubuntu.co.uk/feed"),
    ("itsfoss", "https://itsfoss.com/rss/"),
    ("9to5linux", "https://9to5linux.com/feed"),
    # Platform (column: tech, batch J)
    ("appleinsider", "https://appleinsider.com/rss/news"),
    ("androidcentral", "https://www.androidcentral.com/feed"),
    # Games Industry (column: tech, batch J)
    ("gamesindustry", "https://www.gamesindustry.biz/feed"),
    ("gamedeveloper", "https://www.gamedeveloper.com/rss.xml"),
    # TV/Celeb (column: entertainment, batch J)
    ("tvline", "https://tvline.com/feed/"),
    ("justjared", "https://www.justjared.com/feed/"),
    # News (batch K)
    ("vice", "https://www.vice.com/en/rss"),
    ("dailydot", "https://www.dailydot.com/feed/"),
    ("thenation", "https://www.thenation.com/feed/?post_type=article"),
    # Books/Culture (column: entertainment, batch K)
    ("parisreview", "https://www.theparisreview.org/blog/feed/"),
    # Tech (batch K)
    ("techspot", "https://www.techspot.com/backend.xml"),
    ("liliputing", "https://liliputing.com/feed/"),
    # Motorsport (column: sports, batch K)
    ("autosport", "https://www.autosport.com/rss/feed/all"),
    ("motorsport", "https://www.motorsport.com/rss/all/news/"),
    # Music (column: entertainment, batch K)
    ("loudwire", "https://loudwire.com/feed/"),
    ("brooklynvegan", "https://www.brooklynvegan.com/feed/"),
    # Movies (column: entertainment, batch K)
    ("firstshowing", "https://www.firstshowing.net/feed/"),
    # Science (column: science, batch K)
    ("sciencenews", "https://www.sciencenews.org/feed"),
    ("discovermagazine", "https://www.discovermagazine.com/rss/all"),
    # Health/Sport (batch K)
    ("menshealth", "https://www.menshealth.com/rss/all.xml/"),
    ("sportskeeda", "https://www.sportskeeda.com/feed"),
    # News — regional & international (batch L)
    ("premiumtimes", "https://www.premiumtimesng.com/feed"),
    ("mailguardian", "https://mg.co.za/feed/"),
    # Aviation & Maritime (column: entertainment/finance, batch L)
    ("aerotime", "https://www.aerotime.aero/feed"),
    ("gcaptain", "https://gcaptain.com/feed/"),
    # Logistics (column: finance, batch L)
    # Outdoors & Esports (column: entertainment, batch L)
    ("gearjunkie", "https://gearjunkie.com/feed"),
    ("esportsinsider", "https://esportsinsider.com/feed"),
    # Fashion (column: entertainment, batch L)
    ("wwd", "https://wwd.com/feed/"),
    ("fashionista", "https://fashionista.com/.rss/full/"),
    # Finance (batch M)
    ("qz", "https://qz.com/rss"),
    # NPR verticals (round 17)
    ("nprmusic", "https://feeds.npr.org/1039/rss.xml"),
    ("nprscience", "https://feeds.npr.org/1007/rss.xml"),
    ("nprhealth", "https://feeds.npr.org/1128/rss.xml"),
    ("nprworld", "https://feeds.npr.org/1004/rss.xml"),
    ("nprbusiness", "https://feeds.npr.org/1006/rss.xml"),
    # BBC verticals (round 17)
    ("bbcscience", "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml"),
    (
        "bbcentertainment",
        "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    ),
    ("bbchealth", "https://feeds.bbci.co.uk/news/health/rss.xml"),
    # Guardian verticals (round 17)
    ("guardianus", "https://www.theguardian.com/us-news/rss"),
    ("guardianenvironment", "https://www.theguardian.com/environment/rss"),
    ("guardianscience", "https://www.theguardian.com/science/rss"),
    ("guardianbusiness", "https://www.theguardian.com/business/rss"),
    ("guardianmusic", "https://www.theguardian.com/music/rss"),
    # NYT verticals (round 17)
    ("nytworld", "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"),
    ("nytbusiness", "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml"),
    ("nythealth", "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml"),
    ("nyttravel", "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml"),
    # Entertainment / Blog (batch O)
    ("knowyourmeme", "https://knowyourmeme.com/newsfeed.rss"),
    ("budgetbytes", "https://www.budgetbytes.com/feed/"),
    ("smittenkitchen", "https://smittenkitchen.com/feed/"),
    ("waitbutwhy", "https://waitbutwhy.com/feed"),
    ("farnamstreet", "https://fs.blog/feed/"),
    ("marginalrevolution", "https://marginalrevolution.com/feed"),
    ("astralcodexten", "https://www.astralcodexten.com/feed"),
    # batch S — popular sites with working feeds
    ("theinformation", "https://www.theinformation.com/feed"),
    ("newscientist", "https://www.newscientist.com/feed/home/"),
    ("economist", "https://www.economist.com/latest/rss.xml"),
    ("lifehacker", "https://lifehacker.com/feed/rss"),
    ("daringfireball", "https://daringfireball.net/feeds/main"),
    ("simonwillison", "https://simonwillison.net/atom/everything/"),
    ("codinghorror", "https://blog.codinghorror.com/rss/"),
    ("joelonsoftware", "https://www.joelonsoftware.com/feed/"),
    ("alistapart", "https://alistapart.com/main/feed/"),
    ("webdev", "https://web.dev/feed.xml"),
    ("v8blog", "https://v8.dev/blog.atom"),
    ("goblog", "https://go.dev/blog/feed.atom"),
    ("pythoninsider", "https://blog.python.org/feeds/posts/default"),
    ("nodejsblog", "https://nodejs.org/en/feed/blog.xml"),
    ("kubernetesblog", "https://kubernetes.io/feed.xml"),
    ("hashicorp", "https://www.hashicorp.com/blog/feed.xml"),
    ("gitlabblog", "https://about.gitlab.com/atom.xml"),
    ("deepmind", "https://deepmind.google/blog/rss.xml"),
    ("bair", "https://bair.berkeley.edu/blog/feed.xml"),
    ("thedefiant", "https://thedefiant.io/feed"),
    ("9to5toys", "https://9to5toys.com/feed/"),
    ("macstories", "https://www.macstories.net/feed/"),
    ("stratechery", "https://stratechery.com/feed/"),
    ("spaceflightnow", "https://spaceflightnow.com/feed/"),
    ("eos", "https://eos.org/feed"),
    ("undark", "https://undark.org/feed/"),
    ("spin", "https://www.spin.com/feed/"),
    ("thefader", "https://www.thefader.com/feed"),
    # batch T — international flagship outlets
    ("lefigaro", "https://www.lefigaro.fr/rss/figaro_actualites.xml"),
    ("liberation", "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml"),
    ("derspiegel", "https://www.spiegel.de/schlagzeilen/index.rss"),
    ("zeit", "https://newsfeed.zeit.de/index"),
    ("faz", "https://www.faz.net/rss/aktuell/"),
    ("welt", "https://www.welt.de/feeds/latest.rss"),
    ("elpais", "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"),
    ("elmundo", "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml"),
    ("lavanguardia", "https://www.lavanguardia.com/rss/home.xml"),
    ("corriere", "https://xml2.corriereobjects.it/rss/homepage.xml"),
    ("repubblica", "https://www.repubblica.it/rss/homepage/rss2.0.xml"),
    ("ansa", "https://www.ansa.it/sito/ansait_rss.xml"),
    ("nhkworld", "https://www3.nhk.or.jp/rss/news/cat0.xml"),
    (
        "hindustantimes",
        "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
    ),
    ("folha", "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml"),
    ("globo", "https://pox.globo.com/rss/g1/"),
    ("clarin", "https://www.clarin.com/rss/lo-ultimo/"),
    ("lanacion", "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml"),
    ("moscowtimes", "https://www.themoscowtimes.com/rss/news"),
    ("irishtimes", "https://www.irishtimes.com/cmlink/news-1.1319192"),
    ("thelocal", "https://www.thelocal.com/feeds/rss.php"),
    (
        "aljazeeraar",
        "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9",
    ),
    # batch U — more world outlets
    ("nrk", "https://www.nrk.no/toppsaker.rss"),
    ("aftenposten", "https://www.aftenposten.no/rss"),
    ("svtnyheter", "https://www.svt.se/nyheter/rss.xml"),
    ("dn_se", "https://www.dn.se/rss/"),
    ("hs_fi", "https://www.hs.fi/rss/tuoreimmat.xml"),
    ("yle", "https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss"),
    ("dr_dk", "https://www.dr.dk/nyheder/service/feeds/allenyheder"),
    ("politiken", "https://politiken.dk/rss/senestenyt.rss"),
    ("nos", "https://feeds.nos.nl/nosnieuwsalgemeen"),
    ("nrc", "https://www.nrc.nl/rss/"),
    ("hln", "https://www.hln.be/home/rss.xml"),
    (
        "rtbf",
        "https://rss.rtbf.be/article/rss/highlight_rtbfinfo_info.xml?source=internal",
    ),
    ("wyborcza", "https://rss.gazeta.pl/pub/rss/najnowsze_wyborcza.xml"),
    ("tvn24", "https://tvn24.pl/najnowsze.xml"),
    ("idnes", "https://servis.idnes.cz/rss.aspx?c=zpravodaj"),
    ("denik", "https://www.denik.cz/rss/zpravy.html"),
    ("index_hu", "https://index.hu/24ora/rss/"),
    ("hvg", "https://hvg.hu/rss"),
    ("digi24", "https://www.digi24.ro/rss"),
    ("tovima", "https://www.tovima.gr/feed/"),
    ("milliyet", "https://www.milliyet.com.tr/rss/rssNew/anasayfaRss.xml"),
    ("news24za", "https://feeds.capi24.com/v1/Search/articles/news24/TopStories/rss"),
    ("punchng", "https://rss.punchng.com/v1/category/latest_news"),
    ("jpost", "https://www.jpost.com/rss/rssfeedsfrontpage.aspx"),
    ("bangkokpost", "https://www.bangkokpost.com/rss/data/topstories.xml"),
    ("inquirer", "https://www.inquirer.net/fullfeed"),
    ("rappler", "https://www.rappler.com/feed/"),
    ("vnexpress", "https://vnexpress.net/rss/tin-moi-nhat.rss"),
    ("chinadaily", "https://www.chinadaily.com.cn/rss/china_rss.xml"),
    # batch V — more world outlets
    ("standardmedia", "https://www.standardmedia.co.ke/rss/headlines.php"),
    ("myjoyonline", "https://www.myjoyonline.com/feed/"),
    ("vanguardngr", "https://www.vanguardngr.com/feed/"),
    ("guardianng", "https://guardian.ng/feed/"),
    ("businessday_ng", "https://businessday.ng/feed/"),
    ("egyptindependent", "https://www.egyptindependent.com/feed/"),
    ("eltiempo", "https://www.eltiempo.com/rss/colombia.xml"),
    ("elcomercio_pe", "https://elcomercio.pe/arcio/rss/"),
    ("livemint", "https://www.livemint.com/rss/news"),
    ("thedailystar", "https://www.thedailystar.net/rss.xml"),
    ("tempo_co", "https://rss.tempo.co/nasional"),
    ("tuoitre", "https://tuoitre.vn/rss/tin-moi-nhat.rss"),
    ("gmanews", "https://data.gmanetwork.com/gno/rss/news/feed.xml"),
    ("tehrantimes", "https://www.tehrantimes.com/rss"),
    ("dailysabah", "https://www.dailysabah.com/rssFeed/home"),
    ("indexhr", "https://www.index.hr/rss"),
    ("irishindependent", "https://www.independent.ie/rss/"),
    # batch W — more world outlets
    ("err_ee", "https://www.err.ee/rss"),
    ("delfi_lt", "https://www.delfi.lt/rss/feeds/daily.xml"),
    ("lsm_lv", "https://www.lsm.lv/rss/"),
    ("haberturk", "https://www.haberturk.com/rss"),
    ("sozcu", "https://www.sozcu.com.tr/feeds-rss-category-sondakika"),
    ("n1info", "https://n1info.rs/feed/"),
    ("24sata_hr", "https://www.24sata.hr/feeds/news.xml"),
    ("novinite", "https://www.novinite.com/services/news_rdf.php"),
    ("cyprusmail", "https://cyprus-mail.com/feed/"),
    ("rte_ie", "https://www.rte.ie/feeds/rss/?index=/news/"),
    ("thejournal_ie", "https://www.thejournal.ie/feed/"),
    ("astanatimes", "https://astanatimes.com/feed/"),
    ("kyivpost", "https://www.kyivpost.com/feed"),
    ("ethiopianreporter", "https://www.thereporterethiopia.com/feed/"),
    ("herald_zw", "https://www.herald.co.zw/feed/"),
    ("namibian", "https://www.namibian.com.na/feed/"),
    ("jamaicaobserver", "https://www.jamaicaobserver.com/feed/"),
    ("batimes", "https://www.batimes.com.ar/feed"),
    ("mercopress", "https://en.mercopress.com/rss/"),
    ("rnz", "https://www.rnz.co.nz/rss/national.xml"),
    ("channelnewsasia", "https://www.channelnewsasia.com/rssfeeds/8395986"),
    # batch X — more world outlets
    ("adaderana", "https://www.adaderana.lk/rss.php"),
    ("kathmandupost", "https://kathmandupost.com/rss"),
    ("lemonde_afrique", "https://www.lemonde.fr/afrique/rss_full.xml"),
    ("jeuneafrique", "https://www.jeuneafrique.com/feed/"),
    ("rfi_afrique", "https://www.rfi.fr/fr/afrique/rss"),
    ("actucameroun", "https://actucameroun.com/feed/"),
    ("lusakatimes", "https://www.lusakatimes.com/feed/"),
    ("elnacional_ve", "https://www.elnacional.com/feed/"),
    ("prensalibre", "https://www.prensalibre.com/feed/"),
    ("papuanewguinea_post", "https://www.postcourier.com.pg/feed/"),
    # batch Y — regional papers (IN/US/BR/ID)
    ("freepressjournal", "https://www.freepressjournal.in/stories.rss"),
    ("nytimes_us", "https://rss.nytimes.com/services/xml/rss/nyt/US.xml"),
    ("bostonglobe", "https://www.bostonglobe.com/rss/bigpicture"),
    ("startribune", "https://www.startribune.com/rss/"),
    ("oregonlive", "https://www.oregonlive.com/arc/outboundfeeds/rss/"),
    ("g1globo2", "https://g1.globo.com/rss/g1/economia/"),
    ("uol", "https://rss.uol.com.br/feed/noticias.xml"),
    ("terra_br", "https://www.terra.com.br/rss/"),
    ("tribunnews", "https://www.tribunnews.com/rss"),
    ("antaranews", "https://www.antaranews.com/rss/terkini"),
    ("cnnindonesia", "https://www.cnnindonesia.com/rss"),
    ("republika", "https://www.republika.co.id/rss"),
    # batch Z — regional papers (DE/ES/MX/NG)
    ("sueddeutsche", "https://rss.sueddeutsche.de/rss/Topthemen"),
    ("tagesschau", "https://www.tagesschau.de/index~rss2.xml"),
    ("ntv_de", "https://www.n-tv.de/rss"),
    ("bild", "https://www.bild.de/feed/alles.xml"),
    ("handelsblatt", "https://www.handelsblatt.com/contentexport/feed/schlagzeilen"),
    ("taz", "https://taz.de/!p4608;rss/"),
    ("tagesspiegel", "https://www.tagesspiegel.de/contentexport/feed/home"),
    ("wdr", "https://www1.wdr.de/uebersicht-100.feed"),
    ("abc_es", "https://www.abc.es/rss/2.0/portada/"),
    ("20minutos", "https://www.20minutos.es/rss/"),
    ("elconfidencial", "https://rss.elconfidencial.com/espana/"),
    ("eldiario_es", "https://www.eldiario.es/rss/"),
    ("jornada", "https://www.jornada.com.mx/rss/edicion.xml"),
    ("reforma", "https://www.reforma.com/rss/portada.xml"),
    ("dailytrust", "https://dailytrust.com/feed/"),
    ("leadership_ng", "https://leadership.ng/feed/"),
    ("legit_ng", "https://www.legit.ng/rss/all.rss"),
    # batch AA — regional papers (FR/IT/JP/KR)
    ("20minutes_fr", "https://www.20minutes.fr/feeds/rss-une.xml"),
    ("leparisien", "https://feeds.leparisien.fr/leparisien/rss"),
    ("ouestfrance", "https://www.ouest-france.fr/rss-en-continu.xml"),
    ("nouvelobs", "https://www.nouvelobs.com/rss.xml"),
    ("mediapart", "https://www.mediapart.fr/articles/feed"),
    ("lexpress", "https://www.lexpress.fr/rss/alaune.xml"),
    ("francetvinfo", "https://www.francetvinfo.fr/titres.rss"),
    ("ledauphine", "https://www.ledauphine.com/rss"),
    ("ilfattoquotidiano", "https://www.ilfattoquotidiano.it/feed/"),
    ("ilsole24ore", "https://www.ilsole24ore.com/rss/italia.xml"),
    ("ilgiornale", "https://www.ilgiornale.it/feed.xml"),
    ("ilmessaggero", "https://www.ilmessaggero.it/rss/home.xml"),
    ("gazzetta", "https://www.gazzetta.it/rss/home.xml"),
    ("tgcom24", "https://www.tgcom24.mediaset.it/rss/homepage.xml"),
    ("nhk_news", "https://www.nhk.or.jp/rss/news/cat0.xml"),
    ("japantoday", "https://japantoday.com/feed"),
    ("tokyoreporter", "https://www.tokyoreporter.com/feed/"),
    ("yonhap", "https://en.yna.co.kr/RSS/news.xml"),
    ("hankyoreh", "https://www.hani.co.kr/rss/"),
    ("donga", "https://rss.donga.com/total.xml"),
    ("kbs_world", "https://world.kbs.co.kr/rss/rss_news.htm?lang=e"),
    ("mk_co_kr", "https://www.mk.co.kr/rss/30000001/"),
    # batch AB — Arabic-world papers
    ("asharqalawsat", "https://aawsat.com/feed"),
    ("alquds", "https://www.alquds.co.uk/feed/"),
    ("almasryalyoum", "https://www.almasryalyoum.com/rss/rssfeeds"),
    ("youm7", "https://www.youm7.com/rss/SectionRss?SectionID=65"),
    ("hespress", "https://www.hespress.com/feed"),
    ("tsa_algerie", "https://www.tsa-algerie.com/feed/"),
    ("echoroukonline", "https://www.echoroukonline.com/feed"),
    ("annahar", "https://www.annahar.com/rss"),
    ("ajel", "https://ajel.sa/rss"),
    ("skynewsarabia", "https://www.skynewsarabia.com/web/rss"),
    ("cnnarabic", "https://arabic.cnn.com/api/v1/rss/rss.xml"),
    # batch AC — Chinese-world papers
    ("peopledaily", "http://www.people.com.cn/rss/politics.xml"),
    ("xinhua_cn", "http://www.xinhuanet.com/politics/news_politics.xml"),
    ("globaltimes", "https://www.globaltimes.cn/rss/outbrain.xml"),
    ("sixthtone", "https://www.sixthtone.com/rss"),
    ("mingpao", "https://news.mingpao.com/rss/pns/s00001.xml"),
    ("orientaldaily", "https://orientaldaily.on.cc/rss/news.xml"),
    ("scmp_china", "https://www.scmp.com/rss/318208/feed"),
    ("libertytimes", "https://news.ltn.com.tw/rss/all.xml"),
    ("udn", "https://udn.com/rssfeed/news/2/6638"),
    ("ettoday", "https://feeds.feedburner.com/ettoday/realtime"),
    ("cna_tw", "https://feeds.feedburner.com/rsscna/intworld"),
    ("hk_rthk", "https://rthk.hk/rthk/news/rss/c_expressnews_clocal.xml"),
    ("rfa_cantonese", "https://www.rfa.org/cantonese/rss2.xml"),
    # batch AD — African papers
    ("news24_za2", "https://feeds.24.com/articles/news24/TopStories/rss"),
    ("citizen_za", "https://www.citizen.co.za/feed/"),
    ("nairametrics", "https://nairametrics.com/feed/"),
    ("peoples_gazette", "https://gazettengr.com/feed/"),
    ("dailypost_ng", "https://dailypost.ng/feed/"),
    ("nation_africa", "https://nation.africa/kenya/rss.xml"),
    ("capitalfm_ke", "https://www.capitalfm.co.ke/news/feed/"),
    ("tuko", "https://www.tuko.co.ke/rss/all.rss"),
    ("ethiopianmonitor", "https://ethiopianmonitor.com/feed/"),
    ("newzimbabwe", "https://www.newzimbabwe.com/feed/"),
    ("mg_africa", "https://mg.co.za/section/africa/feed/"),
    ("theafricareport", "https://www.theafricareport.com/feed/"),
    ("africanews", "https://www.africanews.com/feed/rss"),
    ("allafrica", "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf"),
    # batch AE — E.Europe/CIS + LatAm papers
    ("unian", "https://rss.unian.net/site/news_eng.rss"),
    ("pravda_ua", "https://www.pravda.com.ua/rss/"),
    ("rp_pl", "https://www.rp.pl/rss_main"),
    ("onet_pl", "https://wiadomosci.onet.pl/.feed"),
    ("interia_pl", "https://fakty.interia.pl/feed"),
    ("novinky_cz", "https://www.novinky.cz/rss"),
    ("aktualne_cz", "https://zpravy.aktualne.cz/rss/"),
    ("sme_sk", "https://www.sme.sk/rss-title"),
    ("dennikn", "https://dennikn.sk/feed/"),
    ("24ur_si", "https://www.24ur.com/rss"),
    ("hotnews_ro", "https://www.hotnews.ro/rss"),
    ("g4media", "https://www.g4media.ro/feed"),
    ("dnevnik_bg", "https://www.dnevnik.bg/rss/"),
    ("meduza", "https://meduza.io/rss/all"),
    ("rbc_ua", "https://www.rbc.ua/static/rss/all.rus.rss.xml"),
    ("tass", "https://tass.com/rss/v2.xml"),
    ("ambito", "https://www.ambito.com/rss/pages/home.xml"),
    ("elcomercio_ec", "https://www.elcomercio.com/feed/"),
    ("elpais_uy", "https://www.elpais.com.uy/rss/"),
    ("elsalvador_com", "https://www.elsalvador.com/feed/"),
    # batch AF — S/SE Asia papers
    ("ndtv_world", "https://feeds.feedburner.com/ndtvnews-world-news"),
    ("indiatoday", "https://www.indiatoday.in/rss/home"),
    ("deccanchronicle", "https://www.deccanchronicle.com/google_feeds.xml"),
    ("thebusinessstandard_bd", "https://www.tbsnews.net/rss.xml"),
    ("tribune_pk", "https://tribune.com.pk/feed/home"),
    ("geo_tv", "https://www.geo.tv/rss/1/53"),
    ("thenews_pk", "https://www.thenews.com.pk/rss/1/1"),
    ("arynews", "https://arynews.tv/feed/"),
    ("colombotelegraph", "https://www.colombotelegraph.com/index.php/feed/"),
    ("onlinekhabar", "https://english.onlinekhabar.com/feed"),
    ("thanhniennews", "https://thanhnien.vn/rss/home.rss"),
    ("khaosod", "https://www.khaosodenglish.com/feed/"),
    ("malaymail", "https://www.malaymail.com/feed/rss/malaysia"),
    ("freemalaysiatoday", "https://www.freemalaysiatoday.com/feed/"),
    ("mothership", "https://mothership.sg/feed/"),
    ("philstar", "https://www.philstar.com/rss/headlines"),
    # batch AG — sports/finance/tech verticals
    ("skysports_f1", "https://www.skysports.com/rss/12040"),
    ("the42", "https://www.the42.ie/feed/"),
    ("tennisworldusa", "https://www.tennisworldusa.org/rss/news.php"),
    ("mmafighting", "https://www.mmafighting.com/rss/index.xml"),
    ("sbnation", "https://www.sbnation.com/rss/index.xml"),
    ("marca_en", "https://www.marca.com/en/rss/portada.xml"),
    ("investing_com", "https://www.investing.com/rss/news.rss"),
    ("seekingalpha", "https://seekingalpha.com/feed.xml"),
    ("ft_companies", "https://www.ft.com/companies?format=rss"),
    ("zerohedge", "https://feeds.feedburner.com/zerohedge/feed"),
    ("theblock_crypto", "https://www.theblock.co/rss.xml"),
    ("bankless", "https://www.bankless.com/rss/feed"),
    ("techmeme", "https://www.techmeme.com/feed.xml"),
    ("thurrott", "https://www.thurrott.com/feed"),
    ("androidpolice", "https://www.androidpolice.com/feed/"),
    ("krebsonsecurity", "https://krebsonsecurity.com/feed/"),
    ("thenewstack", "https://thenewstack.io/feed/"),
    # batch AH — gaming/science/climate/health/autos
    ("ign_games", "https://feeds.ign.com/ign/games-all"),
    ("rockpapershotgun", "https://www.rockpapershotgun.com/feed"),
    ("gamasutra", "https://www.gamedeveloper.com/rss.xml"),
    ("purexbox", "https://www.purexbox.com/feeds/latest"),
    ("inverse", "https://www.inverse.com/rss"),
    ("climatehome", "https://www.climatechangenews.com/feed/"),
    ("medpagetoday", "https://www.medpagetoday.com/rss/headlines.xml"),
    ("kffhealth", "https://kffhealthnews.org/feed/"),
    ("thetruthaboutcars", "https://www.thetruthaboutcars.com/feed/"),
    ("insideevs", "https://insideevs.com/rss/news/all/"),
    # batch AI — podcasts + newsletters
    ("pod_uptofirst", "https://www.npr.org/rss/podcast.php?id=510318"),
    ("pod_planetmoney", "https://feeds.npr.org/510289/podcast.xml"),
    ("pod_radiolab", "https://feeds.simplecast.com/EmVW7VGp"),
    ("pod_hardfork", "https://feeds.simplecast.com/l2i9YnTd"),
    ("pod_acquired", "https://feeds.transistor.fm/acquired"),
    ("pod_lex", "https://lexfridman.com/feed/podcast/"),
    ("pod_hubermanlab", "https://feeds.megaphone.fm/hubermanlab"),
    ("pod_allin", "https://allinchamathjason.libsyn.com/rss"),
    ("pod_smartless", "https://feeds.simplecast.com/hNaFxXpO"),
    ("pod_darknetdiaries", "https://feeds.megaphone.fm/darknetdiaries"),
    ("nl_pragmaticengineer", "https://newsletter.pragmaticengineer.com/feed"),
    ("nl_platformer", "https://www.platformer.news/rss/"),
    ("nl_lenny", "https://www.lennysnewsletter.com/feed"),
    (
        "nl_money_stuff",
        "https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss",
    ),
    ("nl_noahpinion", "https://www.noahpinion.blog/feed"),
    ("nl_culturestudy", "https://annehelen.substack.com/feed"),
    ("nl_theargument", "https://www.slowboring.com/feed"),
    ("nl_bigtechnology", "https://www.bigtechnology.com/feed"),
    ("nl_importai", "https://importai.substack.com/feed"),
    ("nl_benedictevans", "https://www.ben-evans.com/benedictevans?format=rss"),
    ("nl_tldr", "https://tldr.tech/api/rss/tech"),
    ("nl_thedownload", "https://www.technologyreview.com/feed/"),
    # batch AJ — more podcasts + newsletters
    ("pod_thetalkshow", "https://daringfireball.net/thetalkshow/rss"),
    ("pod_atp", "https://atp.fm/rss"),
    ("pod_econtalk", "https://feeds.simplecast.com/wgl4xEgL"),
    ("pod_99pi", "https://feeds.simplecast.com/BqbsxVfO"),
    ("pod_crimejunkie", "https://feeds.simplecast.com/qm_9xx0g"),
    ("pod_thismortallife", "https://feeds.thisamericanlife.org/talpodcast"),
    ("pod_pod_save_america", "https://feeds.simplecast.com/dxZsm5kX"),
    ("pod_globalnews_bbc", "https://podcasts.files.bbci.co.uk/p02nq0gn.rss"),
    ("nl_thefp", "https://www.thefp.com/feed"),
    ("nl_tangle", "https://www.readtangle.com/feed"),
    ("nl_thegeneralist", "https://www.generalist.com/feed"),
    ("nl_notboring", "https://www.notboring.co/feed"),
    ("nl_thediff", "https://www.thediff.co/feed"),
    ("nl_dense_discovery", "https://www.densediscovery.com/feed/"),
    ("nl_jamesclear", "https://jamesclear.com/feed"),
    ("nl_dailycoin", "https://dailycoin.com/feed/"),
    # batch AK — more world outlets
    ("thelocal_de", "https://www.thelocal.de/feeds/rss.php"),
    ("thelocal_fr", "https://www.thelocal.fr/feeds/rss.php"),
    ("spainenglish", "https://www.thelocal.es/feeds/rss.php"),
    ("portugalnews", "https://www.theportugalnews.com/rss"),
    ("greekreporter", "https://greekreporter.com/feed/"),
    ("balkaninsight", "https://balkaninsight.com/feed/"),
    ("intellinews", "https://www.intellinews.com/feed"),
    (
        "thenationalae",
        "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml",
    ),
    ("middleeasteye", "https://www.middleeasteye.net/rss"),
    ("al_monitor", "https://www.al-monitor.com/rss"),
    ("businesstoday_in", "https://www.businesstoday.in/rssfeeds/?id=home"),
    ("stuff_nz", "https://www.stuff.co.nz/rss"),
    ("theconversation_au", "https://theconversation.com/au/articles.atom"),
    ("crikey", "https://www.crikey.com.au/feed/"),
    ("thewest_au", "https://thewest.com.au/rss"),
    # batch AL — US/UK/CA + global affairs
    ("apnews_world", "https://feedx.net/rss/ap.xml"),
    ("upi", "https://rss.upi.com/news/news.rss"),
    ("csmonitor", "https://rss.csmonitor.com/feeds/all"),
    ("theroot", "https://www.theroot.com/rss"),
    ("thenation_us", "https://www.thenation.com/feed/?post_type=article"),
    ("thedispatch", "https://thedispatch.com/feed/"),
    ("washingtonexaminer", "https://www.washingtonexaminer.com/feed"),
    ("independent_uk", "https://www.independent.co.uk/news/uk/rss"),
    ("metro_uk", "https://metro.co.uk/feed/"),
    ("inews_uk", "https://inews.co.uk/feed"),
    ("thecanary", "https://www.thecanary.co/feed/"),
    ("thenational_scot", "https://www.thenational.scot/news/rss/"),
    ("walesonline", "https://www.walesonline.co.uk/?service=rss"),
    ("nationalpost", "https://nationalpost.com/feed/"),
    ("torontostar", "https://www.thestar.com/search/?f=rss"),
    ("financialpost", "https://financialpost.com/feed/"),
    ("thetyee", "https://thetyee.ca/rss2.xml"),
    ("abcnews_intl", "https://abcnews.go.com/abcnews/internationalheadlines"),
    ("themarkup", "https://themarkup.org/feeds/rss.xml"),
    ("restofworld2", "https://restofworld.org/feed/latest/"),
    ("thenewhumanitarian", "https://www.thenewhumanitarian.org/rss.xml"),
    ("foreignaffairs", "https://www.foreignaffairs.com/rss.xml"),
    ("diplomat", "https://thediplomat.com/feed/"),
    ("warontherocks", "https://warontherocks.com/feed/"),
    # batch AM — AU/India-tech/Caribbean/LatAm-English
    ("theage_au", "https://www.theage.com.au/rss/feed.xml"),
    ("brisbanetimes", "https://www.brisbanetimes.com.au/rss/feed.xml"),
    ("watoday", "https://www.watoday.com.au/rss/feed.xml"),
    ("9news_au", "https://www.9news.com.au/rss"),
    ("sbs_au", "https://www.sbs.com.au/news/feed"),
    ("theguardian_au", "https://www.theguardian.com/australia-news/rss"),
    ("michaelwest", "https://michaelwest.com.au/feed/"),
    ("thespinoff", "https://thespinoff.co.nz/feed"),
    ("newsroom_nz", "https://www.newsroom.co.nz/feed"),
    ("thewire_science", "https://science.thewire.in/feed/"),
    ("theken", "https://the-ken.com/feed/"),
    ("yourstory", "https://yourstory.com/feed"),
    ("inc42", "https://inc42.com/feed/"),
    ("medianama", "https://www.medianama.com/feed/"),
    ("jamaicagleaner", "https://jamaica-gleaner.com/feed/rss.xml"),
    ("dominicantoday", "https://dominicantoday.com/feed/"),
    ("riotimesonline", "https://www.riotimesonline.com/feed/"),
    ("colombiaone", "https://colombiaone.com/feed/"),
    ("mexiconewsdaily", "https://mexiconewsdaily.com/feed/"),
    ("buenosairesherald", "https://buenosairesherald.com/feed"),
    ("santiagotimes", "https://santiagotimes.cl/feed/"),
    ("peruviantimes", "https://www.peruviantimes.com/feed/"),
    # batch AN — US/UK/EU regionals + Japan
    ("chicagosuntimes", "https://chicago.suntimes.com/feed"),
    ("houstonchronicle", "https://www.houstonchronicle.com/rss/feed/News-270.php"),
    ("nola", "https://www.nola.com/search/?f=rss"),
    ("themanchester", "https://www.manchestereveningnews.co.uk/?service=rss"),
    ("liverpoolecho", "https://www.liverpoolecho.co.uk/?service=rss"),
    ("birminghammail", "https://www.birminghammail.co.uk/?service=rss"),
    ("yorkshirepost", "https://www.yorkshirepost.co.uk/rss"),
    ("heraldscotland", "https://www.heraldscotland.com/news/rss/"),
    ("belfasttelegraph", "https://www.belfasttelegraph.co.uk/rss/"),
    ("mdr_de", "https://www.mdr.de/nachrichten/index-rss.xml"),
    ("stuttgarter", "https://www.stuttgarter-zeitung.de/news.rss.feed"),
    ("nicematin", "https://www.nicematin.com/rss"),
    ("sudouest", "https://www.sudouest.fr/rss.xml"),
    ("ladepeche", "https://www.ladepeche.fr/rss.xml"),
    ("ilgazzettino", "https://www.ilgazzettino.it/rss/home.xml"),
    ("quotidiano_net", "https://www.quotidiano.net/rss/homepage.xml"),
    ("soranews24", "https://soranews24.com/feed/"),
    # batch AO — Africa-tech/Pacific/Caribbean
    ("techcabal", "https://techcabal.com/feed/"),
    ("techpoint_africa", "https://techpoint.africa/feed/"),
    ("disrupt_africa", "https://disrupt-africa.com/feed/"),
    ("ventureburn", "https://ventureburn.com/feed/"),
    ("moneyweb", "https://www.moneyweb.co.za/feed/"),
    ("fin24", "https://feeds.24.com/articles/fin24/rss"),
    ("the_independent_ug", "https://www.independent.co.ug/feed/"),
    ("malawi24", "https://malawi24.com/feed/"),
    ("zambianbusinesstimes", "https://zambianbusinesstimes.com/feed/"),
    ("postzambia", "https://www.daily-mail.co.zm/feed/"),
    ("rnz_pacific", "https://www.rnz.co.nz/rss/pacific.xml"),
    ("matangitonga", "https://matangitonga.to/rss.xml"),
    ("caymancompass", "https://www.caymancompass.com/feed/"),
    ("barbadostoday", "https://barbadostoday.bb/feed/"),
    ("stluciatimes", "https://stluciatimes.com/feed/"),
    ("antiguaobserver", "https://antiguaobserver.com/feed/"),
    ("newsday_tt", "https://newsday.co.tt/feed/"),
    # batch AP — Iberian/LatAm-es/DE-tech/CH-AT/FR-intl
    ("expansion_es", "https://e00-expansion.uecdn.es/rss/portada.xml"),
    ("eldiario_ar", "https://www.eldiarioar.com/rss/"),
    ("elcolombiano", "https://www.elcolombiano.com/rss/portada.xml"),
    (
        "elpais_america",
        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada",
    ),
    ("observador_pt", "https://observador.pt/feed/"),
    ("sapo_pt", "https://www.sapo.pt/rss"),
    ("record_pt", "https://www.record.pt/rss/"),
    ("businessinsider_es", "https://www.businessinsider.es/rss"),
    ("xataka", "https://www.xataka.com/index.xml"),
    ("genbeta", "https://www.genbeta.com/index.xml"),
    ("elespanol", "https://www.elespanol.com/rss/"),
    ("heise_de", "https://www.heise.de/rss/heise.rdf"),
    ("golem_de", "https://rss.golem.de/rss.php?feed=RSS2.0"),
    ("t3n_de", "https://t3n.de/rss.xml"),
    ("derstandard_at", "https://www.derstandard.at/rss"),
    ("20min_ch", "https://partner-feeds.20min.ch/rss/20minuten"),
    ("nzz", "https://www.nzz.ch/recent.rss"),
    ("lemonde_diplo", "https://www.monde-diplomatique.fr/recents.xml"),
    ("rfi_en", "https://www.rfi.fr/en/rss"),
    ("france24_en", "https://www.france24.com/en/rss"),
    # batch AQ — Nordic/Dutch/Belgian/tech
    ("vg_no", "https://www.vg.no/rss/feed/"),
    ("e24_no", "https://e24.no/rss"),
    ("expressen", "https://feeds.expressen.se/nyheter/"),
    ("aftonbladet", "https://www.aftonbladet.se/rss.xml"),
    ("di_se", "https://www.di.se/rss"),
    ("iltalehti", "https://www.iltalehti.fi/rss/uutiset.xml"),
    ("is_fi", "https://www.is.fi/rss/tuoreimmat.xml"),
    ("berlingske", "https://www.berlingske.dk/content/rss"),
    ("volkskrant", "https://www.volkskrant.nl/voorpagina/rss.xml"),
    ("telegraaf", "https://www.telegraaf.nl/rss"),
    ("ad_nl", "https://www.ad.nl/home/rss.xml"),
    ("nu_nl", "https://www.nu.nl/rss"),
    ("demorgen", "https://www.demorgen.be/rss.xml"),
    ("tweakers", "https://feeds.feedburner.com/tweakers/mixed"),
    ("quartz", "https://qz.com/rss"),
    ("arstechnicaSci", "https://arstechnica.com/science/feed/"),
    ("techxplore", "https://techxplore.com/rss-feed/"),
    # batch AR — anime/gaming/tech/crypto niches
    ("comicbook", "https://comicbook.com/feed/"),
    ("gamerant", "https://gamerant.com/feed/"),
    ("thegamer", "https://www.thegamer.com/feed/"),
    ("nintendoeverything", "https://nintendoeverything.com/feed/"),
    ("automaton_west", "https://automaton-media.com/en/feed/"),
    ("gematsu", "https://www.gematsu.com/feed"),
    ("windowscentral", "https://www.windowscentral.com/feeds/all"),
    ("neowin", "https://www.neowin.net/news/rss/"),
    ("howtogeek", "https://www.howtogeek.com/feed/"),
    ("makeuseof", "https://www.makeuseof.com/feed/"),
    ("imore", "https://www.imore.com/feeds/all"),
    ("gsmarena", "https://www.gsmarena.com/rss-news-reviews.php3"),
    ("bgr", "https://bgr.com/feed/"),
    ("slashgear", "https://www.slashgear.com/feed/"),
    ("pcworld", "https://www.pcworld.com/feed"),
    ("cryptoslate", "https://cryptoslate.com/feed/"),
    ("beincrypto", "https://beincrypto.com/feed/"),
    ("cryptobriefing", "https://cryptobriefing.com/feed/"),
    ("protos", "https://protos.com/feed/"),
    ("dlnews", "https://www.dlnews.com/arc/outboundfeeds/rss/"),
    ("blockworks", "https://blockworks.co/feed"),
    # batch AS — food/health/lifestyle/design/trade
    ("thekitchn", "https://www.thekitchn.com/main.rss"),
    ("delish", "https://www.delish.com/rss/all.xml/"),
    ("selfmag", "https://www.self.com/feed/rss"),
    ("womenshealth", "https://www.womenshealthmag.com/rss/all.xml/"),
    ("romper", "https://www.romper.com/rss"),
    ("archdaily", "https://www.archdaily.com/rss/"),
    ("designboom", "https://www.designboom.com/feed/"),
    ("core77", "https://www.core77.com/feed"),
    ("creativebloq", "https://www.creativebloq.com/feeds/all"),
    ("highsnobiety", "https://www.highsnobiety.com/feed/"),
    ("marketingweek", "https://www.marketingweek.com/feed/"),
    ("supplychaindive", "https://www.supplychaindive.com/feeds/news/"),
    ("hrdive", "https://www.hrdive.com/feeds/news/"),
    # batch AT — science/research
    ("smithsonianmag", "https://www.smithsonianmag.com/rss/latest_articles/"),
    ("spectrum_ieee", "https://spectrum.ieee.org/feeds/feed.rss"),
    ("mit_news", "https://news.mit.edu/rss/feed"),
    ("knowable", "https://knowablemagazine.org/rss"),
    # batch AU — trade/security/Industry Dive
    ("theverge_full", "https://www.theverge.com/rss/full.xml"),
    ("kotaku_au", "https://www.kotaku.com.au/feed/"),
    ("techradar_pro", "https://www.techradar.com/pro/rss"),
    ("itpro", "https://www.itpro.com/feeds/all"),
    ("computerworld", "https://www.computerworld.com/feed"),
    ("infoworld", "https://www.infoworld.com/feed"),
    ("cio", "https://www.cio.com/feed"),
    ("securityweek", "https://feeds.feedburner.com/securityweek"),
    ("threatpost", "https://threatpost.com/feed/"),
    ("therecord_media", "https://therecord.media/feed/"),
    ("sifted", "https://sifted.eu/feed"),
    ("tech_eu", "https://tech.eu/feed/"),
    ("techfundingnews", "https://techfundingnews.com/feed/"),
    ("crunchbase_news", "https://news.crunchbase.com/feed/"),
    ("pymnts", "https://www.pymnts.com/feed/"),
    ("bankingdive", "https://www.bankingdive.com/feeds/news/"),
    ("cfodive", "https://www.cfodive.com/feeds/news/"),
    ("utilitydive", "https://www.utilitydive.com/feeds/news/"),
    ("healthcaredive", "https://www.healthcaredive.com/feeds/news/"),
    ("ciodive", "https://www.ciodive.com/feeds/news/"),
    ("restaurantdive", "https://www.restaurantdive.com/feeds/news/"),
    ("k12dive", "https://www.k12dive.com/feeds/news/"),
    # batch AV — philosophy/quotes feeds
    ("themarginalian", "https://www.themarginalian.org/feed/"),
    ("dailystoic_feed", "https://dailystoic.com/feed/"),
    ("brainyquote", "https://www.brainyquote.com/link/quotebr.rss"),
    # batch AY — investigative/science/aviation/logistics
    ("the19th", "https://19thnews.org/feed/"),
    ("themarshallproject", "https://www.themarshallproject.org/rss/recent.rss"),
    ("mississippitoday", "https://mississippitoday.org/feed/"),
    ("chalkbeat", "https://www.chalkbeat.org/arc/outboundfeeds/rss/"),
    ("the74", "https://www.the74million.org/feed/"),
    ("sciencebasednews", "https://sciencebasedmedicine.org/feed/"),
    ("endpts", "https://endpts.com/feed/"),
    ("fiercebiotech", "https://www.fiercebiotech.com/rss/xml"),
    ("fiercepharma", "https://www.fiercepharma.com/rss/xml"),
    ("medcitynews", "https://medcitynews.com/feed/"),
    ("chemengonline", "https://www.chemengonline.com/feed/"),
    ("aviationweek", "https://aviationweek.com/rss.xml"),
    ("flightglobal", "https://www.flightglobal.com/rss/"),
    ("theloadstar", "https://theloadstar.com/feed/"),
    # batch AZ — legal/defense/space-weather/art/music
    ("jurist", "https://www.jurist.org/news/feed/"),
    ("courthousenews", "https://www.courthousenews.com/feed/"),
    ("fedscoop", "https://fedscoop.com/feed/"),
    ("statescoop", "https://statescoop.com/feed/"),
    ("militarytimes", "https://www.militarytimes.com/arc/outboundfeeds/rss/"),
    ("thedrive_warzone", "https://www.twz.com/feed"),
    ("severe_weather_eu", "https://www.severe-weather.eu/feed/"),
    ("watchers_news", "https://watchers.news/feed/"),
    ("earthsky", "https://earthsky.org/feed/"),
    ("artnews", "https://www.artnews.com/feed/"),
    ("artnet", "https://news.artnet.com/feed"),
    ("hyperallergic", "https://hyperallergic.com/feed/"),
    ("theartnewspaper", "https://www.theartnewspaper.com/rss.xml"),
    ("colossal", "https://www.thisiscolossal.com/feed/"),
    ("metalinjection", "https://metalinjection.net/feed"),
    ("jambase", "https://www.jambase.com/feed"),
    # batch BA — thinktank/agri/energy/fashion/auto
    ("csis", "https://www.csis.org/rss.xml"),
    ("bruegel", "https://www.bruegel.org/rss.xml"),
    ("project_syndicate", "https://www.project-syndicate.org/rss"),
    ("theconversation_us", "https://theconversation.com/us/articles.atom"),
    ("modernfarmer", "https://modernfarmer.com/feed/"),
    ("fooddive", "https://www.fooddive.com/feeds/news/"),
    ("agfundernews", "https://agfundernews.com/feed"),
    ("pv_magazine", "https://www.pv-magazine.com/feed/"),
    ("businessoffashion", "https://www.businessoffashion.com/feed/"),
    ("vogue_runway", "https://www.vogue.com/feed/rss"),
    ("roadandtrack", "https://www.roadandtrack.com/rss/all.xml/"),
    ("caranddriver", "https://www.caranddriver.com/rss/all.xml/"),
    ("hagerty", "https://www.hagerty.com/media/feed/"),
    # batch BB — realestate/travel/satire/books
    ("bisnow", "https://www.bisnow.com/rss"),
    ("curbed", "https://www.curbed.com/rss/index.xml"),
    ("thebabylonbee", "https://babylonbee.com/feed"),
    ("theonion", "https://theonion.com/feed/"),
    ("theparisreview", "https://www.theparisreview.org/blog/feed/"),
    ("kirkusreviews", "https://www.kirkusreviews.com/feeds/rss/"),
    ("bookriot", "https://bookriot.com/feed/"),
    ("tordotcom", "https://reactormag.com/feed/"),
    ("techinasia", "https://www.techinasia.com/feed"),
    # batch BC — opinion/political magazines
    ("the_conversation_uk", "https://theconversation.com/uk/articles.atom"),
    ("opendemocracy", "https://www.opendemocracy.net/en/feed/"),
    ("jacobin", "https://jacobin.com/feed"),
    ("unherd", "https://unherd.com/feed/"),
    ("persuasion", "https://www.persuasion.community/feed"),
    ("spiked", "https://www.spiked-online.com/feed/"),
    ("americanconservative", "https://www.theamericanconservative.com/feed/"),
    ("newrepublic", "https://newrepublic.com/rss.xml"),
    ("commondreams", "https://www.commondreams.org/feeds/news.rss"),
    ("truthout", "https://truthout.org/feed/"),
    ("alternet", "https://www.alternet.org/feeds/feed.rss"),
    ("rawstory", "https://www.rawstory.com/feeds/feed.rss"),
    # batch BD — longform/media-industry/film
    ("futurism", "https://futurism.com/feed"),
    ("psyche", "https://psyche.co/feed.rss"),
    ("narratively", "https://narratively.com/feed/"),
    ("cjr", "https://www.cjr.org/feed"),
    ("mediaite", "https://www.mediaite.com/feed/"),
    ("thewrap", "https://www.thewrap.com/feed/"),
    ("nofilmschool", "https://nofilmschool.com/rss.xml"),
    ("soundonsound", "https://www.soundonsound.com/rss.xml"),
    # batch BE — dev blogs
    ("linuxjournal", "https://www.linuxjournal.com/node/feed"),
    ("dev_to", "https://dev.to/feed"),
    ("logrocket", "https://blog.logrocket.com/feed/"),
    ("rust_blog", "https://blog.rust-lang.org/feed.xml"),
    ("cncf", "https://www.cncf.io/feed/"),
    ("stackoverflow_blog", "https://stackoverflow.blog/feed/"),
    ("github_blog", "https://github.blog/feed/"),
    # batch BF — trade/biz-school/design
    ("constructiondive", "https://www.constructiondive.com/feeds/news/"),
    ("manufacturingdive", "https://www.manufacturingdive.com/feeds/news/"),
    ("packagingdive", "https://www.packagingdive.com/feeds/news/"),
    ("wastedive", "https://www.wastedive.com/feeds/news/"),
    ("legaldive", "https://www.legaldive.com/feeds/news/"),
    ("biopharmadive", "https://www.biopharmadive.com/feeds/news/"),
    ("medtechdive", "https://www.medtechdive.com/feeds/news/"),
    ("hotelmanagement", "https://www.hotelmanagement.net/rss.xml"),
    ("chiefexecutive", "https://chiefexecutive.net/feed/"),
    ("hbswk", "https://hbswk.hbs.edu/rss/all.xml"),
    ("knowledge_wharton", "https://knowledge.wharton.upenn.edu/feed/"),
    ("sloanreview", "https://sloanreview.mit.edu/feed/"),
    ("fastcompany_design", "https://www.fastcompany.com/co-design/rss"),
    ("designmilk", "https://design-milk.com/feed/"),
    ("yankodesign", "https://www.yankodesign.com/feed/"),
    # batch BG — gov agencies + science journals
    ("nasa_breaking", "https://www.nasa.gov/rss/dyn/breaking_news.rss"),
    ("who_news", "https://www.who.int/rss-feeds/news-english.xml"),
    ("esa_news", "https://www.esa.int/rssfeed/Our_Activities/Space_News"),
    ("sec_news", "https://www.sec.gov/news/pressreleases.rss"),
    ("federalreserve_press", "https://www.federalreserve.gov/feeds/press_all.xml"),
    ("un_news", "https://news.un.org/feed/subscribe/en/news/all/rss.xml"),
    ("reliefweb", "https://reliefweb.int/updates/rss.xml"),
    ("plos", "https://journals.plos.org/plosone/feed/atom"),
    ("arxiv_cs", "http://export.arxiv.org/rss/cs"),
    ("phys_arxiv", "http://export.arxiv.org/rss/physics"),
    # batch BH — university research news
    ("harvard_gazette", "https://news.harvard.edu/gazette/feed/"),
    ("berkeley_news", "https://news.berkeley.edu/feed"),
    ("caltech_news", "https://www.caltech.edu/about/news/rss"),
    ("upenn_news", "https://penntoday.upenn.edu/rss.xml"),
    ("jhu_hub", "https://hub.jhu.edu/feed/"),
    ("umich_news", "https://news.umich.edu/feed/"),
    ("gatech_news", "https://news.gatech.edu/rss.xml"),
    ("utexas_news", "https://news.utexas.edu/feed/"),
    ("sciencedaily_top", "https://www.sciencedaily.com/rss/top/science.xml"),
    # batch BI — more universities
    ("washington_news", "https://www.washington.edu/news/feed/"),
    ("wisc_news", "https://news.wisc.edu/feed/"),
    ("illinois_news", "https://news.illinois.edu/rss/"),
    ("manchester_uni", "https://www.manchester.ac.uk/discover/news/feed/"),
    ("cnrs", "https://news.cnrs.fr/rss"),
    ("csic", "https://www.csic.es/en/rss.xml"),
]


def _register(source_id: str, url: str) -> None:
    """Register a parse_rss getter for *url* under *source_id*.

    Parameters are captured by value so the closure is correct even
    though we iterate over ``_FEEDS`` in a loop.
    """

    async def _getter() -> list[NewsItem]:
        items = parse_rss(await fetch_text(url))
        if not items:
            raise NewsFetchError(f"Cannot fetch rss data for {source_id}")
        return items

    register(source_id, _getter)


for _source_id, _url in _FEEDS:
    _register(_source_id, _url)
