"""Reddit — hot posts via RSS (one module, one hundred and seventy-nine channels).

Reddit's JSON API returns 403 for non-authenticated requests; the Atom
RSS feed at /r/{sub}/hot.rss returns 200 with a browser User-Agent,
which the shared fetch client already sends.
"""

from ..fetch import NewsFetchError, fetch_text, parse_rss
from ..registry import register
from ..schemas import NewsItem

_CHANNELS: list[tuple[str, str]] = [  # (subreddit_name, source_id)
    ("popular", "reddit-popular"),
    ("technology", "reddit-technology"),
    ("worldnews", "reddit-worldnews"),
    ("news", "reddit-news"),
    ("programming", "reddit-programming"),
    ("science", "reddit-science"),
    ("gaming", "reddit-gaming"),
    ("movies", "reddit-movies"),
    ("sports", "reddit-sports"),
    ("wallstreetbets", "reddit-wallstreetbets"),
    ("Music", "reddit-music"),
    ("AskReddit", "reddit-askreddit"),
    ("todayilearned", "reddit-todayilearned"),
    ("space", "reddit-space"),
    ("nba", "reddit-nba"),
    ("nfl", "reddit-nfl"),
    ("soccer", "reddit-soccer"),
    ("CryptoCurrency", "reddit-cryptocurrency"),
    ("Futurology", "reddit-futurology"),
    ("politics", "reddit-politics"),
    ("television", "reddit-television"),
    ("books", "reddit-books"),
    ("history", "reddit-history"),
    ("gadgets", "reddit-gadgets"),
    ("personalfinance", "reddit-personalfinance"),
    ("Fitness", "reddit-fitness"),
    ("food", "reddit-food"),
    ("MachineLearning", "reddit-machinelearning"),
    ("Bitcoin", "reddit-bitcoin"),
    ("stocks", "reddit-stocks"),
    ("webdev", "reddit-webdev"),
    ("apple", "reddit-apple"),
    ("Android", "reddit-android"),
    ("pcgaming", "reddit-pcgaming"),
    ("formula1", "reddit-formula1"),
    ("baseball", "reddit-baseball"),
    ("hockey", "reddit-hockey"),
    ("MMA", "reddit-mma"),
    # batch C — 8 new
    ("dataisbeautiful", "reddit-dataisbeautiful"),
    ("Damnthatsinteresting", "reddit-damnthatsinteresting"),
    ("explainlikeimfive", "reddit-explainlikeimfive"),
    ("LifeProTips", "reddit-lifeprotips"),
    ("UpliftingNews", "reddit-upliftingnews"),
    ("nottheonion", "reddit-nottheonion"),
    ("Documentaries", "reddit-documentaries"),
    ("OutOfTheLoop", "reddit-outoftheloop"),
    # batch D — 10 new
    ("Economics", "reddit-economics"),
    ("energy", "reddit-energy"),
    ("cybersecurity", "reddit-cybersecurity"),
    ("artificial", "reddit-artificial"),
    ("OpenAI", "reddit-openai"),
    ("selfhosted", "reddit-selfhosted"),
    ("homelab", "reddit-homelab"),
    ("buildapc", "reddit-buildapc"),
    ("Games", "reddit-games"),
    ("aviation", "reddit-aviation"),
    # batch E — 8 new
    ("leagueoflegends", "reddit-leagueoflegends"),
    ("Minecraft", "reddit-minecraft"),
    ("photography", "reddit-photography"),
    ("Cooking", "reddit-cooking"),
    ("travel", "reddit-travel"),
    ("running", "reddit-running"),
    ("anime", "reddit-anime"),
    ("architecture", "reddit-architecture"),
    # batch F — 10 new
    ("europe", "reddit-europe"),
    ("canada", "reddit-canada"),
    ("unitedkingdom", "reddit-unitedkingdom"),
    ("australia", "reddit-australia"),
    ("askscience", "reddit-askscience"),
    ("Physics", "reddit-physics"),
    ("Python", "reddit-python"),
    ("rust", "reddit-rust"),
    ("golang", "reddit-golang"),
    ("javascript", "reddit-javascript"),
    # batch G — weather & transport
    ("weather", "reddit-weather"),
    ("TropicalWeather", "reddit-tropicalweather"),
    ("flying", "reddit-flying"),
    ("trains", "reddit-trains"),
    # batch H — sports & personal finance
    ("CFB", "reddit-cfb"),
    ("CollegeBasketball", "reddit-collegebasketball"),
    ("tennis", "reddit-tennis"),
    ("golf", "reddit-golf"),
    ("Boxing", "reddit-boxing"),
    ("Cricket", "reddit-cricket"),
    ("RealEstate", "reddit-realestate"),
    ("smallbusiness", "reddit-smallbusiness"),
    ("startups", "reddit-startups"),
    ("Frugal", "reddit-frugal"),
    # batch I — city, home & garden
    ("nyc", "reddit-nyc"),
    ("LosAngeles", "reddit-losangeles"),
    ("london", "reddit-london"),
    ("chicago", "reddit-chicago"),
    ("toronto", "reddit-toronto"),
    ("DIY", "reddit-diy"),
    ("gardening", "reddit-gardening"),
    ("woodworking", "reddit-woodworking"),
    ("HomeImprovement", "reddit-homeimprovement"),
    # batch J — finance & dev
    ("Entrepreneur", "reddit-entrepreneur"),
    ("investing", "reddit-investing"),
    ("options", "reddit-options"),
    ("dividends", "reddit-dividends"),
    ("financialindependence", "reddit-financialindependence"),
    ("cscareerquestions", "reddit-cscareerquestions"),
    ("ExperiencedDevs", "reddit-experienceddevs"),
    ("devops", "reddit-devops"),
    ("kubernetes", "reddit-kubernetes"),
    ("aws", "reddit-aws"),
    # batch K — sysadmin, data, academic, misc
    ("sysadmin", "reddit-sysadmin"),
    ("networking", "reddit-networking"),
    ("datascience", "reddit-datascience"),
    ("dataengineering", "reddit-dataengineering"),
    ("math", "reddit-math"),
    ("biology", "reddit-biology"),
    ("chemistry", "reddit-chemistry"),
    ("Astronomy", "reddit-astronomy"),
    ("AskEngineers", "reddit-askengineers"),
    ("coolguides", "reddit-coolguides"),
    # batch L — OS, mobile, philosophy, productivity
    ("linux", "reddit-linux"),
    ("windows", "reddit-windows"),
    ("mac", "reddit-mac"),
    ("iphone", "reddit-iphone"),
    ("SteamDeck", "reddit-steamdeck"),
    ("philosophy", "reddit-philosophy"),
    ("AskHistorians", "reddit-askhistorians"),
    ("productivity", "reddit-productivity"),
    # batch M — EV & maker (round 17)
    ("teslamotors", "reddit-teslamotors"),
    ("electricvehicles", "reddit-electricvehicles"),
    ("3Dprinting", "reddit-3dprinting"),
    ("homeautomation", "reddit-homeautomation"),
    # batch N — creative & lifestyle (round 18)
    ("gamedev", "reddit-gamedev"),
    ("blender", "reddit-blender"),
    ("Art", "reddit-art"),
    ("web_design", "reddit-webdesign"),
    ("digitalnomad", "reddit-digitalnomad"),
    ("nutrition", "reddit-nutrition"),
    ("Meditation", "reddit-meditation"),
    ("languagelearning", "reddit-languagelearning"),
    # batch O — memes & misc (round 19)
    ("memes", "reddit-memes"),
    ("ProgrammerHumor", "reddit-programmerhumor"),
    ("wholesomememes", "reddit-wholesomememes"),
    ("Showerthoughts", "reddit-showerthoughts"),
    ("quotes", "reddit-quotes"),
    ("recipes", "reddit-recipes"),
    # batch P — curiosity & discovery (round 20)
    ("interestingasfuck", "reddit-interestingasfuck"),
    ("oddlysatisfying", "reddit-oddlysatisfying"),
    ("mildlyinteresting", "reddit-mildlyinteresting"),
    ("BeAmazed", "reddit-beamazed"),
    ("AskCulinary", "reddit-askculinary"),
    ("suggestmeabook", "reddit-suggestmeabook"),
    ("MovieSuggestions", "reddit-moviesuggestions"),
    ("technews", "reddit-technews"),
    # batch Q — culture & leisure (round 21)
    ("AskHistory", "reddit-askhistory"),
    ("TrueFilm", "reddit-truefilm"),
    ("indiegaming", "reddit-indiegaming"),
    ("podcasts", "reddit-podcasts"),
    ("audiobooks", "reddit-audiobooks"),
    ("retrogaming", "reddit-retrogaming"),
    ("vinyl", "reddit-vinyl"),
    ("hiking", "reddit-hiking"),
    # batch R — hobbies & science (round 22)
    ("robotics", "reddit-robotics"),
    ("drones", "reddit-drones"),
    ("Archaeology", "reddit-archaeology"),
    ("Paleontology", "reddit-paleontology"),
    ("geography", "reddit-geography"),
    ("Fantasy", "reddit-fantasy"),
    ("scifi", "reddit-scifi"),
    ("boardgames", "reddit-boardgames"),
    # batch S — education & learning (round 23)
    ("learnprogramming", "reddit-learnprogramming"),
    ("learnpython", "reddit-learnpython"),
    ("learnmachinelearning", "reddit-learnmachinelearning"),
    ("college", "reddit-college"),
    ("GradSchool", "reddit-gradschool"),
    ("ApplyingToCollege", "reddit-applyingtocollege"),
    # batch T — personal finance & wellness (round 24)
    ("Bogleheads", "reddit-bogleheads"),
    ("getdisciplined", "reddit-getdisciplined"),
    ("decidingtobebetter", "reddit-decidingtobebetter"),
    ("Mindfulness", "reddit-mindfulness"),
    ("EatCheapAndHealthy", "reddit-eatcheapandhealthy"),
    ("MealPrepSunday", "reddit-mealprepsunday"),
    # batch AV — more subreddits + themed (tarot/religion/philosophy)
    ("NatureIsFuckingLit", "reddit-natureisfuckinglit"),
    ("Awwducational", "reddit-awwducational"),
    ("explainlikeimfive", "reddit-eli5"),
    ("YouShouldKnow", "reddit-youshouldknow"),
    ("MapPorn", "reddit-mapporn"),
    ("HistoryPorn", "reddit-historyporn"),
    ("OldSchoolCool", "reddit-oldschoolcool"),
    ("india", "reddit-india"),
    ("ukpolitics", "reddit-ukpolitics"),
    ("PoliticalDiscussion", "reddit-politicaldiscussion"),
    ("geopolitics", "reddit-geopolitics"),
    ("environment", "reddit-environment"),
    ("climate", "reddit-climate"),
    ("collapse", "reddit-collapse"),
    ("EverythingScience", "reddit-everythingscience"),
    ("medicine", "reddit-medicine"),
    ("psychology", "reddit-psychology"),
    ("writing", "reddit-writing"),
    ("manga", "reddit-manga"),
    ("kpop", "reddit-kpop"),
    ("hiphopheads", "reddit-hiphopheads"),
    ("indieheads", "reddit-indieheads"),
    ("electronicmusic", "reddit-electronicmusic"),
    ("ethereum", "reddit-ethereum"),
    ("tarot", "reddit-tarot"),
    ("Christianity", "reddit-christianity"),
    ("islam", "reddit-islam"),
    ("Buddhism", "reddit-buddhism"),
    ("spirituality", "reddit-spirituality"),
    ("bible", "reddit-bible"),
    ("religion", "reddit-religion"),
    ("Stoicism", "reddit-stoicism"),
    ("hinduism", "reddit-hinduism"),
    ("Judaism", "reddit-judaism"),
    ("occult", "reddit-occult"),
    # batch AW — more subreddits
    ("mildlyinfuriating", "reddit-mildlyinfuriating"),
    ("nextfuckinglevel", "reddit-nextfuckinglevel"),
    ("HumansBeingBros", "reddit-humansbeingbros"),
    ("facepalm", "reddit-facepalm"),
    ("PublicFreakout", "reddit-publicfreakout"),
    ("AbsoluteUnits", "reddit-absoluteunits"),
    ("educationalgifs", "reddit-educationalgifs"),
    ("toptalent", "reddit-toptalent"),
    ("nevertellmetheodds", "reddit-nevertellmetheodds"),
    ("ThatsInsane", "reddit-thatsinsane"),
    ("Outdoors", "reddit-outdoors"),
    ("camping", "reddit-camping"),
    ("backpacking", "reddit-backpacking"),
    ("solotravel", "reddit-solotravel"),
    ("itookapicture", "reddit-itookapicture"),
    ("EarthPorn", "reddit-earthporn"),
    ("cityporn", "reddit-cityporn"),
    ("bodyweightfitness", "reddit-bodyweightfitness"),
    ("mealprep", "reddit-mealprep"),
    # batch AX — tech/gaming subreddits
    ("pcmasterrace", "reddit-pcmasterrace"),
    ("hardware", "reddit-hardware"),
    ("raspberry_pi", "reddit-raspberrypi"),
    ("arduino", "reddit-arduino"),
    ("electronics", "reddit-electronics"),
    ("mechanicalkeyboards", "reddit-mechanicalkeyboards"),
    ("ios", "reddit-ios"),
    ("firefox", "reddit-firefox"),
    ("chrome", "reddit-chrome"),
    ("linux_gaming", "reddit-linuxgaming"),
    ("ps5", "reddit-ps5"),
    ("xboxseriesx", "reddit-xboxseriesx"),
    ("NintendoSwitch", "reddit-nintendoswitch"),
    ("steam", "reddit-steam2"),
    ("patientgamers", "reddit-patientgamers"),
    ("truegaming", "reddit-truegaming"),
    ("tabletopgaming", "reddit-tabletopgaming"),
    ("DnD", "reddit-dnd"),
    ("rpg", "reddit-rpg"),
    ("MagicTCG", "reddit-magictcg"),
    ("pokemon", "reddit-pokemon"),
    ("Genshin_Impact", "reddit-genshinimpact"),
    ("DotA2", "reddit-dota2"),
    ("Overwatch", "reddit-overwatch"),
    ("GlobalOffensive", "reddit-globaloffensive"),
    ("VALORANT", "reddit-valorant"),
    ("FortNiteBR", "reddit-fortnite"),
]


def _make_getter(sub: str, source_id: str) -> None:
    """Register a getter for r/{sub}/hot.rss under the given source id.

    Captures ``sub`` and ``source_id`` as parameters so the closure is
    correct even though we iterate over ``_CHANNELS`` in a loop.
    """
    _url = f"https://www.reddit.com/r/{sub}/hot.rss"

    async def _getter() -> list[NewsItem]:
        items = parse_rss(await fetch_text(_url))
        if not items:
            raise NewsFetchError(f"Cannot fetch rss data for r/{sub}")
        return items

    register(source_id, _getter)


for _sub, _source_id in _CHANNELS:
    _make_getter(_sub, _source_id)

# Public mapping from source_id -> subreddit name, preserving original casing
# (e.g. "reddit-askhistorians" -> "AskHistorians").  Consumed by the endpoint
# layer to decide whether a non-hot sort should fetch an alternative RSS URL.
REDDIT_SUBS: dict[str, str] = {source_id: sub for sub, source_id in _CHANNELS}
