"""initial

Revision ID: b8c6b4cffbb5
Revises:
Create Date: 2026-10-03 22:39:42.364839

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "b8c6b4cffbb5"
down_revision = None
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    public_uuid_ossp = PGExtension(schema="public", signature="uuid-ossp")
    op.create_entity(public_uuid_ossp)

    public_citext = PGExtension(schema="public", signature="citext")
    op.create_entity(public_citext)

    public_pg_trgm = PGExtension(schema="public", signature="pg_trgm")
    op.create_entity(public_pg_trgm)

    op.create_table(
        "email_logs",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("processor", sa.String(), nullable=False),
        sa.Column("processor_id", sa.String(), nullable=True),
        sa.Column("to_email_addr", sa.String(), nullable=False),
        sa.Column("from_email_addr", sa.String(), nullable=False),
        sa.Column("from_name", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("email_template", sa.String(), nullable=True),
        sa.Column(
            "email_props", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("deduplication_key", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("email_logs_pkey")),
    )
    op.create_index(
        op.f("ix_email_logs_created_at"), "email_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_email_logs_deduplication_key",
        "email_logs",
        ["deduplication_key"],
        unique=False,
        postgresql_where="deduplication_key IS NOT NULL",
    )
    op.create_index(
        op.f("ix_email_logs_deleted_at"), "email_logs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_email_template"),
        "email_logs",
        ["email_template"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_logs_processor_id"), "email_logs", ["processor_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_status"), "email_logs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_to_email_addr"),
        "email_logs",
        ["to_email_addr"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "accepted_terms_of_service_at", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("accepted_terms_of_service_ip", sa.String(), nullable=True),
        sa.Column("blocked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(
        "ix_users_email_case_insensitive",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "authentication_sessions",
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("step", sa.SmallInteger(), nullable=False),
        sa.Column(
            "authentication_method_references",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "used_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("identity_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["users.id"],
            name=op.f("authentication_sessions_identity_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("authentication_sessions_pkey")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("authentication_sessions_token_hash_key")
        ),
    )
    op.create_index(
        op.f("ix_authentication_sessions_created_at"),
        "authentication_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentication_sessions_deleted_at"),
        "authentication_sessions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentication_sessions_expires_at"),
        "authentication_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentication_sessions_identity_id"),
        "authentication_sessions",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "backup_codes_enrollments",
        sa.Column(
            "codes_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "used_codes_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["users.id"],
            name=op.f("backup_codes_enrollments_identity_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("backup_codes_enrollments_pkey")),
        sa.UniqueConstraint(
            "identity_id", name=op.f("backup_codes_enrollments_identity_id_key")
        ),
    )
    op.create_index(
        op.f("ix_backup_codes_enrollments_created_at"),
        "backup_codes_enrollments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backup_codes_enrollments_deleted_at"),
        "backup_codes_enrollments",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "email_verification",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("email_verification_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_verification_pkey")),
    )
    op.create_index(
        op.f("ix_email_verification_created_at"),
        "email_verification",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_deleted_at"),
        "email_verification",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_expires_at"),
        "email_verification",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_token_hash"),
        "email_verification",
        ["token_hash"],
        unique=False,
    )
    op.create_table(
        "launches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("tagline", sa.String(length=140), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("logo_path", sa.String(length=512), nullable=True),
        sa.Column("kicker", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("state", sa.Unicode(), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("day", sa.Date(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("launches_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("launches_pkey")),
    )
    op.create_index(
        op.f("ix_launches_created_at"), "launches", ["created_at"], unique=False
    )
    op.create_index(
        "ix_launches_day_position",
        "launches",
        ["day", "position"],
        unique=True,
        postgresql_where="state IN ('approved', 'live')",
    )
    op.create_index(
        op.f("ix_launches_deleted_at"), "launches", ["deleted_at"], unique=False
    )
    op.create_index("ix_launches_state_day", "launches", ["state", "day"], unique=False)
    op.create_index(op.f("ix_launches_user_id"), "launches", ["user_id"], unique=False)
    op.create_table(
        "oauth2_authorization_codes",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("sub_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("nonce", sa.Text(), nullable=True),
        sa.Column("auth_time", sa.Integer(), nullable=False),
        sa.Column("acr", sa.Text(), nullable=True),
        sa.Column("amr", sa.Text(), nullable=True),
        sa.Column("code_challenge", sa.Text(), nullable=True),
        sa.Column("code_challenge_method", sa.String(length=48), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("oauth2_authorization_codes_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth2_authorization_codes_pkey")),
        sa.UniqueConstraint("code", name=op.f("oauth2_authorization_codes_code_key")),
    )
    op.create_index(
        op.f("ix_oauth2_authorization_codes_created_at"),
        "oauth2_authorization_codes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_authorization_codes_deleted_at"),
        "oauth2_authorization_codes",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "oauth2_clients",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("client_secret_hash_v2", sa.String(length=80), nullable=True),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "registration_access_token_hash_v2", sa.String(length=80), nullable=True
        ),
        sa.Column("registration_access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("first_party", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("rate_limit_group", sa.Unicode(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("client_id_issued_at", sa.Integer(), nullable=False),
        sa.Column("client_secret_expires_at", sa.Integer(), nullable=False),
        sa.Column("client_metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("oauth2_clients_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth2_clients_pkey")),
        sa.UniqueConstraint("client_id", name=op.f("oauth2_clients_client_id_key")),
    )
    op.create_index(
        op.f("ix_oauth2_clients_client_secret_hash_v2"),
        "oauth2_clients",
        ["client_secret_hash_v2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_clients_created_at"),
        "oauth2_clients",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_clients_deleted_at"),
        "oauth2_clients",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_clients_registration_access_token_hash_v2"),
        "oauth2_clients",
        ["registration_access_token_hash_v2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_clients_user_id"), "oauth2_clients", ["user_id"], unique=False
    )
    op.create_table(
        "oauth2_grants",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("oauth2_grants_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth2_grants_pkey")),
        sa.UniqueConstraint(
            "client_id", "user_id", name=op.f("oauth2_grants_client_id_user_id_key")
        ),
    )
    op.create_index(
        op.f("ix_oauth2_grants_client_id"), "oauth2_grants", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_oauth2_grants_created_at"),
        "oauth2_grants",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_grants_deleted_at"),
        "oauth2_grants",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_grants_user_id"), "oauth2_grants", ["user_id"], unique=False
    )
    op.create_table(
        "oauth2_states",
        sa.Column("state_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("code_verifier", sa.String(), nullable=True),
        sa.Column("nonce", sa.String(), nullable=True),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("identity_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["users.id"],
            name=op.f("oauth2_states_identity_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth2_states_pkey")),
        sa.UniqueConstraint("state_hash", name=op.f("oauth2_states_state_hash_key")),
    )
    op.create_index(
        op.f("ix_oauth2_states_created_at"),
        "oauth2_states",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_states_deleted_at"),
        "oauth2_states",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_states_expires_at"),
        "oauth2_states",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_states_identity_id"),
        "oauth2_states",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "oauth2_tokens",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("nonce", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("token_type", sa.String(length=40), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.Integer(), nullable=False),
        sa.Column("access_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("refresh_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("sub_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("oauth2_tokens_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth2_tokens_pkey")),
        sa.UniqueConstraint(
            "access_token", name=op.f("oauth2_tokens_access_token_key")
        ),
    )
    op.create_index(
        op.f("ix_oauth2_tokens_created_at"),
        "oauth2_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth2_tokens_deleted_at"),
        "oauth2_tokens",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_oauth2_tokens_expires_at",
        "oauth2_tokens",
        [sa.literal_column("(issued_at + expires_in)")],
        unique=False,
        postgresql_where=sa.text(
            "refresh_token IS NULL OR refresh_token_revoked_at != 0"
        ),
    )
    op.create_index(
        op.f("ix_oauth2_tokens_nonce"), "oauth2_tokens", ["nonce"], unique=False
    )
    op.create_index(
        op.f("ix_oauth2_tokens_refresh_token"),
        "oauth2_tokens",
        ["refresh_token"],
        unique=False,
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_token_expires_at", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.String(length=320), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=False),
        sa.Column("account_username", sa.String(length=320), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("oauth_accounts_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth_accounts_pkey")),
        sa.UniqueConstraint(
            "platform",
            "account_id",
            name=op.f("oauth_accounts_platform_account_id_key"),
        ),
    )
    op.create_index(
        "idx_user_id_platform", "oauth_accounts", ["user_id", "platform"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_accounts_created_at"),
        "oauth_accounts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_accounts_deleted_at"),
        "oauth_accounts",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "reader_prefs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("reader_prefs_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reader_prefs_pkey")),
        sa.UniqueConstraint("user_id", "key", name="uq_reader_pref"),
    )
    op.create_index(
        op.f("ix_reader_prefs_created_at"), "reader_prefs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reader_prefs_deleted_at"), "reader_prefs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_reader_prefs_user_id"), "reader_prefs", ["user_id"], unique=False
    )
    op.create_table(
        "totp_enrollments",
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("secret", sa.CHAR(length=32), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.Column("code_length", sa.SmallInteger(), nullable=False),
        sa.Column("time_step", sa.Integer(), nullable=False),
        sa.Column("last_verified_time_step", sa.Integer(), nullable=True),
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["users.id"],
            name=op.f("totp_enrollments_identity_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("totp_enrollments_pkey")),
        sa.UniqueConstraint(
            "identity_id", name=op.f("totp_enrollments_identity_id_key")
        ),
    )
    op.create_index(
        op.f("ix_totp_enrollments_created_at"),
        "totp_enrollments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_totp_enrollments_deleted_at"),
        "totp_enrollments",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "user_followed_sources",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_followed_sources_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_followed_sources_pkey")),
        sa.UniqueConstraint("user_id", "source_id", name="uq_user_followed_source"),
    )
    op.create_index(
        op.f("ix_user_followed_sources_created_at"),
        "user_followed_sources",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_followed_sources_deleted_at"),
        "user_followed_sources",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_followed_sources_user_id"),
        "user_followed_sources",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("token_v2", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Unicode()), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_sessions_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_sessions_pkey")),
        sa.UniqueConstraint("token_v2", name=op.f("user_sessions_token_v2_key")),
    )
    op.create_index(
        op.f("ix_user_sessions_created_at"),
        "user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_deleted_at"),
        "user_sessions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"),
        "user_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "email_otps",
        sa.Column("code_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("identity_id", sa.Uuid(), nullable=True),
        sa.Column("authentication_session_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["authentication_session_id"],
            ["authentication_sessions.id"],
            name=op.f("email_otps_authentication_session_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["users.id"],
            name=op.f("email_otps_identity_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_otps_pkey")),
    )
    op.create_index(
        op.f("ix_email_otps_authentication_session_id"),
        "email_otps",
        ["authentication_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_otps_code_hash"), "email_otps", ["code_hash"], unique=True
    )
    op.create_index(
        op.f("ix_email_otps_created_at"), "email_otps", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_otps_deleted_at"), "email_otps", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_otps_expires_at"), "email_otps", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_otps_identity_id"), "email_otps", ["identity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_otps_identity_id"), table_name="email_otps")
    op.drop_index(op.f("ix_email_otps_expires_at"), table_name="email_otps")
    op.drop_index(op.f("ix_email_otps_deleted_at"), table_name="email_otps")
    op.drop_index(op.f("ix_email_otps_created_at"), table_name="email_otps")
    op.drop_index(op.f("ix_email_otps_code_hash"), table_name="email_otps")
    op.drop_index(
        op.f("ix_email_otps_authentication_session_id"), table_name="email_otps"
    )
    op.drop_table("email_otps")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_deleted_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_created_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(
        op.f("ix_user_followed_sources_user_id"), table_name="user_followed_sources"
    )
    op.drop_index(
        op.f("ix_user_followed_sources_deleted_at"), table_name="user_followed_sources"
    )
    op.drop_index(
        op.f("ix_user_followed_sources_created_at"), table_name="user_followed_sources"
    )
    op.drop_table("user_followed_sources")
    op.drop_index(op.f("ix_totp_enrollments_deleted_at"), table_name="totp_enrollments")
    op.drop_index(op.f("ix_totp_enrollments_created_at"), table_name="totp_enrollments")
    op.drop_table("totp_enrollments")
    op.drop_index(op.f("ix_reader_prefs_user_id"), table_name="reader_prefs")
    op.drop_index(op.f("ix_reader_prefs_deleted_at"), table_name="reader_prefs")
    op.drop_index(op.f("ix_reader_prefs_created_at"), table_name="reader_prefs")
    op.drop_table("reader_prefs")
    op.drop_index(op.f("ix_oauth_accounts_deleted_at"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_created_at"), table_name="oauth_accounts")
    op.drop_index("idx_user_id_platform", table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_oauth2_tokens_refresh_token"), table_name="oauth2_tokens")
    op.drop_index(op.f("ix_oauth2_tokens_nonce"), table_name="oauth2_tokens")
    op.drop_index(
        "ix_oauth2_tokens_expires_at",
        table_name="oauth2_tokens",
        postgresql_where=sa.text(
            "refresh_token IS NULL OR refresh_token_revoked_at != 0"
        ),
    )
    op.drop_index(op.f("ix_oauth2_tokens_deleted_at"), table_name="oauth2_tokens")
    op.drop_index(op.f("ix_oauth2_tokens_created_at"), table_name="oauth2_tokens")
    op.drop_table("oauth2_tokens")
    op.drop_index(op.f("ix_oauth2_states_identity_id"), table_name="oauth2_states")
    op.drop_index(op.f("ix_oauth2_states_expires_at"), table_name="oauth2_states")
    op.drop_index(op.f("ix_oauth2_states_deleted_at"), table_name="oauth2_states")
    op.drop_index(op.f("ix_oauth2_states_created_at"), table_name="oauth2_states")
    op.drop_table("oauth2_states")
    op.drop_index(op.f("ix_oauth2_grants_user_id"), table_name="oauth2_grants")
    op.drop_index(op.f("ix_oauth2_grants_deleted_at"), table_name="oauth2_grants")
    op.drop_index(op.f("ix_oauth2_grants_created_at"), table_name="oauth2_grants")
    op.drop_index(op.f("ix_oauth2_grants_client_id"), table_name="oauth2_grants")
    op.drop_table("oauth2_grants")
    op.drop_index(op.f("ix_oauth2_clients_user_id"), table_name="oauth2_clients")
    op.drop_index(
        op.f("ix_oauth2_clients_registration_access_token_hash_v2"),
        table_name="oauth2_clients",
    )
    op.drop_index(op.f("ix_oauth2_clients_deleted_at"), table_name="oauth2_clients")
    op.drop_index(op.f("ix_oauth2_clients_created_at"), table_name="oauth2_clients")
    op.drop_index(
        op.f("ix_oauth2_clients_client_secret_hash_v2"), table_name="oauth2_clients"
    )
    op.drop_table("oauth2_clients")
    op.drop_index(
        op.f("ix_oauth2_authorization_codes_deleted_at"),
        table_name="oauth2_authorization_codes",
    )
    op.drop_index(
        op.f("ix_oauth2_authorization_codes_created_at"),
        table_name="oauth2_authorization_codes",
    )
    op.drop_table("oauth2_authorization_codes")
    op.drop_index(op.f("ix_launches_user_id"), table_name="launches")
    op.drop_index("ix_launches_state_day", table_name="launches")
    op.drop_index(op.f("ix_launches_deleted_at"), table_name="launches")
    op.drop_index(
        "ix_launches_day_position",
        table_name="launches",
        postgresql_where="state IN ('approved', 'live')",
    )
    op.drop_index(op.f("ix_launches_created_at"), table_name="launches")
    op.drop_table("launches")
    op.drop_index(
        op.f("ix_email_verification_token_hash"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_expires_at"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_deleted_at"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_created_at"), table_name="email_verification"
    )
    op.drop_table("email_verification")
    op.drop_index(
        op.f("ix_backup_codes_enrollments_deleted_at"),
        table_name="backup_codes_enrollments",
    )
    op.drop_index(
        op.f("ix_backup_codes_enrollments_created_at"),
        table_name="backup_codes_enrollments",
    )
    op.drop_table("backup_codes_enrollments")
    op.drop_index(
        op.f("ix_authentication_sessions_identity_id"),
        table_name="authentication_sessions",
    )
    op.drop_index(
        op.f("ix_authentication_sessions_expires_at"),
        table_name="authentication_sessions",
    )
    op.drop_index(
        op.f("ix_authentication_sessions_deleted_at"),
        table_name="authentication_sessions",
    )
    op.drop_index(
        op.f("ix_authentication_sessions_created_at"),
        table_name="authentication_sessions",
    )
    op.drop_table("authentication_sessions")
    op.drop_index("ix_users_email_case_insensitive", table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_email_logs_to_email_addr"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_status"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_processor_id"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_email_template"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_deleted_at"), table_name="email_logs")
    op.drop_index(
        "ix_email_logs_deduplication_key",
        table_name="email_logs",
        postgresql_where="deduplication_key IS NOT NULL",
    )
    op.drop_index(op.f("ix_email_logs_created_at"), table_name="email_logs")
    op.drop_table("email_logs")
    public_pg_trgm = PGExtension(schema="public", signature="pg_trgm")
    op.drop_entity(public_pg_trgm)

    public_citext = PGExtension(schema="public", signature="citext")
    op.drop_entity(public_citext)

    public_uuid_ossp = PGExtension(schema="public", signature="uuid-ossp")
    op.drop_entity(public_uuid_ossp)

    # ### end Alembic commands ###
