"""news pipeline

Revision ID: 46d6516de288
Revises: b8c6b4cffbb5
Create Date: 2026-10-04 00:03:26.766195

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "46d6516de288"
down_revision = "b8c6b4cffbb5"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("surface", sa.String(length=16), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sender_hash", sa.String(length=64), nullable=True),
        sa.Column("digested", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_pkey")),
    )
    op.create_index(
        op.f("ix_feedback_created_at"), "feedback", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_deleted_at"), "feedback", ["deleted_at"], unique=False
    )
    op.create_table(
        "job_runs",
        sa.Column("kind", sa.Unicode(), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("state", sa.Unicode(), nullable=False),
        sa.Column("lane", sa.String(length=32), nullable=False),
        sa.Column("served_model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("prompt_digest", sa.String(length=64), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("error_class", sa.String(length=32), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("retry_of", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["retry_of"],
            ["job_runs.id"],
            name=op.f("job_runs_retry_of_fkey"),
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("job_runs_pkey")),
    )
    op.create_index(
        "ix_job_runs_kind_started_at", "job_runs", ["kind", "started_at"], unique=False
    )
    op.create_index(
        "ix_job_runs_open",
        "job_runs",
        ["state"],
        unique=False,
        postgresql_where="state IN ('queued', 'running')",
    )
    op.create_index("ix_job_runs_subject", "job_runs", ["subject"], unique=False)
    op.create_table(
        "news_briefings",
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("built_for", sa.Date(), nullable=False),
        sa.Column("built_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("news_briefings_pkey")),
        sa.UniqueConstraint(
            "profile_id", "built_for", "built_at", name="uq_news_briefing_build"
        ),
    )
    op.create_index(
        op.f("ix_news_briefings_built_at"), "news_briefings", ["built_at"], unique=False
    )
    op.create_index(
        op.f("ix_news_briefings_profile_id"),
        "news_briefings",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "news_clusters",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("publisher_count", sa.Integer(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("lead_source_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("news_clusters_pkey")),
        sa.UniqueConstraint("key", name=op.f("news_clusters_key_key")),
    )
    op.create_index(
        op.f("ix_news_clusters_created_at"),
        "news_clusters",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_clusters_deleted_at"),
        "news_clusters",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_clusters_first_seen_at"),
        "news_clusters",
        ["first_seen_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_clusters_last_seen_at"),
        "news_clusters",
        ["last_seen_at"],
        unique=False,
    )
    op.create_table(
        "news_cluster_members",
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("item_id", sa.String(length=2048), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_key", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("pub_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("seen_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_clusters.id"],
            name=op.f("news_cluster_members_cluster_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint(
            "cluster_id", "source_id", "item_id", name=op.f("news_cluster_members_pkey")
        ),
    )
    op.create_index(
        "ix_news_cluster_members_seen_at",
        "news_cluster_members",
        ["seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_news_cluster_members_url_key",
        "news_cluster_members",
        ["url_key"],
        unique=False,
    )
    op.create_table(
        "news_cluster_scores",
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("why", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("scored_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("publisher_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_clusters.id"],
            name=op.f("news_cluster_scores_cluster_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint(
            "cluster_id", "profile_id", name=op.f("news_cluster_scores_pkey")
        ),
    )
    op.create_index(
        op.f("ix_news_cluster_scores_scored_at"),
        "news_cluster_scores",
        ["scored_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_news_cluster_scores_scored_at"), table_name="news_cluster_scores"
    )
    op.drop_table("news_cluster_scores")
    op.drop_index("ix_news_cluster_members_url_key", table_name="news_cluster_members")
    op.drop_index("ix_news_cluster_members_seen_at", table_name="news_cluster_members")
    op.drop_table("news_cluster_members")
    op.drop_index(op.f("ix_news_clusters_last_seen_at"), table_name="news_clusters")
    op.drop_index(op.f("ix_news_clusters_first_seen_at"), table_name="news_clusters")
    op.drop_index(op.f("ix_news_clusters_deleted_at"), table_name="news_clusters")
    op.drop_index(op.f("ix_news_clusters_created_at"), table_name="news_clusters")
    op.drop_table("news_clusters")
    op.drop_index(op.f("ix_news_briefings_profile_id"), table_name="news_briefings")
    op.drop_index(op.f("ix_news_briefings_built_at"), table_name="news_briefings")
    op.drop_table("news_briefings")
    op.drop_index("ix_job_runs_subject", table_name="job_runs")
    op.drop_index(
        "ix_job_runs_open",
        table_name="job_runs",
        postgresql_where="state IN ('queued', 'running')",
    )
    op.drop_index("ix_job_runs_kind_started_at", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_feedback_deleted_at"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_created_at"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
