"""add promotion

Revision ID: 88b8a2396a0e
Revises: 54267f23e641
Create Date: 2026-06-21 22:18:52.668285

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "88b8a2396a0e"
down_revision = "54267f23e641"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=2048), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="pending_payment",
            nullable=False,
        ),
        sa.Column("payment_ref", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("activated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("active_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("impressions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("clicks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("promotions_author_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("promotions_pkey")),
        sa.UniqueConstraint("payment_ref", name=op.f("promotions_payment_ref_key")),
    )
    op.create_index(
        op.f("ix_promotions_active_until"), "promotions", ["active_until"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_author_id"), "promotions", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_category"), "promotions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_created_at"), "promotions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_deleted_at"), "promotions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_status"), "promotions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promotions_status"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_deleted_at"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_created_at"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_category"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_author_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_active_until"), table_name="promotions")
    op.drop_table("promotions")
    # ### end Alembic commands ###
