"""add promotion category status composite index

Revision ID: abf4cc7dd659
Revises: 74f6845e5f1c
Create Date: 2026-07-21 16:44:56.433943

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "abf4cc7dd659"
down_revision = "74f6845e5f1c"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_promotions_category_status",
        "promotions",
        ["category", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_promotions_category_status", table_name="promotions")
    # ### end Alembic commands ###
