"""widen oauth token columns to text

Revision ID: 74f6845e5f1c
Revises: 4d96c2d1e08a
Create Date: 2026-07-21 00:38:18.119758

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "74f6845e5f1c"
down_revision = "4d96c2d1e08a"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oauth_accounts",
        "access_token",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_accounts",
        "refresh_token",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    # Truncate to fit varchar(1024) via USING — the whole reason for the upgrade
    # was that Microsoft tokens exceed 1024, so a bare narrow would raise
    # "value too long" on populated data.
    op.alter_column(
        "oauth_accounts",
        "refresh_token",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=True,
        postgresql_using="left(refresh_token, 1024)",
    )
    op.alter_column(
        "oauth_accounts",
        "access_token",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
        postgresql_using="left(access_token, 1024)",
    )
    # ### end Alembic commands ###
