"""add user promotion_emails_enabled

Revision ID: 9295e9705921
Revises: f92ebdfbe7b0
Create Date: 2026-06-23 18:53:02.068003

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "9295e9705921"
down_revision = "f92ebdfbe7b0"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "promotion_emails_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "promotion_emails_enabled")
    # ### end Alembic commands ###
