"""drop promotions table

Revision ID: 93a465af44ad
Revises: abf4cc7dd659
Create Date: 2026-07-21 23:02:57.987256

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "93a465af44ad"
down_revision = "abf4cc7dd659"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promotions_active_until"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_author_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_category"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_category_status"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_created_at"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_deleted_at"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_status"), table_name="promotions")
    op.drop_table("promotions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("link", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column(
            "image_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "duration_minutes", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("amount_cents", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=16),
            server_default=sa.text("'pending_payment'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "payment_ref", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "paid_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "activated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "active_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "impressions",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "clicks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("promotions_author_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("promotions_pkey")),
        sa.UniqueConstraint(
            "payment_ref",
            name=op.f("promotions_payment_ref_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_promotions_status"), "promotions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_deleted_at"), "promotions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_created_at"), "promotions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_category_status"),
        "promotions",
        ["category", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotions_category"), "promotions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_author_id"), "promotions", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_active_until"), "promotions", ["active_until"], unique=False
    )
    # ### end Alembic commands ###
