"""add user_followed_sources

Revision ID: 0ed2b275d086
Revises: 9295e9705921
Create Date: 2026-06-23 19:41:15.442990

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "0ed2b275d086"
down_revision = "9295e9705921"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_followed_sources",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_followed_sources_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_followed_sources_pkey")),
        sa.UniqueConstraint("user_id", "source_id", name="uq_user_followed_source"),
    )
    op.create_index(
        op.f("ix_user_followed_sources_created_at"),
        "user_followed_sources",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_followed_sources_deleted_at"),
        "user_followed_sources",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_followed_sources_user_id"),
        "user_followed_sources",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_followed_sources_user_id"), table_name="user_followed_sources"
    )
    op.drop_index(
        op.f("ix_user_followed_sources_deleted_at"), table_name="user_followed_sources"
    )
    op.drop_index(
        op.f("ix_user_followed_sources_created_at"), table_name="user_followed_sources"
    )
    op.drop_table("user_followed_sources")
    # ### end Alembic commands ###
