"""drop promotion body column

Revision ID: 4d96c2d1e08a
Revises: 9b7ace2a9be5
Create Date: 2026-07-19 20:56:21.687766

"""

import sqlalchemy as sa
from alembic import op

# Outception Custom Imports

# revision identifiers, used by Alembic.
revision = "4d96c2d1e08a"
down_revision = "9b7ace2a9be5"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "body")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so re-adding a NOT NULL column succeeds on a populated
    # table (existing rows get ""); the app never reads body anymore.
    op.add_column(
        "promotions",
        sa.Column(
            "body",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###
